import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { readClaudeSession, readClaudeTranscript } from "./claude-transcript.js";

// A Claude Code transcript is read into turns of calls the readings score; these pin where a turn begins, what counts
// as a failure, and that a subagent's calls land in the turn that was running when it made them.

const dirs: string[] = [];
const tempDir = (): string => {
    const dir = mkdtempSync(join(tmpdir(), "claude-transcript-"));
    dirs.push(dir);
    return dir;
};

afterEach(() => {
    for (const dir of dirs.splice(0)) {
        rmSync(dir, { recursive: true, force: true });
    }
});

const ROOT = "/repo";
const at = (second: number): string => new Date(Date.UTC(2026, 8, 1, 12, 0, second)).toISOString();

const prompt = (second: number, content: unknown, extra: object = {}): string =>
    JSON.stringify({ type: "user", sessionId: "s-1", cwd: ROOT, timestamp: at(second), message: { role: "user", content }, ...extra });
const uses = (second: number, ...blocks: object[]): string =>
    JSON.stringify({ type: "assistant", sessionId: "s-1", timestamp: at(second), message: { role: "assistant", content: blocks } });
const tool = (id: string, name: string, input: object): object => ({ type: "tool_use", id, name, input });
const result = (second: number, id: string, content: string, isError = false): string =>
    JSON.stringify({
        type: "user",
        timestamp: at(second),
        message: { role: "user", content: [{ type: "tool_result", tool_use_id: id, content, is_error: isError }] },
    });

const SESSION = [
    JSON.stringify({ type: "queue-operation", operation: "enqueue", timestamp: at(0) }),
    prompt(1, "find the parser and fix it"),
    uses(2, tool("t1", "Bash", { command: "ls" }), tool("t2", "Grep", { pattern: "parse" })),
    result(3, "t1", "src\nREADME.md"),
    uses(4, tool("t3", "Read", { file_path: "/repo/src/parse.ts" })),
    result(5, "t3", "File does not exist.", true),
    // Inserted by the CLI, not typed by anyone: never a turn of its own.
    prompt(6, "Caveat: the messages below were generated by the user while running local commands.", { isMeta: true }),
    prompt(7, [{ type: "text", text: "<local-command-stdout>ok</local-command-stdout>" }]),
    prompt(20, [{ type: "text", text: "now edit it" }]),
    uses(21, tool("t4", "Edit", { file_path: "/repo/src/parser.ts", old_string: "a", new_string: "b" })),
    "not json at all",
    result(22, "t4", "ok"),
].join("\n");

test("turns begin at real prompts, and calls carry their kind, target and root-relative file", () => {
    const session = readClaudeTranscript(SESSION, { root: ROOT });
    expect(session).toMatchObject({ sessionId: "s-1", cwd: ROOT });
    expect(session.turns.map((turn) => [turn.index, turn.prompt])).toEqual([
        [0, "find the parser and fix it"],
        [1, "now edit it"],
    ]);
    expect(session.turns[0]?.calls.map((call) => [call.name, call.category, call.target ?? null])).toEqual([
        ["Bash", "execute", "ls"],
        ["Grep", "search", "parse"],
        ["Read", "read", "/repo/src/parse.ts"],
    ]);
    expect(session.turns[1]?.calls[0]?.locations).toEqual([{ path: "src/parser.ts" }]);
});

test("a failure is a tool_result marked as an error, kept with the start of what it said", () => {
    const session = readClaudeTranscript(SESSION, { root: ROOT });
    expect(session.turns[0]?.failures).toEqual([{ id: "t3", text: "File does not exist." }]);
    expect(session.turns[1]?.failures).toEqual([]);
});

test("a subagent's calls count in the turn that was running when it made them", () => {
    const dir = tempDir();
    const file = join(dir, "s-1.jsonl");
    writeFileSync(file, SESSION);
    mkdirSync(join(dir, "s-1", "subagents"), { recursive: true });
    writeFileSync(
        join(dir, "s-1", "subagents", "agent-a.jsonl"),
        [
            JSON.stringify({ type: "user", isSidechain: true, timestamp: at(8), message: { role: "user", content: "look around" } }),
            JSON.stringify({
                type: "assistant",
                isSidechain: true,
                timestamp: at(9),
                message: { content: [tool("s1", "Bash", { command: "rg parse" })] },
            }),
            JSON.stringify({
                type: "user",
                isSidechain: true,
                timestamp: at(10),
                message: { content: [{ type: "tool_result", tool_use_id: "s1", content: "boom", is_error: true }] },
            }),
        ].join("\n"),
    );
    const session = readClaudeSession(file, { root: ROOT });
    expect(session?.turns[0]?.calls.map((call) => [call.id, call.subagent])).toEqual([
        ["t1", false],
        ["t2", false],
        ["t3", false],
        ["s1", true],
    ]);
    expect(session?.turns[0]?.failures.map((failure) => failure.id)).toEqual(["t3", "s1"]);
    expect(session?.turns[1]?.calls.map((call) => call.id)).toEqual(["t4"]);
});

test("a slash command and an image-only prompt start turns; a compaction summary and an interruption do not", () => {
    const text = [
        prompt(1, "first"),
        uses(2, tool("t1", "Bash", { command: "ls" })),
        prompt(3, [{ type: "text", text: "[Request interrupted by user]" }]),
        prompt(4, "<command-message>review</command-message>\n<command-name>/review</command-name>"),
        uses(5, tool("t2", "Read", { file_path: "/repo/a.ts" })),
        prompt(6, "This session is being continued from a previous conversation.", { isCompactSummary: true }),
        uses(7, tool("t3", "Grep", { pattern: "x" })),
        prompt(8, [{ type: "image", source: { type: "base64", data: "" } }]),
        uses(9, tool("t4", "Bash", { command: "pwd" })),
    ].join("\n");
    const turns = readClaudeTranscript(text, { root: ROOT }).turns;
    expect(turns.map((turn) => [turn.prompt, turn.calls.map((call) => call.id)])).toEqual([
        ["first", ["t1"]],
        ["<command-message>review</command-message>\n<command-name>/review</command-name>", ["t2", "t3"]],
        ["", ["t4"]],
    ]);
});

test("a session file that cannot be read is no session, and one with no prompt has no turns", () => {
    expect(readClaudeSession(join(tempDir(), "missing.jsonl"), { root: ROOT })).toBeUndefined();
    expect(readClaudeTranscript(uses(1, tool("t1", "Bash", { command: "ls" })), { root: ROOT }).turns).toEqual([]);
});
