import type { Provider, ResolvedInputs } from "@intentic/engine";
import { z } from "zod";
import { normalize, starterDockerfile } from "../core/ci-yaml.js";
import { parseInputs, registryImage } from "../core/inputs.js";
import type { GitLabApi } from "./gitlab-api.js";
import { gitlabApi } from "./gitlab-api.js";

// One environment's build job. Unlike the GitHub path (one workflow file per env), GitLab uses a single
// .gitlab-ci.yml, so this provider is per-APP and emits one job per environment gated by branch.
const glCiEnvSchema = z.object({
    name: z.string(),
    branch: z.string(),
    tag: z.string(),
    // The Komodo deployment the job's notify step redeploys (auto_update polling is the backstop).
    deploymentId: z.string(),
});
const glCiSchema = z.object({
    url: z.string(),
    owner: z.string(),
    repoName: z.string(),
    token: z.string(),
    // The container-registry authority (e.g. registry.gitlab.com); image = registry/owner/repo:tag.
    registry: z.string(),
    // Komodo's PUBLIC url the notify step logs into (GitLab-hosted runners reach it through the tunnel).
    komodoUrl: z.string(),
    // The Komodo admin the notify step logs in with (the password is set as a CI/CD variable).
    adminUser: z.string(),
    adminPassword: z.string(),
    environments: z.array(glCiEnvSchema),
});
type GlCiInputs = z.infer<typeof glCiSchema>;
const parse = (inputs: ResolvedInputs): GlCiInputs => parseInputs(glCiSchema, inputs, "gl-ci");

const CI_FILE_PATH = ".gitlab-ci.yml";
const DOCKERFILE_PATH = "Dockerfile";

const VAR_KOMODO = "KOMODO_PASSWORD";

// A YAML block-sequence item that is a JSON double-quoted scalar. YAML 1.2 is a JSON superset, so
// JSON.stringify robustly escapes any command (quotes, $, backslashes) into a valid script line.
const scriptLine = (command: string): string => `    - ${JSON.stringify(command)}`;

// One build job: build on docker-in-docker, push to the GitLab Container Registry via the built-in job-token
// creds, then log into Komodo and trigger an immediate Deploy. Gated to its env's branch via rules:. The
// host is never SSHed from CI, its Periphery pulls outbound.
const jobYaml = (parsed: GlCiInputs, environment: GlCiInputs["environments"][number]): string => {
    const image = registryImage({ registry: parsed.registry, owner: parsed.owner, repoName: parsed.repoName, tag: environment.tag });
    const shaImage = `${parsed.registry}/${parsed.owner}/${parsed.repoName}:$CI_COMMIT_SHA`;
    return [
        `build-${environment.name}:`,
        "  stage: build",
        "  image: docker:29",
        "  services:",
        "    - docker:29-dind",
        "  rules:",
        `    - if: '$CI_COMMIT_BRANCH == "${environment.branch}"'`,
        "  before_script:",
        scriptLine('docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"'),
        scriptLine("apk add --no-cache curl"),
        "  script:",
        scriptLine(`docker build -t ${image} -t ${shaImage} .`),
        scriptLine(`docker push ${image}`),
        scriptLine(`docker push ${shaImage}`),
        scriptLine(
            `JWT=$(curl -sf ${parsed.komodoUrl}/auth/login/LoginLocalUser -H 'Content-Type: application/json' ` +
                `-d '{"username":"${parsed.adminUser}","password":"'"$${VAR_KOMODO}"'"}' | sed -n 's/.*"jwt":"\\([^"]*\\)".*/\\1/p')`,
        ),
        scriptLine(
            `curl -sf ${parsed.komodoUrl}/execute -H "Authorization: $JWT" -H 'Content-Type: application/json' ` +
                `-d '{"type":"Deploy","params":{"deployment":"${environment.deploymentId}"}}'`,
        ),
    ].join("\n");
};

// The .gitlab-ci.yml: one build job per environment. build → push to registry → notify Komodo to redeploy.
const gitlabCiYaml = (parsed: GlCiInputs): string =>
    [
        "# Generated by intentic: build → push to the GitLab Container Registry → notify Komodo to redeploy.",
        "stages:",
        "  - build",
        "",
        ...parsed.environments.map((environment) => jobYaml(parsed, environment)),
        "",
    ].join("\n");

// The app's CI/CD wiring for the GitLab path: commits the single .gitlab-ci.yml and sets the Komodo-login
// CI/CD variable its notify steps consume. Mirrors gh-ci.ts but per-app (one file, all envs) and with
// plaintext project variables instead of libsodium-encrypted Actions secrets. PENDING-guards on owner (the
// gitlab node's output) and komodoUrl so a plan proceeds before the forge account and Komodo are up.
export const createGlCiProvider = (api: GitLabApi = gitlabApi): Provider => ({
    read: async (inputs, ctx) => {
        if (typeof inputs["token"] !== "string" || typeof inputs["owner"] !== "string" || typeof inputs["komodoUrl"] !== "string") {
            return undefined;
        }
        const parsed = parse(inputs);
        try {
            const file = await api.readFile({
                url: parsed.url,
                token: parsed.token,
                owner: parsed.owner,
                name: parsed.repoName,
                path: CI_FILE_PATH,
                branch: parsed.environments[0]?.branch ?? "main",
            });
            if (file === undefined) {
                return undefined;
            }
            return { outputs: {}, detail: { ci: file.content } };
        } catch (error) {
            ctx.log(`gl-ci "${ctx.id}": GitLab not reachable yet: ${String(error)}`);
            return undefined;
        }
    },
    diff: (inputs, observed) => {
        const ci = observed.detail?.["ci"];
        if (typeof ci !== "string" || normalize(ci) !== normalize(gitlabCiYaml(parse(inputs)))) {
            return { action: "update", reason: ".gitlab-ci.yml differs from desired" };
        }
        return { action: "noop" };
    },
    apply: async (inputs) => {
        const parsed = parse(inputs);
        const common = { url: parsed.url, token: parsed.token, owner: parsed.owner, name: parsed.repoName };
        const branch = parsed.environments[0]?.branch ?? "main";

        // The Komodo admin password the notify steps log in with, set as a plaintext project CI/CD variable.
        await api.setCiVariable({ ...common, key: VAR_KOMODO, value: parsed.adminPassword });

        // Seed a starter Dockerfile if the repo has none.
        const dockerfile = await api.readFile({ ...common, path: DOCKERFILE_PATH, branch });
        if (dockerfile === undefined) {
            await api.commitFile({ ...common, path: DOCKERFILE_PATH, content: starterDockerfile(), branch, message: "intentic: starter Dockerfile" });
        }

        // Commit the CI file LAST so its first run already sees the Dockerfile + variable.
        await api.commitFile({ ...common, path: CI_FILE_PATH, content: gitlabCiYaml(parsed), branch, message: "intentic: GitLab CI pipeline" });
        return {};
    },
    delete: async (inputs) => {
        if (typeof inputs["token"] !== "string" || typeof inputs["owner"] !== "string") {
            return;
        }
        const parsed = parse(inputs);
        const common = { url: parsed.url, token: parsed.token, owner: parsed.owner, name: parsed.repoName };
        await api.deleteFile({
            ...common,
            path: CI_FILE_PATH,
            branch: parsed.environments[0]?.branch ?? "main",
            message: "intentic: remove CI pipeline",
        });
        await api.deleteCiVariable({ ...common, key: VAR_KOMODO });
    },
});
