export { CHORE_KINDS, CHORES, choreAutomationPrompt, choreById, chorePrompt, repoLabel, repoName } from "./chores.js";
export { FIX_DEPS_AUTOMATION } from "./fix-deps.js";
export type { Chore, ChoreContext, ChoreFinding, ChoreKind, ChoreKindSpec, ChoreStance } from "./chores.js";
export { bucketOf, digestOf } from "./digest.js";
export { CHORE_INVARIANTS, composeAsk, REFACTOR_INVARIANTS, REPORT_INVARIANTS, TRIAGE_NOTE } from "./prompt.js";
export type { Ask } from "./prompt.js";
export { updateBrief } from "./extension-update.js";
export type { UpdateBrief } from "./extension-update.js";
export { PROBES, probeSpec } from "./probes.js";
export type { ProbeSpec } from "./probes.js";
export { WORKSPACE_ROOT_EXCLUDE_ENV } from "./workspace-scope.js";
export { componentStem, frameworksOf, IDIOM_RULES, idiomRule, normalizePath, UI_FRAMEWORKS, usesTailwind } from "./stack.js";
export type { IdiomRule, UiFramework } from "./stack.js";
export { assessChore, assessReport, ledgerKey, unseenVerdicts } from "./verdict.js";
export type { ChoreState, ChoreVerdict } from "./verdict.js";
