import type { Provider, ResolvedInputs } from "@intentic/engine";
import { z } from "zod";
import { normalize, starterDockerfile } from "../core/ci-yaml.js";
import { parseInputs } from "../core/inputs.js";
import type { GitHubApi } from "./github-api.js";
import { githubApi } from "./github-api.js";

const ghCiSchema = z.object({
    owner: z.string(),
    repoName: z.string(),
    // The env branch the workflow triggers on (production -> "main").
    branch: z.string(),
    // The image tag = the environment name, so co-located environments publish to distinct tags.
    tag: z.string(),
    token: z.string(),
    // Komodo's PUBLIC url the notify step logs into (GitHub-hosted runners reach it through the tunnel).
    komodoUrl: z.string(),
    // The Komodo admin the workflow's notify step logs in with (the password is stored as a repo secret).
    adminUser: z.string(),
    adminPassword: z.string(),
    // The Komodo deployment id the notify step redeploys (auto_update polling is the backstop).
    deployment: z.string(),
});
type GhCiInputs = z.infer<typeof ghCiSchema>;
const parse = (inputs: ResolvedInputs): GhCiInputs => parseInputs(ghCiSchema, inputs, "gh-ci");

const SECRET_KOMODO = "KOMODO_PASSWORD";
const workflowPath = (tag: string): string => `.github/workflows/build-${tag}.yml`;
const DOCKERFILE_PATH = "Dockerfile";

// The GitHub Actions workflow: on a push to the env branch it builds the Dockerfile, pushes the image to
// GHCR (with the job's own GITHUB_TOKEN, no extra registry secret), then logs into Komodo and triggers an
// immediate Deploy. Mirrors the Forgejo stack's workflow: CI only builds + pushes; Komodo rolls out. The
// host is never SSHed from CI, its Periphery pulls outbound.
const workflowYaml = (parsed: GhCiInputs): string => {
    const image = `ghcr.io/${parsed.owner}/${parsed.repoName}`;
    return [
        "# Generated by intentic: build the image, push it to GHCR, notify Komodo to redeploy.",
        `name: build-${parsed.tag}`,
        "on:",
        "  push:",
        `    branches: ["${parsed.branch}"]`,
        "jobs:",
        "  build:",
        "    runs-on: ubuntu-24.04",
        "    permissions:",
        "      contents: read",
        "      packages: write",
        "    steps:",
        "      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1",
        "      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0",
        "        with:",
        "          registry: ghcr.io",
        "          username: ${{ github.actor }}",
        "          password: ${{ secrets.GITHUB_TOKEN }}",
        "      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2",
        "        with:",
        "          context: .",
        "          push: true",
        "          tags: |",
        `            ${image}:${parsed.tag}`,
        `            ${image}:$\{{ github.sha }}`,
        "      - name: notify komodo to redeploy",
        "        run: |",
        `          KOMODO_PASSWORD='\${{ secrets.${SECRET_KOMODO} }}'`,
        `          JWT=$(curl -sf ${parsed.komodoUrl}/auth/login/LoginLocalUser -H 'Content-Type: application/json' \\`,
        `            -d '{"username":"${parsed.adminUser}","password":"'"$KOMODO_PASSWORD"'"}' | sed -n 's/.*"jwt":"\\([^"]*\\)".*/\\1/p')`,
        `          curl -sf ${parsed.komodoUrl}/execute -H "Authorization: $JWT" -H 'Content-Type: application/json' \\`,
        `            -d '{"type":"Deploy","params":{"deployment":"${parsed.deployment}"}}'`,
        "",
    ].join("\n");
};

// The app's CI/CD wiring for the GitHub path: commits the build-and-push workflow and sets the Komodo-login
// secret its notify step consumes. Mirrors forgejo/ci.ts with GitHub Actions + GHCR. The secret cannot be
// read back, so it is re-set every apply, idempotently; PENDING-guards on owner (the github node's output)
// and komodoUrl so a plan proceeds before the forge account and Komodo are up.
export const createGhCiProvider = (api: GitHubApi = githubApi): Provider => ({
    read: async (inputs, ctx) => {
        if (typeof inputs["token"] !== "string" || typeof inputs["owner"] !== "string" || typeof inputs["komodoUrl"] !== "string") {
            return undefined;
        }
        const parsed = parse(inputs);
        try {
            const file = await api.readFile({
                token: parsed.token,
                owner: parsed.owner,
                repo: parsed.repoName,
                path: workflowPath(parsed.tag),
                branch: parsed.branch,
            });
            if (file === undefined) {
                return undefined;
            }
            return { outputs: {}, detail: { workflow: file.content } };
        } catch (error) {
            ctx.log(`gh-ci "${ctx.id}": GitHub not reachable yet: ${String(error)}`);
            return undefined;
        }
    },
    diff: (inputs, observed) => {
        const workflow = observed.detail?.["workflow"];
        if (typeof workflow !== "string" || normalize(workflow) !== normalize(workflowYaml(parse(inputs)))) {
            return { action: "update", reason: "GitHub Actions workflow differs from desired" };
        }
        return { action: "noop" };
    },
    apply: async (inputs) => {
        const parsed = parse(inputs);
        const common = { token: parsed.token, owner: parsed.owner, repo: parsed.repoName };

        // The Komodo admin password the workflow's notify step logs in with.
        await api.setRepoSecret({ ...common, secretName: SECRET_KOMODO, value: parsed.adminPassword });

        // Seed a starter Dockerfile if the repo has none.
        const dockerfile = await api.readFile({ ...common, path: DOCKERFILE_PATH, branch: parsed.branch });
        if (dockerfile === undefined) {
            await api.commitFile({
                ...common,
                path: DOCKERFILE_PATH,
                content: starterDockerfile(),
                branch: parsed.branch,
                message: "intentic: starter Dockerfile",
            });
        }

        // Commit the workflow LAST so its first run already sees the Dockerfile + secret.
        const existing = await api.readFile({ ...common, path: workflowPath(parsed.tag), branch: parsed.branch });
        await api.commitFile({
            ...common,
            path: workflowPath(parsed.tag),
            content: workflowYaml(parsed),
            branch: parsed.branch,
            message: "intentic: GitHub Actions workflow",
            ...(existing !== undefined ? { sha: existing.sha } : {}),
        });
        return {};
    },
    delete: async (inputs) => {
        if (typeof inputs["token"] !== "string" || typeof inputs["owner"] !== "string") {
            return;
        }
        const parsed = parse(inputs);
        const common = { token: parsed.token, owner: parsed.owner, repo: parsed.repoName };
        await api.deleteFile({ ...common, path: workflowPath(parsed.tag), branch: parsed.branch, message: "intentic: remove workflow" });
        await api.deleteRepoSecret({ ...common, secretName: SECRET_KOMODO });
    },
});
