import type { StateFile } from "./state-portability.js";

// /history holds daemon state outside /work's `.intentic/`: real git dirs (in-tree .git is a pointer file), the fleet
// registry, turn journal, ledgers, checkpoint scopes, isolated checkouts. Nothing here is watched, unlike `.intentic`.
// history-state-coverage.test.ts enforces this list stays complete.

// historyRoot-relative paths, forward-slash, matched by prefix; a directory keeps its trailing slash so it can't
// prefix-match a sibling file.
export const HISTORY_STATE_FILES: readonly StateFile[] = [
    /* ---- the machinery a restored workspace is inert without ---- */

    // Every repo's real git dir, including root's own; missing it breaks a repo outright. Branches live here too.
    { path: "gits/", portability: "carry" },
    // Checkpoint timeline (one bare repo per scope); lets "restore to before that turn" still reach back.
    { path: "scopes/", portability: "carry" },
    // The fleet: every conversation card, its branch, session ids and standing.
    { path: "agents.json", portability: "carry" },
    { path: "turns/", portability: "carry" },
    // Armed condition watches; carries safely: the journal holds no credential, only names re-derived on target.
    { path: "watches/", portability: "carry" },
    { path: "transcripts/", portability: "carry" },
    // What each message can restore to (a checkpoint or isolated commit); the join between transcripts and scopes.
    { path: "turn-anchors.json", portability: "carry" },
    // Index of published-page conversations; the pages travel with /work anyway, this makes one withdrawable.
    { path: "shares.json", portability: "carry" },
    { path: "activity.jsonl", portability: "carry" },
    { path: "usage.jsonl", portability: "carry" },
    { path: "account-usage.json", portability: "carry" },
    { path: "provider-refusals.json", portability: "carry" },
    // Models refused to this sandbox's credentials; expires daily, same subscriptions apply elsewhere.
    { path: "model-refusals.json", portability: "carry" },
    // First-time dependency setup requests; carried so an interrupted queue survives export, entries self-remove.
    { path: "dependency-requests.json", portability: "carry" },
    // Which device cards were already offered; carry, not identity, since it holds ids, never a token.
    { path: "host-setup-seeded.json", portability: "carry" },
    // The deploy engine's own ledgers: a run's events and check results the Pipelines view reads.
    { path: "apply-events.ndjson", portability: "carry" },
    { path: "check-events/", portability: "carry" },

    /* ---- regenerated by the target ---- */

    // Deliberately omitted: the branch lives in gits/, the registry in agents.json; regenerated on the next turn.
    {
        path: "worktrees/",
        portability: "derived",
        note: "Each conversation re-attaches its checkout from its branch on its next turn.",
    },
    // Search phrase index, derived from transcripts/; rebuilt by the first boot's backfill instead of carried.
    { path: "said-index/", portability: "derived", note: "Rebuilt from the carried transcripts by the first boot's backfill." },
    { path: "overlays/", portability: "derived" },
    { path: "logs/", portability: "derived" },
    { path: "trash/", portability: "derived" },
    { path: ".isolation-probe", portability: "derived" },
    // Finished bundles, excluded so an export doesn't pack every prior export in; kept off /work, unwatched.
    { path: "exports/", portability: "derived" },
    // Bundles being taken in, mid-review; excluded as someone else's. Deleted on apply/abandon, swept after a crash.
    { path: "arrivals/", portability: "derived" },

    /* ---- credentials ---- */

    // The ssh alias dir ~/.ssh/intentic-hosts symlinks to: per-host config, keys and passphrases.
    {
        path: "ssh-hosts/",
        portability: "secret",
        note: "Re-add each ssh host on the Capabilities view, its key does not travel.",
    },
    // The cli-proxy's config, which holds the routed subscriptions' provider tokens.
    {
        path: "translator/",
        portability: "secret",
        note: "Sign the routed AI subscriptions in again on the Agent tab.",
    },

    /* ---- identity: what binds this sandbox to its owner, its browsers and its host ---- */

    // Signs every browser session cookie; carrying it would let the holder mint sessions against the target.
    { path: "session-secret", portability: "identity", note: "Sign in again, the target signs its own sessions." },
    {
        path: "browser-access-disabled",
        portability: "identity",
        note: "Account-deletion retirement belongs to the source sandbox; the imported copy starts with fresh browser access.",
    },
    {
        path: "push.json",
        portability: "identity",
        note: "Re-enable notifications in the browsers you use, a push subscription is bound to the sandbox that minted it.",
    },
    { path: "sync-enrollments.json", portability: "identity", note: "Re-pair desktop sync from the Sync tab." },
    { path: "sync-pair-consumed.json", portability: "identity" },
    { path: "host-enrollments.json", portability: "identity" },
    // A connected browser's enrollment, paired to this sandbox; carrying it elsewhere is dead weight or worse.
    { path: "webext-enrollments.json", portability: "identity", note: "Pair your browser again from its card: the extension is still installed." },
    // The browser pairing burn list; a redeemed pairing must not read as fresh wherever this file travels.
    { path: "webext-pair-consumed.json", portability: "identity" },
    // Setup-device pairing burn list; carrying it would mark another sandbox's fresh pairing as spent.
    { path: "host-pair-consumed.json", portability: "identity" },
    // A runner's enrollment names this sandbox as parent; elsewhere its digest would dial the old parent.
    { path: "runner-enrollments.json", portability: "identity" },
    { path: "runner-pair-consumed.json", portability: "identity" },
    // This container's own identity and reconnect token; elsewhere it would dial the parent as this runner.
    { path: "runner-identity.json", portability: "identity" },
    { path: "local-cert/", portability: "identity" },
];
