import { ICONS, type IconName } from "@intentic/ui/icons";
import { glyphBody } from "@intentic/ui/glyph";

/** Monaco's semantic defaults; its component-specific names inherit these through its icon registry. */
export const EDITOR_ICONS = {
    account: `user`,
    add: `plus`,
    "arrow-down": `arrow-down`,
    "arrow-right": `arrow-right`,
    "arrow-swap": `repeat`,
    "arrow-up": `arrow-up`,
    "bell-slash": `volume-off`,
    "case-sensitive": `case-sensitive`,
    check: `check`,
    "chevron-down": `chevron-down`,
    "chevron-left": `chevron-left`,
    "chevron-right": `chevron-right`,
    "chevron-up": `chevron-up`,
    close: `times`,
    "collapse-all": `collapse-all`,
    "compare-changes": `split-columns`,
    copy: `copy`,
    dash: `minus`,
    discard: `undo`,
    error: `times-circle`,
    "expand-all": `expand-all`,
    file: `file`,
    fold: `collapse-all`,
    folder: `folder`,
    gear: `cog`,
    "index-zero": `code-number`,
    info: `info-circle`,
    issues: `exclamation-circle`,
    "keyboard-tab": `keyboard-tab`,
    "keyboard-tab-above": `arrow-up`,
    "keyboard-tab-below": `arrow-down`,
    "light-bulb": `bolt`,
    "lightbulb-autofix": `wrench`,
    "lightbulb-sparkle": `sparkles`,
    "lightbulb-sparkle-autofix": `sparkles`,
    "list-filter": `filter`,
    loading: `spinner`,
    map: `file-tree`,
    "menu-selection": `check`,
    "menu-submenu": `chevron-right`,
    move: `move`,
    "preserve-case": `case-sensitive`,
    "quick-input-back": `arrow-left`,
    regex: `regex`,
    remove: `minus`,
    replace: `replace`,
    "replace-all": `replace-all`,
    "scrollbar-button-down": `chevron-down`,
    "scrollbar-button-left": `chevron-left`,
    "scrollbar-button-right": `chevron-right`,
    "scrollbar-button-up": `chevron-up`,
    "search-fuzzy": `search`,
    selection: `selection`,
    sparkle: `sparkles`,
    "sparkle-filled": `sparkles`,
    "split-horizontal": `split-columns`,
    "split-vertical": `layout-left`,
    "stop-circle": `stop`,
    "surround-with": `code-object`,
    "symbol-array": `code-array`,
    "symbol-boolean": `code-boolean`,
    "symbol-class": `code-class`,
    "symbol-color": `palette`,
    "symbol-constant": `code-constant`,
    "symbol-constructor": `hammer`,
    "symbol-customcolor": `palette`,
    "symbol-enum": `code-enum`,
    "symbol-enum-member": `code-variable`,
    "symbol-event": `bolt`,
    "symbol-field": `code-variable`,
    "symbol-file": `file`,
    "symbol-folder": `folder`,
    "symbol-function": `code-function`,
    "symbol-interface": `code-interface`,
    "symbol-key": `key`,
    "symbol-keyword": `key`,
    "symbol-method": `code-function`,
    "symbol-module": `box`,
    "symbol-namespace": `code-object`,
    "symbol-null": `code-null`,
    "symbol-number": `code-number`,
    "symbol-object": `code-object`,
    "symbol-operator": `code-operator`,
    "symbol-package": `box`,
    "symbol-property": `sliders-h`,
    "symbol-reference": `link`,
    "symbol-snippet": `file-edit`,
    "symbol-string": `code-string`,
    "symbol-struct": `code-class`,
    "symbol-text": `align-left`,
    "symbol-type-parameter": `code-parameter`,
    "symbol-unit": `arrows-h`,
    "symbol-value": `code-variable`,
    "symbol-variable": `code-variable`,
    sync: `refresh`,
    "toolbar-more": `ellipsis`,
    tools: `wrench`,
    "tree-item-expanded": `chevron-down`,
    "tree-item-loading": `spinner`,
    unfold: `expand-all`,
    warning: `exclamation-triangle`,
    "whole-word": `whole-word`,
    wrench: `wrench`,
} as const satisfies Record<string, IconName>;

const mask = (name: IconName): string =>
    `url("data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">${glyphBody(ICONS[name])}</svg>`)}")`;

/** Installed once with Monaco, before any editor or diff surface mounts. Blank is an intentional spacer. */
export const EDITOR_ICON_CSS = `:root { --intentic-icon-code: ${mask(`code`)}; --intentic-icon-blank: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E"); ${Object.entries(
    EDITOR_ICONS,
)
    .map(([id, name]) => `--intentic-icon-${id}: ${mask(name)};`)
    .join(` `)} }`;
