import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterAll, beforeAll, expect, test } from "vitest";
import { createEngine, type Engine } from "../index.js";
import { makeFixtureWorkspace } from "../testing.js";
import type { QueryRequest } from "../types.js";

// The two orientation verbs — `map` (what matters, structurally) and `hotspots` (what matters, by risk).

let root: string;
let cleanup: () => Promise<void>;
let engine: Engine;

beforeAll(async () => {
    ({ root, cleanup } = await makeFixtureWorkspace());
    engine = createEngine({ root });
});
afterAll(() => cleanup());

const request = (partial: Partial<QueryRequest> & { verb: QueryRequest["verb"]; query: string }): QueryRequest => ({
    scope: {},
    render: { budget: 1500 },
    options: {},
    echo: `${partial.verb} "${partial.query}"`,
    ...partial,
});

test("map: files ranked by import graph, each showing its exported signatures at real lines", async () => {
    const outcome = await engine.run(request({ verb: "map", query: "" }));
    expect(outcome.exitCode).toBe(0);

    // registry.ts and WidgetList.vue both `import … from "./widget.js"` — a specifier naming a file that does
    // not exist, since the real neighbour is widget.ts. Ranking widget.ts above registry.ts (which nothing
    // imports) therefore also proves the TypeScript .js→.ts resolution works.
    const paths = outcome.result.groups.map((group) => group.path);
    expect(paths).toContain("alpha/src/widget.ts");
    expect(paths.indexOf("alpha/src/widget.ts")).toBeLessThan(paths.indexOf("alpha/src/registry.ts"));

    const widget = outcome.result.groups.find((group) => group.path === "alpha/src/widget.ts")!;
    expect(widget.hits.map((hit) => hit.text)).toEqual(expect.arrayContaining([expect.stringContaining("createWidget")]));
    // Every line stays a usable anchor: the signature sits on the line the symbol is actually declared.
    const def = widget.hits.find((hit) => hit.text.includes("createWidget"))!;
    expect(def.line).toBe(6);
});

test("map: a component's script-setup locals never become definitions", async () => {
    const outcome = await engine.run(request({ verb: "map", query: "" }));
    // WidgetList.vue exports nothing — its `widgets`/`labelOf` are locals, so it contributes no map entry.
    expect(outcome.result.groups.map((group) => group.path)).not.toContain("alpha/src/WidgetList.vue");
});

test("map: generated files are excluded — their re-exports are not definitions", async () => {
    await writeFile(
        join(root, "alpha/src/shim.ts"),
        `// Generated by scripts/gen.mjs — do not edit.\nexport const createWidget = 1;\nexport const Widget = 2;\n`,
    );
    const outcome = await engine.run(request({ verb: "map", query: "" }));
    expect(outcome.result.groups.map((group) => group.path)).not.toContain("alpha/src/shim.ts");
    // The real definition site is untouched by the shim's arrival.
    expect(outcome.result.groups.map((group) => group.path)).toContain("alpha/src/widget.ts");
});

test("hotspots: ranks by commits × complexity, and never lists uncommitted or branch-free files", async () => {
    const outcome = await engine.run(request({ verb: "hotspots", query: "" }));
    expect(outcome.exitCode).toBe(0);
    expect(outcome.text).toMatch(/alpha\/src\/\S+\s+1 commit\s+\+\d+ -\d+\s+cx \d+\s+score \d+/);

    const paths = outcome.result.groups.map((group) => group.path);
    // WidgetList.vue is the only fixture file with branch points — and they live in its <script> block, so this
    // also proves .vue complexity is counted rather than skipped for want of a Vue grammar.
    expect(paths).toContain("alpha/src/WidgetList.vue");
    // beta/ has no git repo — no commits, so no churn, so it cannot be a hotspot.
    expect(paths.every((path) => path.startsWith("alpha/"))).toBe(true);
    // registry.ts is committed but branch-free; notes.md is markup, where keyword scans read content, not code.
    expect(paths).not.toContain("alpha/src/registry.ts");
    expect(paths).not.toContain("notes.md");
});

test("hotspots: the path filter narrows, and --since rejects a bad window", async () => {
    const filtered = await engine.run(request({ verb: "hotspots", query: "widgetlist" }));
    expect(filtered.result.groups.map((group) => group.path)).toEqual(["alpha/src/WidgetList.vue"]);

    await expect(engine.run(request({ verb: "hotspots", query: "", options: { since: "yesterday" } }))).rejects.toThrow("--since expects");
});
