import type { IndexDb } from "../store/db.js";
import type { RankedGroup, RankedHit, SymbolRow } from "../types.js";
import { buildImportGraph, fileHeads } from "./import-graph.js";

// `iq map`, the repo as a ranked skeleton: which files matter, and what each one exposes. This is the
// orientation artifact a reader (or a model with a fresh context) wants before touching anything, and the file
// tree is a poor substitute, it sorts alphabetically, which correlates with nothing.
//
// Importance is PageRank over the import graph: an edge A→B means A imports B, so rank flows from importers to
// the modules they depend on, and being imported by a central file counts for more than by a leaf.
//
// Edges are IMPORTS, not symbol-name matches. Name matching was tried first and has a ceiling that no weighting
// fixes: text cannot tell a reference from a coincidence, so a module exporting ordinary words (`App`, `Host`,
// `Repo`) collects mentions from the whole repo and tops the list. An import statement is unambiguous.

const DAMPING = 0.85;
const ITERATIONS = 20;

interface MapSymbol {
    readonly fileId: number;
    readonly path: string;
    readonly name: string;
    readonly kind: SymbolRow["kind"];
    readonly line: number;
    readonly signature: string;
}

// Generated files are not part of the authored surface a map describes, and they distort the ranking: a
// re-export shim duplicates a whole library's vocabulary, so everything appears to depend on it. Both halves of
// the test are conventions, not guesses about one repo, the `@generated` marker and Go's standardized
// `Code generated ... DO NOT EDIT.` banner, plus the `generated/` dir and `*.generated.*` suffix.
const GENERATED_PATH = /(^|\/)generated\/|\.generated\./i;
const GENERATED_BANNER = /@generated\b|\bdo not edit\b|\bauto-?generated\b|\bgenerated by\b/i;
const BANNER_LINES = 5;

const exportedSymbols = (db: IndexDb, allowed: ReadonlySet<string>): MapSymbol[] =>
    db
        .all(
            `SELECT f.id AS file_id, f.path, s.name, s.kind, s.line, s.signature
             FROM symbols s JOIN files f ON f.id = s.file_id
             WHERE s.exported = 1 ORDER BY f.path, s.line`,
        )
        .map((row) => ({
            fileId: Number(row["file_id"]),
            path: row["path"] as string,
            name: row["name"] as string,
            kind: row["kind"] as SymbolRow["kind"],
            line: Number(row["line"]),
            signature: row["signature"] as string,
        }))
        .filter((symbol) => allowed.has(symbol.path));

const pageRank = (nodes: ReadonlySet<number>, edges: ReadonlyMap<number, ReadonlySet<number>>): Map<number, number> => {
    const count = nodes.size;
    let rank = new Map([...nodes].map((node) => [node, 1 / count]));
    for (let iteration = 0; iteration < ITERATIONS; iteration++) {
        const next = new Map([...nodes].map((node) => [node, 0]));
        // Files that import nothing would leak their rank out of the system; spreading it uniformly is the
        // standard fix and keeps the ranks a true distribution.
        let dangling = 0;
        for (const [node, value] of rank) {
            const out = edges.get(node);
            if (out === undefined || out.size === 0) {
                dangling += value;
                continue;
            }
            for (const to of out) {
                next.set(to, (next.get(to) ?? 0) + value / out.size);
            }
        }
        const base = (1 - DAMPING) / count + (DAMPING * dangling) / count;
        rank = new Map([...next].map(([node, value]) => [node, base + DAMPING * value]));
    }
    return rank;
};

export const repoMap = (db: IndexDb, allowed: ReadonlySet<string>): RankedGroup[] => {
    const heads = fileHeads(db);
    // Every indexed file in scope is a graph node, including ones that export nothing, an entry point that only
    // imports still pushes importance into what it uses. Only files with something to show get rendered.
    const graph = buildImportGraph(db, allowed, heads);
    if (graph.pathsById.size === 0) {
        return [];
    }
    const rank = pageRank(new Set(graph.pathsById.keys()), graph.imports);

    const isGenerated = (fileId: number, path: string): boolean =>
        GENERATED_PATH.test(path) || GENERATED_BANNER.test((heads.get(fileId) ?? "").split("\n", BANNER_LINES).join("\n"));

    const byFile = new Map<number, MapSymbol[]>();
    for (const symbol of exportedSymbols(db, allowed)) {
        if (isGenerated(symbol.fileId, symbol.path)) {
            continue;
        }
        const existing = byFile.get(symbol.fileId);
        if (existing === undefined) {
            byFile.set(symbol.fileId, [symbol]);
        } else {
            existing.push(symbol);
        }
    }
    return [...byFile.entries()]
        .map(([fileId, fileSymbols]) => ({ fileSymbols, rank: rank.get(fileId) ?? 0 }))
        .toSorted((a, b) => b.rank - a.rank || (a.fileSymbols[0]!.path < b.fileSymbols[0]!.path ? -1 : 1))
        .map((entry, position) => {
            const score = 1 / (position + 1);
            const hits: RankedHit[] = entry.fileSymbols.map((symbol) => ({
                path: symbol.path,
                line: symbol.line,
                text: symbol.signature,
                tags: [{ kind: "def" as const }],
                score,
            }));
            return { path: entry.fileSymbols[0]!.path, score, hits };
        });
};
