// Build the custom icon pack and the vendor marks into offline Iconify collections.
// Run `pnpm --filter @intentic/ui generate:icons` after changing a drawing or the vocabulary.

import { getIcons } from "@iconify/utils";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { packageRoot } from "@intentic/constants/node";
import { ICONS } from "../src/icons/iconSets.js";
import { ACTION_GLYPHS } from "../src/icons/actionGlyphs.js";
import { NAVIGATION_GLYPHS } from "../src/icons/navigationGlyphs.js";
import { OBJECT_GLYPHS } from "../src/icons/objectGlyphs.js";
import { STATUS_GLYPHS } from "../src/icons/statusGlyphs.js";
import { glyphBody, type Glyph } from "../src/icons/glyph.js";
import type { IconifyIcon, IconifyJSON } from "@iconify/types";

const drawings: Record<string, Glyph> = {};
for (const family of [ACTION_GLYPHS, NAVIGATION_GLYPHS, OBJECT_GLYPHS, STATUS_GLYPHS]) {
    for (const [name, drawing] of Object.entries(family)) {
        if (Object.hasOwn(drawings, name)) {
            throw new Error(`Duplicate custom icon: ${name}`);
        }
        drawings[name] = drawing;
    }
}

const custom: Record<string, IconifyIcon> = {};
const brands = new Set<string>();
for (const id of Object.values(ICONS)) {
    const [prefix, name] = id.split(":");
    if (!name) {
        throw new Error(`Missing icon name: ${id}`);
    }
    if (prefix === `ri`) {
        brands.add(name);
        continue;
    }
    if (prefix !== `intentic` || !Object.hasOwn(drawings, name)) {
        throw new Error(`Missing custom drawing: ${id}`);
    }
    custom[name] = { body: glyphBody(drawings[name]!) };
}
const unused = Object.keys(drawings).filter((name) => !Object.hasOwn(custom, name));
if (unused.length > 0) {
    throw new Error(`Drawings without an icon name: ${unused.join(`, `)}`);
}

const full = (await import("@iconify-json/ri/icons.json", { with: { type: "json" } })).default;
const trimmed = getIcons(full, [...brands]);
if (!trimmed) {
    throw new Error(`No bundled vendor marks found.`);
}
const missing = [...brands].filter((name) => !Object.hasOwn(trimmed.icons, name));
if (missing.length > 0) {
    throw new Error(`Missing vendor marks: ${missing.join(", ")}`);
}
const collections: IconifyJSON[] = [{ prefix: `intentic`, width: 24, height: 24, icons: custom }, trimmed];

const out = `// GENERATED by scripts/generateIconData.ts: do not edit. Run \`pnpm --filter @intentic/ui generate:icons\`.
// Custom drawings and vendor marks, registered via addCollection() in the editor and shared views.
import type { IconifyJSON } from "@iconify/types";

export const BUNDLED_ICONS: IconifyJSON[] = ${JSON.stringify(collections)};
`;

const outPath = join(packageRoot(import.meta.url), "src/icons/iconData.generated.ts");
writeFileSync(outPath, out);
console.log(`Wrote ${outPath}: ${Object.keys(custom).length} custom icons, ${brands.size} vendor marks.`);
