// The kit's export names — the single source consumed by the web app's shim generator
// (_apps/web/scripts/generate-ext-shims.mjs) and hostModules' dev-time coverage assertion. Update alongside
// src/index.ts; the assertion catches drift on the next dev boot.
export const extensionUiNames = [
    "BottomSheet",
    "Button",
    "Card",
    "Checkbox",
    "Code",
    "ContextMenu",
    "CopyButton",
    "DagGraph",
    "Dialog",
    "Icon",
    "InfoHint",
    "InputText",
    "Page",
    "PageHeader",
    "Popover",
    "ProgressRing",
    "RowGroup",
    "Segmented",
    "Select",
    "StatusBadge",
    "StepSection",
    "ToggleSwitch",
    "cmp",
    "formatBytes",
    "timeAgo",
    "useDevice",
    "useTheme",
];
