FROM busybox:1.38.0@sha256:fd7dc98638c8e305f4dc34e979f1c0fdfdcaeb0fbf8fcff77ae834b6da3d7e6e
RUN mkdir -p /www && printf '%s' '<%= it.appBody %>' > /www/index.html
ENV PORT=8080
EXPOSE 8080
CMD ["sh","-c","httpd -f -v -p ${PORT} -h /www"]
