import type { StateFile } from "./state-portability.js";

/* WHAT LIVES ON /history — the second half of the daemon's state, and the half nothing declared until an
 * export had to reason about it.
 *
 * `WORKSPACE_STATE_FILES` covers `<workspace>/.intentic/`, which is where the manifests live. It is not where
 * the machinery lives. Every repo's REAL git dir is here (a repo's in-tree `.git` is a pointer file — see
 * git/repo-git-dirs.ts for the invariant that forces it), and so are the fleet registry, the turn journal, the
 * ledgers, the checkpoint scopes and the isolated agents' checkouts. A "workspace export" that took `/work`
 * alone would carry a tree of repos with dangling gitdir pointers — every git command in the restored sandbox
 * answering `fatal: not a git repository` — and an empty agent board.
 *
 * The two tables stay separate rather than becoming one keyed by volume, because they answer different
 * questions. A `.intentic` entry also declares which browser QUERY it makes stale, since the file watcher
 * reports it; nothing here is watched at all (that is the point of the volume), so an `invalidates` field on
 * these entries would be a column of empty arrays. What they share is the portability class, and that is
 * imported rather than duplicated.
 *
 * `history-state.test.ts` fails when a daemon store builds a `/history` path this list doesn't carry, in both
 * directions — the same shape-recognizing guard that covers the workspace table.
 */

// Paths are historyRoot-relative, forward-slash, matched by PREFIX; a directory entry keeps its trailing slash
// so it cannot prefix-match a sibling file. See stateFileFor for how nesting resolves.
export const HISTORY_STATE_FILES: readonly StateFile[] = [
    /* ---- the machinery a restored workspace is inert without ---- */

    /* THE ONE THAT MAKES A BUNDLE A WORKSPACE. Every repo's real git dir, including the /work root's own
     * ("root"), keyed by URI-encoded repo id. Carrying the working tree without this hands the target files
     * whose `.git` points at a path that does not exist there — which is not a degraded repo but a broken one,
     * and it takes the Changes review, the diff, land and every agent branch with it. The agent BRANCHES live
     * in here too, which is what lets the checkouts below be left out. */
    { path: "gits/", portability: "carry" },
    // The checkpoint timeline (one bare repo per scope, snapshots on refs/snapshots/head). Restoring it is what
    // makes "restore to before that turn" still reach back past the move.
    { path: "scopes/", portability: "carry" },
    // The fleet: every conversation card, its branch, its session ids, its standing.
    { path: "agents.json", portability: "carry" },
    { path: "turns/", portability: "carry" },
    { path: "transcripts/", portability: "carry" },
    // Which checkpoint each message can be rewound to. Carried WITH the transcripts and the scopes above,
    // because it is the join between them: without it a restored conversation reads back whole and offers no
    // way back into it, even though both the messages and the checkpoints travelled.
    { path: "rewind-points.json", portability: "carry" },
    { path: "activity.jsonl", portability: "carry" },
    { path: "usage.jsonl", portability: "carry" },
    { path: "account-usage.json", portability: "carry" },
    { path: "provider-refusals.json", portability: "carry" },
    // The deploy engine's own ledgers — a run's events and the check results the Pipelines view reads back.
    { path: "apply-events.ndjson", portability: "carry" },
    { path: "check-events/", portability: "carry" },

    /* ---- regenerated by the target ---- */

    /* THE DELIBERATE OMISSION, and the difference between a bundle of gigabytes and one of hundreds.
     *
     * A conversation's worktree is a full checkout of the monorepo per agent (plus its overlay upper dir), and
     * there can be a hundred of them. None of it is unique: the branch it holds is in `gits/` above, and the
     * registry entry naming it travels in agents.json — so an imported conversation arrives in exactly the
     * shape the system already has a name for. `attached()` reports its checkout as absent, the board renders
     * it, and the next turn's `ensure()` re-creates it from the recorded composition, which is the same path an
     * archived agent takes when it runs again. The boot sweep's `git worktree prune` clears the stale admin
     * entries the restored git dirs still carry. */
    {
        path: "worktrees/",
        portability: "derived",
        note: "Each conversation re-attaches its checkout from its branch on its next turn.",
    },
    { path: "overlays/", portability: "derived" },
    { path: "logs/", portability: "derived" },
    { path: "trash/", portability: "derived" },
    { path: ".isolation-probe", portability: "derived" },
    /* The finished bundles themselves. `derived` is doing real work here rather than describing leftovers: an
     * export that carried the export directory would pack every previous bundle into the new one, and the next
     * export would pack THAT — each one a multiple of the last. Living on this volume is the other half of the
     * same guard; under `/work` the file would also be watched, indexed by iq, and snapshotted into history. */
    { path: "exports/", portability: "derived" },

    /* ---- credentials ---- */

    // The ssh alias dir ~/.ssh/intentic-hosts symlinks to: per-host config, private keys and passphrases for
    // every host capability and git remote the sandbox reaches.
    {
        path: "ssh-hosts/",
        portability: "secret",
        note: "Re-add each ssh host on the Capabilities view — its key does not travel.",
    },
    // The cli-proxy's config, which holds the routed subscriptions' provider tokens.
    {
        path: "translator/",
        portability: "secret",
        note: "Sign the routed AI subscriptions in again on the Agent tab.",
    },

    /* ---- identity: what binds this sandbox to its owner, its browsers and its host ---- */

    /* Signs every browser session cookie. Carrying it would let a bundle's holder mint sessions against the
     * target — an export becomes a credential — and the target minting its own costs exactly one sign-in. */
    { path: "session-secret", portability: "identity", note: "Sign in again — the target signs its own sessions." },
    {
        path: "push.json",
        portability: "identity",
        note: "Re-enable notifications in the browsers you use — a push subscription is bound to the sandbox that minted it.",
    },
    { path: "sync-enrollments.json", portability: "identity", note: "Re-pair desktop sync from the Sync tab." },
    { path: "sync-pair-consumed.json", portability: "identity" },
    { path: "host-enrollments.json", portability: "identity" },
    { path: "local-cert/", portability: "identity" },
];
