[test]
preload = ["../../_tools/testing/src/dom.ts", "../../_tools/testing/src/bun-preload.ts", "../../_tools/testing/src/bun-vue.ts", "../web/bun.setup.ts", "./bun.setup.ts"]
pathIgnorePatterns = ["**/dist/**", "**/deploy/**", "**/.cache/**", "**/.turbo/**", "**/out-tsc/**"]
