import { ATTACHMENTS_DIR, CONTROL_SCOPES, type ContractRoute, RAW_ROUTE_LIST, SANDBOX_ROUTES, sandboxRouteFor } from "@intentic/sandbox-contract";
import { unstubbed } from "@intentic/testing";
import type { ControlTokens } from "./control-tokens.js";
import { controlScoped } from "./control-tokens.js";
import { grantsOf } from "./grants.js";
import { guestReach, routeFloor } from "./role-floor.js";

// Every route the daemon serves, and what each gate in front of it decides, recorded from the path tables this
// replaced (app.ts, role-floor.ts, grants.ts, control-tokens.ts) when that policy moved into route meta. A row that
// changes is a route that became more or less reachable: change one on purpose, never to make this pass.

// One row per route, keyed `METHOD /template`: door|bearer (does the session middleware let it through untouched),
// early|waits (does it answer before boot), stream|timed, its member floor, then guest, embedded, enrolment and every
// machine credential that reaches it: panel, agent, sync (sync-pipe: no heartbeat), and the control rungs editor, read,
// drive, land. An extension token reaches what its manifest declares, never what a route does, so it has no column.
const RECORDED: Readonly<Record<string, string>> = {
    "GET /accounts/{provider}": "bearer waits timed viewer panel read drive land",
    "POST /accounts/{provider}/disconnect": "bearer waits timed maintainer panel",
    "POST /accounts/{provider}/login/cancel": "bearer waits timed maintainer panel",
    "POST /accounts/{provider}/login/complete": "bearer waits timed maintainer panel",
    "POST /accounts/{provider}/login/start": "bearer waits timed maintainer panel",
    "POST /accounts/{provider}/rename": "bearer waits timed maintainer panel",
    "GET /activity": "bearer waits timed viewer panel read drive land",
    "GET /activity/status": "bearer waits timed viewer panel read drive land",
    "POST /agent": "bearer waits timed collaborator guest panel editor drive land",
    "POST /agent/attach": "bearer waits stream viewer guest panel read drive land",
    "GET /agent/commands": "bearer waits timed viewer guest panel read drive land",
    "POST /agent/queue/edit": "bearer waits timed collaborator guest panel drive land",
    "POST /agent/queue/remove": "bearer waits timed collaborator guest panel drive land",
    "POST /agent/queue/resume": "bearer waits timed collaborator guest panel drive land",
    "GET /agent/refusals": "bearer waits timed viewer guest panel read drive land",
    "POST /agent/reply": "bearer waits timed collaborator guest panel editor drive land",
    "POST /agent/resume": "bearer waits timed collaborator guest panel drive land",
    "POST /agent/rewind": "bearer waits timed collaborator guest panel drive land",
    "POST /agent/route-chat": "bearer waits timed collaborator panel drive land",
    "POST /agent/steer": "bearer waits timed collaborator guest panel drive land",
    "POST /agent/stop": "bearer waits timed collaborator guest panel drive land",
    "GET /agents": "bearer waits timed viewer guest panel read drive land",
    "GET /agents/{id}": "bearer waits timed viewer guest panel read drive land",
    "GET /agents/{id}/{repo}/file-diff": "bearer waits timed viewer panel read drive land",
    "POST /agents/{id}/assign": "bearer waits timed collaborator panel drive land",
    "POST /agents/{id}/auto-land": "bearer waits timed maintainer panel",
    "POST /agents/{id}/break-policy": "bearer waits timed collaborator panel drive land",
    "GET /agents/{id}/conflicts": "bearer waits timed viewer panel read drive land",
    "GET /agents/{id}/diff": "bearer waits timed viewer panel read drive land",
    "POST /agents/{id}/discard": "bearer waits timed maintainer panel land",
    "GET /agents/{id}/history": "bearer waits timed viewer panel read drive land",
    "POST /agents/{id}/keep-warm": "bearer waits timed collaborator panel drive land",
    "POST /agents/{id}/land": "bearer waits timed maintainer panel land",
    "POST /agents/{id}/place": "bearer waits timed maintainer panel",
    "POST /agents/{id}/react": "bearer waits timed viewer guest panel drive land",
    "POST /agents/{id}/rename": "bearer waits timed collaborator guest panel drive land",
    "POST /agents/{id}/request-land": "bearer waits timed collaborator panel drive land",
    "POST /agents/{id}/scratch/delete": "bearer waits timed maintainer panel",
    "POST /agents/{id}/scratch/include": "bearer waits timed maintainer panel",
    "POST /agents/{id}/seen": "bearer waits timed collaborator guest panel drive land",
    "POST /agents/{id}/stop-job": "bearer waits timed maintainer panel",
    "POST /agents/{id}/stop-watching": "bearer waits timed maintainer panel",
    "GET /agents/{id}/system-prompt": "bearer waits timed viewer panel read drive land",
    "GET /agents/{id}/transcript": "bearer waits timed viewer guest panel read drive land",
    "GET /agents/{id}/transcript/tools/{toolId}": "bearer waits timed viewer panel read drive land",
    "POST /agents/archive": "bearer waits timed collaborator guest panel drive land",
    "GET /agents/archived": "bearer waits timed viewer guest panel read drive land",
    "POST /agents/purge": "bearer waits timed maintainer panel land",
    "GET /agents/search": "bearer waits timed viewer panel read drive land",
    "POST /agents/seen": "bearer waits timed collaborator guest panel drive land",
    "POST /agents/unarchive": "bearer waits timed collaborator guest panel drive land",
    "GET /approvals": "bearer waits timed viewer panel read drive land",
    "POST /approvals": "bearer waits timed maintainer panel",
    "GET /approvals/hooks": "bearer waits timed maintainer panel",
    "POST /approvals/hooks/{digest}/approve": "bearer waits timed maintainer",
    "POST /approvals/hooks/{digest}/dismiss": "bearer waits timed maintainer",
    "DELETE /approvals/{id}": "bearer waits timed maintainer panel",
    "GET /areas": "bearer waits timed viewer guest panel read drive land",
    "POST /areas": "bearer waits timed maintainer panel",
    "DELETE /areas/{id}": "bearer waits timed maintainer panel",
    "DELETE /arrivals": "bearer waits timed maintainer panel",
    "POST /arrivals/apply": "bearer waits timed maintainer panel",
    "GET /arrivals/hosts": "bearer waits timed viewer panel read drive land",
    "POST /arrivals/plan": "bearer waits timed maintainer panel",
    "POST /arrivals/scan": "bearer waits timed maintainer panel",
    "GET /automations": "bearer waits timed viewer panel read drive land",
    "POST /automations": "bearer waits timed maintainer panel",
    "DELETE /automations/{id}": "bearer waits timed maintainer panel",
    "POST /automations/{id}/enabled": "bearer waits timed maintainer panel",
    "POST /automations/{id}/fire": "door waits timed maintainer panel",
    "POST /automations/{id}/rotate-token": "bearer waits timed maintainer panel",
    "POST /automations/{id}/run": "bearer waits timed maintainer panel",
    "GET /automations/catalog": "bearer waits timed viewer panel read drive land",
    "GET /automations/pending": "bearer waits timed viewer panel read drive land",
    "POST /automations/pending/{id}/approve": "bearer waits timed maintainer panel",
    "POST /automations/pending/{id}/reject": "bearer waits timed maintainer panel",
    "GET /automations/senders/{provider}": "bearer waits timed viewer panel read drive land",
    "DELETE /bundles": "bearer waits timed maintainer panel",
    "GET /bundles": "bearer waits timed viewer panel",
    "POST /bundles": "bearer waits timed maintainer panel",
    "GET /bundles/download": "door waits timed viewer panel",
    "POST /bundles/ticket": "bearer waits timed maintainer panel",
    "GET /capabilities": "bearer waits timed maintainer panel",
    "POST /capabilities": "bearer waits timed maintainer panel",
    "DELETE /capabilities/{id}": "bearer waits timed maintainer panel",
    "GET /capabilities/{id}/connection": "bearer waits timed maintainer",
    "POST /capabilities/{id}/login": "bearer waits timed maintainer panel",
    "GET /capabilities/{id}/otp": "bearer waits timed maintainer panel agent",
    "POST /capabilities/{id}/rename": "bearer waits timed maintainer panel",
    "POST /capabilities/{id}/secret": "bearer waits timed maintainer panel",
    "GET /capabilities/{id}/status": "bearer waits timed maintainer panel",
    "POST /capabilities/ask": "bearer waits timed maintainer panel agent",
    "GET /capabilities/connectable": "bearer waits timed maintainer panel agent",
    "POST /capabilities/marketplace": "bearer waits timed maintainer panel",
    "POST /capabilities/probe": "bearer waits timed maintainer",
    "DELETE /capabilities/recommendations/{entry}": "bearer waits timed maintainer panel",
    "POST /capabilities/refs": "bearer waits timed maintainer panel",
    "GET /children": "bearer waits timed viewer panel agent",
    "POST /children/answer": "bearer waits timed maintainer panel agent",
    "GET /children/providers": "bearer waits timed viewer panel agent",
    "POST /children/send": "bearer waits timed maintainer panel agent",
    "POST /children/spawn": "bearer waits timed maintainer panel agent",
    "POST /children/wait": "bearer waits timed maintainer panel agent",
    "GET /chores": "bearer waits timed viewer panel read drive land",
    "POST /chores/ledger": "bearer waits timed maintainer panel",
    "POST /chores/probe": "bearer waits timed maintainer panel",
    "POST /ci/fix": "bearer waits timed maintainer panel",
    "GET /ci/runs": "bearer waits timed viewer panel read drive land",
    "POST /ci/runs/cancel": "bearer waits timed maintainer panel",
    "POST /ci/runs/jobs": "bearer waits timed maintainer panel",
    "POST /ci/runs/rerun": "bearer waits timed maintainer panel",
    "POST /ci/webhook/{host}": "door waits timed maintainer panel",
    "GET /definition": "bearer waits timed viewer panel read drive land",
    "POST /definition/diff": "bearer waits timed maintainer panel",
    "GET /definition/workspace": "bearer waits timed viewer panel read drive land",
    "POST /definition/workspace/publish": "bearer waits timed maintainer panel",
    "GET /diff/derived": "bearer waits timed viewer panel read drive land",
    "GET /diff/raw": "bearer waits timed viewer panel read drive land",
    "GET /endpoints/{id}/models": "bearer waits timed viewer panel read drive land",
    "GET /endpoints/local-model/fit": "bearer waits timed viewer panel read drive land",
    "POST /endpoints/local-model/prefetch": "bearer waits timed maintainer panel",
    "GET /endpoints/trial/status": "bearer waits timed viewer panel read drive land",
    "GET /engines": "bearer waits timed viewer panel read drive land",
    "POST /engines/channel": "bearer waits timed maintainer panel",
    "POST /engines/revert": "bearer waits timed maintainer panel",
    "POST /engines/update": "bearer waits timed maintainer panel",
    "POST /enroll": "door waits timed maintainer panel",
    "GET /environment": "bearer waits timed viewer panel read drive land",
    "POST /environment/approve": "bearer waits timed maintainer panel",
    "GET /environment/contents": "bearer waits timed viewer panel read drive land",
    "POST /environment/reject": "bearer waits timed maintainer panel",
    "POST /environment/runtime-install": "bearer waits timed maintainer panel",
    "GET /events": "bearer early stream viewer guest panel read drive land",
    "GET /exit": "bearer waits timed viewer panel agent",
    "POST /exit/{id}/check": "bearer waits timed maintainer panel agent",
    "GET /exit/{id}/countries": "bearer waits timed viewer panel agent",
    "POST /exit/{id}/rotate": "bearer waits timed maintainer panel agent",
    "POST /exit/{id}/start": "bearer waits timed maintainer panel agent",
    "POST /exit/{id}/stop": "bearer waits timed maintainer panel agent",
    "POST /exit/{id}/use": "bearer waits timed maintainer panel agent",
    "GET /extensions": "bearer waits timed viewer panel read drive land",
    "GET /extensions/{id}/bundle": "bearer waits timed viewer panel read drive land",
    "POST /extensions/{id}/enabled": "bearer waits timed maintainer panel",
    "GET /extensions/{id}/processes/{name}": "bearer waits timed viewer panel read drive land",
    "POST /extensions/{id}/processes/{name}/start": "bearer waits timed maintainer panel",
    "POST /extensions/{id}/processes/{name}/stop": "bearer waits timed maintainer panel",
    "GET /extensions/{id}/readiness": "bearer waits timed viewer panel read drive land",
    "GET /extensions/{id}/removal": "bearer waits timed viewer panel read drive land",
    "POST /extensions/{id}/remove": "bearer waits timed maintainer panel",
    "POST /extensions/{id}/revert": "bearer waits timed maintainer panel",
    "GET /extensions/{id}/settings": "bearer waits timed viewer panel read drive land",
    "POST /extensions/{id}/settings": "bearer waits timed maintainer panel",
    "POST /extensions/{id}/update": "bearer waits timed maintainer panel",
    "POST /extensions/{id}/update-policy": "bearer waits timed maintainer panel",
    "POST /extensions/{id}/update/preview": "bearer waits timed maintainer panel",
    "POST /extensions/updates/check": "bearer waits timed maintainer panel",
    "POST /extensions/usage": "bearer waits timed maintainer panel",
    "POST /extensions/workspace": "bearer waits timed maintainer panel",
    "POST /extensions/{id}/approve": "bearer waits timed maintainer",
    "GET /fleet": "bearer waits timed viewer panel agent read drive land",
    "GET /fleet/{handle}": "bearer waits timed viewer panel agent read drive land",
    "POST /fleet/message": "bearer waits timed maintainer panel agent",
    "POST /git/{repo}/abort": "bearer waits timed maintainer panel",
    "POST /git/{repo}/branch": "bearer waits timed maintainer panel",
    "GET /git/{repo}/branches": "bearer waits timed viewer panel read drive land",
    "POST /git/{repo}/branches": "bearer waits timed maintainer panel",
    "POST /git/{repo}/branches/delete": "bearer waits timed maintainer panel",
    "POST /git/{repo}/checkout": "bearer waits timed maintainer panel",
    "POST /git/{repo}/cherry-pick": "bearer waits timed maintainer panel",
    "POST /git/{repo}/commit": "bearer waits timed maintainer panel",
    "GET /git/{repo}/commit-diff": "bearer waits timed viewer panel read drive land",
    "GET /git/{repo}/commit-file-diff": "bearer waits timed viewer panel read drive land",
    "POST /git/{repo}/discard": "bearer waits timed maintainer panel",
    "POST /git/{repo}/drop": "bearer waits timed maintainer panel",
    "POST /git/{repo}/fetch": "bearer waits timed maintainer panel",
    "GET /git/{repo}/file": "bearer waits timed viewer panel read drive land",
    "PUT /git/{repo}/file": "bearer waits timed maintainer panel",
    "GET /git/{repo}/file-diff": "bearer waits timed viewer panel read drive land",
    "GET /git/{repo}/files": "bearer waits timed viewer panel read drive land",
    "GET /git/{repo}/log": "bearer waits timed viewer panel read drive land",
    "POST /git/{repo}/merge": "bearer waits timed maintainer panel",
    "GET /git/{repo}/operation": "bearer waits timed viewer panel read drive land",
    "POST /git/{repo}/publish-file": "bearer waits timed maintainer panel",
    "POST /git/{repo}/pull": "bearer waits timed maintainer panel",
    "GET /git/{repo}/push": "bearer waits timed viewer panel read drive land",
    "POST /git/{repo}/push": "bearer waits timed maintainer panel",
    "POST /git/{repo}/push/cancel": "bearer waits timed maintainer panel",
    "POST /git/{repo}/rebase": "bearer waits timed maintainer panel",
    "GET /git/{repo}/remote": "bearer waits timed viewer panel read drive land",
    "POST /git/{repo}/reset": "bearer waits timed maintainer panel",
    "POST /git/{repo}/revert": "bearer waits timed maintainer panel",
    "POST /git/{repo}/stage": "bearer waits timed maintainer panel",
    "POST /git/{repo}/stash": "bearer waits timed maintainer panel",
    "GET /git/{repo}/stash-diff": "bearer waits timed viewer panel read drive land",
    "POST /git/{repo}/stash/apply": "bearer waits timed maintainer panel",
    "POST /git/{repo}/stash/drop": "bearer waits timed maintainer panel",
    "GET /git/{repo}/stashes": "bearer waits timed viewer panel read drive land",
    "GET /git/{repo}/status": "bearer waits timed viewer panel read drive land",
    "POST /git/{repo}/tag": "bearer waits timed maintainer panel",
    "POST /git/{repo}/tag/delete": "bearer waits timed maintainer panel",
    "POST /git/{repo}/tag/push": "bearer waits timed maintainer panel",
    "GET /git/{repo}/undo": "bearer waits timed viewer panel read drive land",
    "POST /git/{repo}/undo": "bearer waits timed maintainer panel",
    "POST /git/{repo}/unstage": "bearer waits timed maintainer panel",
    "GET /git/changes": "bearer waits timed viewer panel read drive land",
    "GET /git/remote-repos": "bearer waits timed viewer panel read drive land",
    "GET /git/repos": "bearer waits timed viewer panel read drive land",
    "GET /health": "door early timed viewer panel read drive land",
    "GET /history/diff": "bearer waits timed viewer panel read drive land",
    "GET /history/file-diff": "bearer waits timed viewer panel read drive land",
    "POST /history/restore": "bearer waits timed maintainer panel",
    "GET /history/snapshots": "bearer waits timed viewer panel read drive land",
    "GET /info": "bearer waits timed viewer guest panel read drive land",
    "GET /intake/{id}/challenge": "door waits timed viewer embedded panel read drive land",
    "GET /intake/{id}/config": "door waits timed viewer embedded panel read drive land",
    "POST /intake/{id}/report": "door waits timed maintainer embedded panel",
    "GET /intake/sdk.js": "door waits timed viewer embedded panel read drive land",
    "POST /intentic": "bearer waits timed maintainer panel",
    "POST /intentic/apply": "bearer waits timed maintainer panel",
    "GET /intentic/apply/events": "bearer waits stream viewer panel read drive land",
    "GET /inventory": "bearer waits timed viewer panel read drive land",
    "POST /inventory": "bearer waits timed maintainer panel",
    "DELETE /inventory/{name}": "bearer waits timed maintainer panel",
    "GET /issues": "bearer waits timed viewer panel read drive land",
    "DELETE /issues/{id}": "bearer waits timed maintainer panel",
    "POST /issues/{id}/investigate": "bearer waits timed maintainer panel",
    "POST /issues/{id}/status": "bearer waits timed maintainer panel",
    "GET /issues/installs/{automationId}": "bearer waits timed viewer panel read drive land",
    "POST /listeners/{provider}/dispatch": "bearer waits timed maintainer panel",
    "POST /listeners/{provider}/failure": "bearer waits timed maintainer panel",
    "GET /listeners/{provider}/state": "bearer waits timed viewer panel read drive land",
    "POST /listeners/{provider}/status": "bearer waits timed maintainer panel",
    "GET /logs": "bearer waits timed maintainer panel",
    "POST /logs/client": "bearer waits timed viewer panel",
    "GET /logs/file": "bearer waits timed maintainer panel",
    "GET /loops": "bearer waits timed viewer panel read drive land",
    "POST /loops": "bearer waits timed maintainer panel",
    "POST /loops/{conversationId}/stop": "bearer waits timed maintainer panel",
    "GET /loops/designs": "bearer waits timed viewer panel read drive land",
    "POST /loops/designs": "bearer waits timed maintainer panel",
    "DELETE /loops/designs/{id}": "bearer waits timed maintainer panel",
    "DELETE /mcp/hosts/{id}": "door waits timed maintainer panel",
    "GET /mcp/hosts/{id}": "door waits timed viewer panel read drive land",
    "POST /mcp/hosts/{id}": "door waits timed maintainer panel",
    "DELETE /mcp/webext/{id}": "door waits timed maintainer panel",
    "GET /mcp/webext/{id}": "door waits timed viewer panel read drive land",
    "POST /mcp/webext/{id}": "door waits timed maintainer panel",
    "DELETE /members": "bearer waits timed maintainer panel",
    "GET /members": "bearer waits timed viewer panel",
    "POST /members": "bearer waits timed maintainer panel",
    "DELETE /members/self": "bearer waits timed viewer guest panel",
    "GET /netdisk": "bearer waits timed viewer panel agent read drive land",
    "POST /netdisk/{id}/mount": "bearer waits timed maintainer panel agent",
    "POST /netdisk/{id}/unmount": "bearer waits timed maintainer panel agent",
    "GET /panels": "bearer waits timed viewer panel read drive land",
    "POST /panels/{repo}/start": "bearer waits timed maintainer panel",
    "POST /panels/{repo}/stop": "bearer waits timed maintainer panel",
    "GET /personas": "bearer waits timed viewer guest panel read drive land",
    "POST /personas": "bearer waits timed maintainer panel",
    "DELETE /personas/{id}": "bearer waits timed maintainer panel",
    "GET /personas/{id}/kit": "bearer waits timed viewer panel read drive land",
    "POST /personas/{id}/prompt": "bearer waits timed maintainer panel",
    "POST /personas/{id}/skills": "bearer waits timed maintainer panel",
    "GET /personas/{id}/skills/read": "bearer waits timed viewer panel read drive land",
    "POST /personas/{id}/skills/remove": "bearer waits timed maintainer panel",
    "GET /ports": "bearer waits timed viewer panel sync read drive land",
    "POST /ports/forward": "bearer waits timed maintainer panel",
    "POST /ports/unforward": "bearer waits timed maintainer panel",
    "GET /providers": "bearer waits timed viewer guest panel read drive land",
    "GET /providers/{provider}/models": "bearer waits timed viewer guest panel read drive land",
    "GET /public": "bearer waits timed viewer panel read drive land",
    "POST /public/publish": "bearer waits timed maintainer panel",
    "POST /public/unpublish": "bearer waits timed maintainer panel",
    "GET /push/config": "bearer waits timed viewer panel",
    "POST /push/subscribe": "bearer waits timed collaborator panel",
    "POST /push/test": "bearer waits timed collaborator panel",
    "POST /push/unsubscribe": "bearer waits timed collaborator panel",
    "GET /safety/log": "bearer waits timed viewer panel read drive land",
    "GET /safety/policy": "bearer waits timed viewer panel read drive land",
    "POST /safety/policy": "bearer waits timed maintainer panel",
    "GET /sandboxes": "bearer waits timed viewer panel agent read drive land",
    "POST /sandboxes": "bearer waits timed maintainer panel agent",
    "GET /secrets": "bearer waits timed maintainer panel",
    "POST /secrets": "bearer waits timed maintainer panel",
    "DELETE /secrets/{key}": "bearer waits timed maintainer panel",
    "GET /secrets/gates": "bearer waits timed maintainer panel agent",
    "DELETE /secrets/gates/{subject}": "bearer waits timed maintainer panel",
    "PUT /secrets/gates/{subject}": "bearer waits timed maintainer panel",
    "GET /secrets/inventory": "bearer waits timed maintainer panel",
    "POST /secrets/request": "bearer waits timed maintainer panel agent",
    "POST /secrets/reveal": "bearer waits timed maintainer panel",
    "GET /sessions": "bearer waits timed viewer panel editor read drive land",
    "GET /sessions/{id}": "bearer waits timed viewer panel editor read drive land",
    "GET /settings": "bearer waits timed viewer guest panel read drive land",
    "POST /settings": "bearer waits timed maintainer panel",
    "GET /settings/field-notes": "bearer waits timed viewer panel read drive land",
    "GET /settings/repo-checks": "bearer waits timed viewer panel read drive land",
    "POST /settings/repo-checks/adopt": "bearer waits timed maintainer panel",
    "GET /settings/rule-firings": "bearer waits timed viewer panel read drive land",
    "GET /settings/savings": "bearer waits timed viewer panel read drive land",
    "GET /settings/system-prompt/{base}": "bearer waits timed viewer panel read drive land",
    "POST /settings/timezone": "bearer waits timed maintainer panel",
    "GET /share": "bearer waits timed viewer panel read drive land",
    "POST /share": "bearer waits timed maintainer panel",
    "POST /share/remove": "bearer waits timed maintainer panel",
    "POST /share/update": "bearer waits timed maintainer panel",
    "GET /skills": "bearer waits timed viewer panel read drive land",
    "POST /skills": "bearer waits timed maintainer panel",
    "GET /skills/read": "bearer waits timed viewer panel read drive land",
    "POST /skills/remove": "bearer waits timed maintainer panel",
    "POST /skills/switch": "bearer waits timed maintainer panel",
    "GET /speech/status": "bearer waits timed viewer guest panel read drive land",
    "POST /speech/transcribe": "bearer waits timed collaborator guest panel drive land",
    "POST /system/access/disable": "door waits timed maintainer panel",
    "DELETE /system/authorized-key": "door waits timed maintainer panel",
    "POST /system/authorized-key": "door waits timed maintainer panel",
    "DELETE /system/authorized-key/{machine}": "bearer waits timed maintainer panel",
    "GET /system/browser-profile": "door early timed viewer panel",
    "GET /system/browser-view": "door early timed viewer panel",
    "POST /system/browser/prepare": "door waits timed maintainer panel",
    "GET /system/browsers": "bearer waits timed viewer panel",
    "DELETE /system/browsers/{name}": "bearer waits timed maintainer panel",
    "GET /system/control/tokens": "bearer waits timed viewer panel",
    "POST /system/control/tokens": "bearer waits timed maintainer panel",
    "DELETE /system/control/tokens/{id}": "bearer waits timed maintainer panel",
    "GET /system/devices": "bearer waits timed viewer panel",
    "POST /system/devices/{id}/agent/{op}": "bearer waits timed maintainer panel",
    "POST /system/devices/{id}/commands/{command}": "bearer waits timed maintainer panel",
    "POST /system/devices/{id}/sandboxes/{slug}": "bearer waits timed maintainer panel",
    "GET /system/hosts": "bearer waits timed viewer panel",
    "DELETE /system/hosts/{id}": "bearer waits timed maintainer panel",
    "GET /system/hosts/connect": "door early timed viewer panel",
    "POST /system/hosts/enroll": "door waits timed maintainer panel",
    "POST /system/hosts/pair": "bearer waits timed maintainer panel",
    "GET /system/manifest-problems": "bearer waits timed viewer panel",
    "POST /system/manifest-problems/repair": "bearer waits timed maintainer panel",
    "GET /system/metrics": "bearer waits timed viewer panel",
    "GET /system/passkeys": "bearer waits timed viewer guest panel",
    "DELETE /system/passkeys/{id}": "bearer waits timed viewer guest panel",
    "POST /system/passkeys/assert": "door early timed maintainer panel",
    "POST /system/passkeys/assert/options": "door early timed maintainer panel",
    "POST /system/passkeys/policy": "bearer waits timed maintainer panel",
    "POST /system/passkeys/recovery": "bearer waits timed maintainer panel",
    "POST /system/passkeys/register": "bearer waits timed viewer guest enrolment panel",
    "POST /system/passkeys/register/options": "bearer waits timed viewer guest enrolment panel",
    "POST /system/presence": "bearer early timed viewer guest panel",
    "GET /system/runners": "bearer waits timed viewer panel",
    "DELETE /system/runners/{id}": "bearer waits timed maintainer panel",
    "POST /system/runners/{id}/definition/sync": "bearer waits timed maintainer panel",
    "GET /system/runners/connect": "door early timed viewer panel",
    "POST /system/runners/credentials": "door waits timed maintainer panel",
    "POST /system/runners/credentials/refresh": "door waits timed maintainer panel",
    "POST /system/runners/enroll": "door waits timed maintainer panel",
    "POST /system/runners/git/{repo}/git-receive-pack": "door waits timed maintainer panel",
    "POST /system/runners/git/{repo}/git-upload-pack": "door waits timed maintainer panel",
    "GET /system/runners/git/{repo}/info/refs": "door waits timed viewer panel",
    "POST /system/runners/pair": "bearer waits timed maintainer panel",
    "ALL /system/runners/translator/*": "door waits timed maintainer panel",
    "POST /system/session": "bearer early timed viewer guest panel",
    "POST /system/session/recover": "door early timed maintainer panel",
    "POST /system/sessions/revoke": "bearer waits timed maintainer panel",
    "GET /system/storage": "bearer waits timed maintainer panel",
    "POST /system/storage/clean": "bearer waits timed maintainer panel",
    "DELETE /system/storage/scan": "bearer waits timed maintainer panel",
    "POST /system/storage/scan": "bearer waits timed maintainer panel",
    "GET /system/subagents": "bearer waits timed viewer panel",
    "GET /system/subagents/{id}/transcript": "bearer waits timed viewer panel",
    "GET /system/sync": "bearer waits timed viewer panel",
    "POST /system/sync/pair": "bearer waits timed collaborator panel",
    "POST /system/sync/report": "bearer waits timed maintainer panel sync",
    "GET /system/sync/ssh": "bearer waits timed viewer panel sync-pipe",
    "GET /system/terminal": "door early timed viewer panel",
    "GET /system/terminals": "bearer early timed viewer panel",
    "DELETE /system/terminals/{name}": "bearer waits timed maintainer panel",
    "GET /system/terminals/{name}/scrollback": "bearer waits timed viewer panel",
    "GET /system/usage": "bearer waits timed maintainer panel",
    "GET /system/webext": "bearer waits timed viewer panel",
    "DELETE /system/webext/{id}": "bearer waits timed maintainer panel",
    "GET /system/webext/connect": "door early timed viewer panel",
    "POST /system/webext/enroll": "door waits timed maintainer panel",
    "POST /system/webext/lend": "door waits timed maintainer panel",
    "POST /system/webext/pair": "bearer waits timed maintainer panel",
    "POST /system/webext/session": "door waits timed maintainer panel",
    "POST /system/ws-ticket": "bearer early timed collaborator panel",
    "POST /translator/{provider}/complete": "bearer waits timed maintainer panel",
    "GET /translator/{provider}/connect": "bearer waits timed viewer panel read drive land",
    "POST /translator/{provider}/connect": "bearer waits timed maintainer panel",
    "POST /translator/{provider}/disconnect": "bearer waits timed maintainer panel",
    "GET /translator/accounts": "bearer waits timed viewer panel read drive land",
    "GET /usage/limit-reset/{account}": "bearer waits timed viewer panel read drive land",
    "POST /usage/limit-reset/{account}/claim": "bearer waits timed maintainer panel",
    "POST /usage/plan-limits/refresh": "bearer waits timed maintainer panel",
    "GET /usage/rollup": "bearer waits timed viewer panel read drive land",
    "GET /vpn": "bearer waits timed viewer panel agent",
    "POST /vpn/{id}/connect": "bearer waits timed maintainer panel agent",
    "POST /vpn/{id}/disconnect": "bearer waits timed maintainer panel agent",
    "POST /vpn/import-forticlient": "bearer waits timed maintainer panel agent",
    "POST /wallet/fetch": "bearer waits timed maintainer panel agent",
    "GET /wallet/history": "bearer waits timed viewer panel agent",
    "GET /wallet/status": "bearer waits timed viewer panel agent",
    "GET /webchat/{id}/challenge": "door waits timed viewer embedded panel read drive land",
    "GET /webchat/{id}/config": "door waits timed viewer embedded panel read drive land",
    "GET /webchat/{id}/installs": "bearer waits timed viewer panel read drive land",
    "POST /webchat/{id}/message": "door waits timed maintainer embedded panel",
    "GET /webchat/{id}/messages": "door waits timed viewer embedded panel read drive land",
    "GET /webchat/widget.js": "door waits timed viewer embedded panel read drive land",
    "GET /workflows": "bearer waits timed viewer panel read drive land",
    "POST /workflows": "bearer waits timed maintainer panel",
    "DELETE /workflows/{id}": "bearer waits timed maintainer panel",
    "POST /workflows/{id}/gate": "door waits timed maintainer panel",
    "POST /workflows/{id}/gate/rotate": "bearer waits timed maintainer panel",
    "POST /workflows/{id}/run": "bearer waits timed maintainer panel",
    "GET /workflows/runs": "bearer waits timed viewer panel read drive land",
    "POST /workflows/runs/{runId}/archive": "bearer waits timed maintainer panel",
    "POST /workflows/runs/{runId}/stop": "bearer waits timed maintainer panel",
    "POST /workflows/runs/{runId}/unarchive": "bearer waits timed maintainer panel",
    "GET /workspace/children": "bearer waits timed viewer guest panel read drive land",
    "GET /workspace/classify": "bearer waits timed viewer panel read drive land",
    "POST /workspace/copy": "bearer waits timed writer panel",
    "POST /workspace/derive": "bearer waits timed viewer guest panel drive land",
    "GET /workspace/derived": "bearer waits timed viewer guest panel read drive land",
    "GET /workspace/derived-status": "bearer waits timed viewer guest panel read drive land",
    "POST /workspace/dir": "bearer waits timed writer panel",
    "DELETE /workspace/entry": "bearer waits timed writer panel",
    "POST /workspace/extract": "bearer waits timed writer panel",
    "GET /workspace/file": "bearer waits timed viewer guest panel read drive land",
    "GET /workspace/health": "bearer waits timed viewer panel read drive land",
    "GET /workspace/mainline": "bearer waits timed viewer panel read drive land",
    "GET /workspace/media": "door waits timed viewer guest panel read drive land",
    "POST /workspace/media-ticket": "bearer waits timed viewer guest panel drive land",
    "GET /workspace/modules": "bearer waits timed viewer panel read drive land",
    "POST /workspace/move": "bearer waits timed writer panel",
    "GET /workspace/raw": "bearer waits timed viewer guest panel read drive land",
    "GET /workspace/repos": "bearer waits timed viewer guest panel read drive land",
    "POST /workspace/repos": "bearer waits timed maintainer panel",
    "GET /workspace/repos/{repo}/apps": "bearer waits timed viewer panel read drive land",
    "POST /workspace/repos/{repo}/apps": "bearer waits timed maintainer panel",
    "POST /workspace/repos/{repo}/apps/{app}/start": "bearer waits timed maintainer panel",
    "POST /workspace/repos/{repo}/apps/{app}/stop": "bearer waits timed maintainer panel",
    "GET /workspace/repos/{repo}/graph": "bearer waits timed viewer panel read drive land",
    "POST /workspace/repos/{repo}/tests": "bearer waits timed maintainer panel",
    "POST /workspace/repos/new": "bearer waits timed maintainer panel",
    "GET /workspace/resolve": "bearer waits timed viewer guest panel read drive land",
    "GET /workspace/search": "bearer waits timed viewer guest panel editor read drive land",
    "GET /workspace/setup": "bearer waits timed viewer panel read drive land",
    "POST /workspace/restore": "bearer waits timed writer panel",
    "POST /workspace/setup/install": "bearer waits timed maintainer panel",
    "POST /workspace/sync": "bearer waits timed maintainer panel",
    "GET /workspace/templates": "bearer waits timed viewer panel read drive land",
    "GET /workspace/thumb": "bearer waits timed viewer guest panel read drive land",
    "GET /workspace/tree": "bearer waits timed viewer guest panel read drive land",
    "POST /workspace/upload": "bearer waits timed writer panel",
    "POST /workspace/upload ?path=<attachment>": "bearer waits timed collaborator guest panel",
    "POST /workspace/upload-archive": "bearer waits timed maintainer panel",
    "POST /workspace/upload-diff": "bearer waits timed maintainer panel",
    "ALL /x/*": "bearer waits timed maintainer panel",
};

// A route's concrete request: each `{param}` a sample segment, a raw route's `/*` two more, `ALL` read as a POST.
const requestOf = (route: ContractRoute): { readonly method: string; readonly path: string } => {
    let params = 0;
    const segments = route.path.split("/").map((segment) => {
        if (segment === "*") {
            return "a/b";
        }
        if (!segment.startsWith("{")) {
            return segment;
        }
        params += 1;
        return `p${params}`;
    });
    return { method: route.method === "ALL" ? "POST" : route.method, path: segments.join("/") };
};

// The session half of a row: the meta read as app.ts reads it, then the floor and guest list the middleware applies.
const sessionGatesOf = (method: string, path: string, target: string | undefined): string[] => {
    const meta = sandboxRouteFor(method, path)?.meta ?? {};
    return [
        meta.auth === "door" ? "door" : "bearer",
        meta.beforeBoot === true ? "early" : "waits",
        meta.stream === true ? "stream" : "timed",
        routeFloor(method, path, target),
        ...(guestReach(method, path, target) ? ["guest"] : []),
        ...(meta.embedded === true ? ["embedded"] : []),
        ...(meta.enrolment === true ? ["enrolment"] : []),
    ];
};

// The machine half: which per-boot secrets, sync token and control rungs the grants admit to the request.
const machineGatesOf = async (method: string, path: string): Promise<string[]> => {
    let checkedIn: boolean | undefined;
    const grants = grantsOf({
        panelToken: "panel",
        agentToken: "agent",
        controlTokens: unstubbed<ControlTokens>("controlTokens", {}),
        verifySync: async (_presented, poll) => {
            checkedIn = poll;
            return true;
        },
        verifyExtension: () => undefined,
    });
    const reaches = async (header: string, secret: string): Promise<boolean> =>
        (await grants.find((grant) => grant.header === header)?.authorize(secret, method, path))?.verdict === "ok";
    const panel = await reaches("x-intentic-panel", "panel");
    const agent = await reaches("x-intentic-agent", "agent");
    const sync = await reaches("x-intentic-sync", "sync");
    return [
        ...(panel ? ["panel"] : []),
        ...(agent ? ["agent"] : []),
        ...(sync ? [checkedIn === true ? "sync" : "sync-pipe"] : []),
        ...CONTROL_SCOPES.filter((scope) => controlScoped(scope, method, path)),
    ];
};

// What every gate decides about one request, spelled as a row.
const decisionsOf = async (method: string, path: string, target?: string): Promise<string> =>
    [...sessionGatesOf(method, path, target), ...(await machineGatesOf(method, path))].join(" ");

test("every declared route's own request resolves to it, and to nothing else", () => {
    const routes = [...RAW_ROUTE_LIST, ...SANDBOX_ROUTES];
    const astray = routes.filter((route) => {
        const { method, path } = requestOf(route);
        return sandboxRouteFor(method, path) !== route;
    });
    expect(astray.map((route) => route.name)).toEqual([]);
});

test("every route is held to exactly the policy recorded for it", async () => {
    const decided: Record<string, string> = {};
    for (const route of [...RAW_ROUTE_LIST, ...SANDBOX_ROUTES]) {
        const { method, path } = requestOf(route);
        decided[`${route.method} ${route.path}`] = await decisionsOf(method, path);
    }
    decided["POST /workspace/upload ?path=<attachment>"] = await decisionsOf("POST", "/workspace/upload", `${ATTACHMENTS_DIR}/u1/shot.png`);
    expect(decided).toEqual(RECORDED);
});
