import type { Provider, ResolvedInputs } from "@intentic/engine";
import { z } from "zod";
import { normalize, SECRET_KOMODO, starterDockerfile } from "../core/ci-yaml.js";
import { hasPendingRef, parseInputs, sshSchema } from "../core/inputs.js";
import { overSsh } from "../core/over-ssh.js";
import type { SshExecutor } from "../core/ssh.js";
import { sshExecutor } from "../core/ssh.js";
import type { ForgejoApi } from "./forgejo-api.js";
import { forgejoApi } from "./forgejo-api.js";
import { FORGEJO_HTTP_PORT } from "./forgejo.js";

// ssh targets the control-plane host; commitFile and setRepoSecret reach Forgejo over an SSH port-forward.
const ciSchema = sshSchema.extend({
    // Shared admin username; adminPassword is Forgejo's, komodoPassword is Komodo's (stored as a repo secret).
    adminUser: z.string(),
    adminPassword: z.string(),
    komodoPassword: z.string(),
    // Repo + registry namespace: a team's org, or the admin user when team-less.
    owner: z.string(),
    repoName: z.string(),
    // Env branch the workflow triggers on (production -> "main").
    branch: z.string(),
    // Forgejo built-in registry authority (e.g. "127.0.0.1:3000"); image is registry/owner/repo:tag.
    registry: z.string(),
    // Image tag; the environment name, so co-located environments publish to distinct tags.
    tag: z.string(),
    // write:package token the Action logs into the registry with; set as the REGISTRY_TOKEN repo secret.
    packagesToken: z.string(),
    // Komodo's host-internal url; reachable because the runner runs with --network host.
    komodoUrl: z.string(),
    // Komodo deployment id the notify step redeploys; auto_update polling is the backstop.
    deployment: z.string(),
});
type CiInputs = z.infer<typeof ciSchema>;
const parse = (inputs: ResolvedInputs): CiInputs => parseInputs(ciSchema, inputs, "ci");

const SECRET_REGISTRY = "REGISTRY_TOKEN";
const workflowPath = (tag: string): string => `.forgejo/workflows/build-${tag}.yaml`;
const DOCKERFILE_PATH = "Dockerfile";

// Forgejo Actions workflow: on push to the env branch, builds the Dockerfile, pushes to the Forgejo registry, then
// logs into Komodo and triggers a Deploy. `${{ }}` are Forgejo expressions; `$JWT`/`$KOMODO_PASSWORD` are shell, kept
// literal.
const workflowYaml = (parsed: CiInputs): string => {
    const base = `${parsed.registry}/${parsed.owner}/${parsed.repoName}`;
    return [
        "# Generated by intentic: build the image, push it to the Forgejo registry, notify Komodo to redeploy.",
        "on:",
        "  push:",
        `    branches: [ "${parsed.branch}" ]`,
        "jobs:",
        "  build:",
        "    runs-on: docker",
        "    steps:",
        "      - uses: https://github.com/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1",
        "      - uses: https://github.com/docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0",
        "        with:",
        `          registry: ${parsed.registry}`,
        `          username: ${parsed.adminUser}`,
        `          password: \${{ secrets.${SECRET_REGISTRY} }}`,
        "      - uses: https://github.com/docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2",
        "        with:",
        "          context: .",
        "          push: true",
        "          tags: |",
        `            ${base}:${parsed.tag}`,
        `            ${base}:\${{ github.sha }}`,
        "      - name: notify komodo to redeploy",
        "        run: |",
        `          KOMODO_PASSWORD='\${{ secrets.${SECRET_KOMODO} }}'`,
        `          JWT=$(curl -sf ${parsed.komodoUrl}/auth/login/LoginLocalUser -H 'Content-Type: application/json' \\`,
        `            -d '{"username":"${parsed.adminUser}","password":"'"$KOMODO_PASSWORD"'"}' | sed -n 's/.*"jwt":"\\([^"]*\\)".*/\\1/p')`,
        `          curl -sf ${parsed.komodoUrl}/execute -H "Authorization: $JWT" -H 'Content-Type: application/json' \\`,
        `            -d '{"type":"Deploy","params":{"deployment":"${parsed.deployment}"}}'`,
        "",
    ].join("\n");
};

// App's CI/CD wiring: commits the build-and-deploy workflow and sets the registry-push + Komodo-login secrets it
// consumes. `read` keys off the committed workflow file, since secrets can't be read back and are re-set every apply.
export const createCiProvider = (api: ForgejoApi = forgejoApi, executor: SshExecutor = sshExecutor): Provider => ({
    read: async (inputs, ctx) => {
        if (hasPendingRef(inputs, "komodoUrl", "packagesToken")) {
            return undefined;
        }
        const parsed = parse(inputs);
        try {
            return await overSsh(executor, parsed, FORGEJO_HTTP_PORT, async (baseUrl) => {
                const workflow = await api.readFile({
                    baseUrl,
                    user: parsed.adminUser,
                    password: parsed.adminPassword,
                    owner: parsed.owner,
                    name: parsed.repoName,
                    branch: parsed.branch,
                    path: workflowPath(parsed.tag),
                });
                if (workflow === undefined) {
                    return undefined;
                }
                return { outputs: {}, detail: { workflow } };
            });
        } catch (error) {
            ctx.log(`ci "${ctx.id}": forgejo not reachable yet, treating as not-yet-created: ${String(error)}`);
            return undefined;
        }
    },
    diff: (inputs, observed) => {
        const workflow = observed.detail?.["workflow"];
        if (typeof workflow !== "string" || normalize(workflow) !== normalize(workflowYaml(parse(inputs)))) {
            return { action: "update", reason: "ci workflow differs from desired" };
        }
        return { action: "noop" };
    },
    apply: async (inputs) => {
        const parsed = parse(inputs);
        return overSsh(executor, parsed, FORGEJO_HTTP_PORT, async (baseUrl) => {
            const repo = {
                baseUrl,
                user: parsed.adminUser,
                password: parsed.adminPassword,
                owner: parsed.owner,
                name: parsed.repoName,
            };
            // Packages token the Action pushes with, and the Komodo admin password the notify step logs in with.
            await api.setRepoSecret({ ...repo, secretName: SECRET_REGISTRY, data: parsed.packagesToken });
            await api.setRepoSecret({ ...repo, secretName: SECRET_KOMODO, data: parsed.komodoPassword });
            // Seeds a starter Dockerfile only when the repo has none; never clobbers the author's own Dockerfile.
            const dockerfile = await api.readFile({ ...repo, branch: parsed.branch, path: DOCKERFILE_PATH });
            if (dockerfile === undefined) {
                await api.commitFile({
                    ...repo,
                    branch: parsed.branch,
                    path: DOCKERFILE_PATH,
                    content: starterDockerfile(),
                    message: "intentic: starter Dockerfile",
                });
            }
            // Commits the workflow last, so its first run already sees the Dockerfile and secrets.
            await api.commitFile({
                ...repo,
                branch: parsed.branch,
                path: workflowPath(parsed.tag),
                content: workflowYaml(parsed),
                message: "intentic: ci workflow",
            });
            return {};
        });
    },
    delete: async (inputs) => {
        const parsed = parse(inputs);
        await overSsh(executor, parsed, FORGEJO_HTTP_PORT, async (baseUrl) => {
            const repo = {
                baseUrl,
                user: parsed.adminUser,
                password: parsed.adminPassword,
                owner: parsed.owner,
                name: parsed.repoName,
            };
            // Drops the workflow file and its secrets; idempotent on a 404, since the repo may be pruned separately.
            await api.deleteFile({ ...repo, branch: parsed.branch, path: workflowPath(parsed.tag), message: "intentic: remove ci workflow" });
            await api.deleteRepoSecret({ ...repo, secretName: SECRET_REGISTRY });
            await api.deleteRepoSecret({ ...repo, secretName: SECRET_KOMODO });
        });
    },
});
