import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import { parseArgs } from "node:util";
import { packageRoot, repoRoot } from "@intentic/constants/node";
import { isNewer } from "@intentic/sandbox-contract";
import { z } from "zod";
import { type DocumentSpec, documentKey } from "../evolution/documents.js";
import { typeFromSchema } from "./json-schema-type.js";
import { type Definition, stateModules } from "./state-modules.js";

// The shape generator: writes the state registry (src/state-registry.ts, every document and boot step the
// source defines, which the boot step and the pre-flight read), freezes every shape each stored document has had, and
// writes the type-level checks that each frozen shape still converts to what today's schema accepts
// (store/evolution/conversion-types.ts), so a change that would strand an old file fails `tsc` at the document until a
// conversion covers it. Run by verify-turn's fixer beside the contract
// lock (`node --import tsx src/store/shapes/write-state-shapes.ts`); `--seed` backfills, once, the shapes every release
// since the contract lock existed recorded for contract-exported schemas. Never shipped: excluded from the build.

interface FrozenShape {
    readonly type: string;
    // Where the shape was first seen: a release tag for a seeded one, the UTC day it was frozen otherwise.
    readonly since: string;
}

type Shapes = Record<string, FrozenShape[]>;

const PACKAGE = packageRoot(import.meta.url);
const SOURCE = join(PACKAGE, "src");
const GENERATED = join(SOURCE, "store", "generated");
const SHAPES_FILE = join(GENERATED, "state-shapes.json");
const CHECKS_FILE = join(GENERATED, "state-shapes.ts");
// Above every subsystem, beside main.ts: it imports each one's documents, so a registry inside `store/` would close an
// import cycle through every subsystem that stores anything.
const REGISTRY_FILE = join(SOURCE, "state-registry.ts");
const REPO = repoRoot(import.meta.url);

const git = (...args: string[]): string | undefined => {
    try {
        return execFileSync("git", ["-C", REPO, ...args], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024, stdio: ["ignore", "pipe", "ignore"] });
    } catch {
        // silent-catch: a path absent at a tag, or no git at all, is simply nothing to seed from
        return undefined;
    }
};

// Every path the contract lock has had, asked of git rather than spelled here: its package keeps its own directory name
// while the directory above it moved (the overhaul of 2026-09-06), so one glob finds it at any release.
const lockPaths = (): string[] => [
    ...new Set((git("log", "--all", "--format=", "--name-only", "--", ":(glob)**/sandbox-contract/contract.lock.json") ?? "").split("\n").filter((path) => path !== "")),
];

interface Located {
    readonly spec: DocumentSpec;
    // Package-relative module path and the name it exports the spec under, for the generated import.
    readonly module: string;
    readonly name: string;
}

// The registry module's source: an import of every definition by the name its module exports it under, and two lists
// read when called, so a module that reaches the registry back through an import cycle never meets an unfilled binding.
const registrySource = (documents: readonly Definition[], steps: readonly Definition[]): string => {
    const from = (module: string): string => {
        const path = module.replace(/\.ts$/, ".js");
        return path.startsWith(".") ? path : `./${path}`;
    };
    const names = new Map<string, string[]>();
    for (const { module, name } of [...documents, ...steps]) {
        names.set(module, [...(names.get(module) ?? []), name]);
    }
    const imports = [...names]
        .toSorted(([a], [b]) => a.localeCompare(b))
        .map(([module, exported]) => `import { ${exported.toSorted().join(", ")} } from "${from(module)}";`);
    return [
        "// Generated by src/store/shapes/write-state-shapes.ts from every `export const name = defineDocument(…)` and",
        "// `defineStep(…)` in src/. Do not edit; run the generator. The one list of every stored document and structural boot",
        "// step this build knows: main.ts hands it to the boot step and state-plan.ts plans with it, so the two agree whatever",
        "// else either process loads. state-registry.test.ts fails when a definition is missing from it. Above every",
        "// subsystem on purpose: nothing under one imports it.",
        'import type { DocumentSpec } from "./store/evolution/documents.js";',
        'import type { StructuralStep } from "./store/evolution/state-steps.js";',
        ...imports,
        "",
        "export const stateDocuments = (): readonly DocumentSpec[] => [",
        ...documents.map(({ name }) => `    ${name},`),
        "];",
        "",
        "// By id, not by the order modules happened to load in: the plan must not depend on an import graph.",
        "export const stateSteps = (): readonly StructuralStep[] =>",
        `    [${steps.map(({ name }) => name).join(", ")}].toSorted((a, b) => a.id.localeCompare(b.id));`,
        "",
    ].join("\n");
};

// Every document the registry just written lists, beside the module and name it imports it under (the registry lists
// them in the order of the definitions): the generated checks import each by that name. Two documents at one address
// would be one file read two ways.
const locate = async (documents: readonly Definition[]): Promise<Located[]> => {
    const registry = (await import(pathToFileURL(REGISTRY_FILE).href)) as { stateDocuments: () => readonly DocumentSpec[] };
    const listed = registry.stateDocuments();
    if (listed.length !== documents.length) {
        throw new Error(`the registry lists ${listed.length} documents where the source defines ${documents.length}`);
    }
    const located = listed.map((spec, index) => ({ spec, module: documents[index]?.module ?? "", name: documents[index]?.name ?? "" }));
    const keys = located.map(({ spec }) => documentKey(spec));
    const doubled = keys.filter((key, index) => keys.indexOf(key) !== index);
    if (doubled.length > 0) {
        throw new Error(`two documents are declared at one address: ${[...new Set(doubled)].join(", ")}`);
    }
    return located;
};

const shapeOf = (schema: unknown): string => {
    try {
        return typeFromSchema(z.toJSONSchema(schema as z.ZodType, { io: "input", unrepresentable: "any" }));
    } catch {
        // silent-catch: a schema JSON Schema cannot spell freezes as unknown, which every later shape fits
        return "unknown";
    }
};

const append = (shapes: Shapes, key: string, shape: FrozenShape): void => {
    const known = shapes[key] ?? [];
    if (!known.some((frozen) => frozen.type === shape.type)) {
        shapes[key] = [...known, shape];
    }
};

// Every release that carried the contract lock, oldest first, contributing the output shape it recorded for each
// document whose schema the contract exports: exactly what that release wrote to disk.
const seed = async (shapes: Shapes, located: readonly Located[]): Promise<void> => {
    const contract = (await import("@intentic/sandbox-contract")) as Record<string, unknown>;
    const names = new Map<unknown, string>(Object.entries(contract).map(([name, value]) => [value, name]));
    const tags = (git("tag", "--sort=creatordate") ?? "").split("\n").filter((tag) => tag !== "");
    const locks = lockPaths();
    for (const tag of tags) {
        const text = locks.map((path) => git("show", `${tag}:${path}`)).find((found) => found !== undefined);
        if (text === undefined) {
            continue;
        }
        const lock = JSON.parse(text) as Record<string, unknown>;
        for (const { spec } of located) {
            const name = names.get(spec.schema);
            if (name !== undefined && lock[name] !== undefined) {
                append(shapes, documentKey(spec), { type: typeFromSchema(lock[name]), since: tag });
            }
        }
    }
};

const aliasOf = (name: string, index: number): string => `${name.charAt(0).toUpperCase()}${name.slice(1)}${index}`;

// A shape frozen from a release older than the document's horizon is past what this build converts on purpose.
const beforeHorizon = (shape: FrozenShape, horizon: string | undefined): boolean =>
    horizon !== undefined && shape.since.startsWith("v") && isNewer(horizon.replace(/^v/, ""), shape.since.replace(/^v/, ""));

const checksSource = (shapes: Shapes, located: readonly Located[]): string => {
    const byKey = new Map(located.map((entry) => [documentKey(entry.spec), entry]));
    const keys = Object.keys(shapes)
        .filter((key) => byKey.has(key))
        .toSorted();
    const imports = keys
        .map((key) => byKey.get(key))
        .filter((entry): entry is Located => entry !== undefined)
        .toSorted((a, b) => a.module.localeCompare(b.module) || a.name.localeCompare(b.name))
        .map(({ module, name }) => `import type { ${name} } from "../../${module.replace(/\.ts$/, ".js")}";`);
    const blocks: string[] = [];
    const checks: string[] = [];
    for (const key of keys) {
        const entry = byKey.get(key);
        if (entry === undefined) {
            continue;
        }
        blocks.push(`// ${key}`);
        (shapes[key] ?? []).forEach((shape, index) => {
            if (beforeHorizon(shape, entry.spec.horizon)) {
                blocks.push(`// since ${shape.since}: before the horizon (${entry.spec.horizon ?? ""}), not converted`);
                return;
            }
            const alias = aliasOf(entry.name, index);
            blocks.push(`// since ${shape.since}`, `type ${alias} = ${shape.type};`);
            checks.push(`Fits<Accepted<typeof ${entry.name}>, Converted<${alias}, typeof ${entry.name}>>`);
        });
        checks.push(`Fits<never, ReusedKeys<typeof ${entry.name}>>`);
        blocks.push("");
    }
    return [
        "// Generated by src/store/shapes/write-state-shapes.ts from state-shapes.json: every shape each stored document has",
        "// had, and the checks that each still converts to what today's schema accepts. Do not edit; run the generator. A",
        "// failure below names the document and property that would strand an old file: add a conversion to its history.",
        'import type { Accepted, Converted, Fits, ReusedKeys } from "../evolution/conversion-types.js";',
        ...imports,
        "",
        ...blocks,
        "export type StateShapeChecks = [",
        ...checks.map((check) => `    ${check},`),
        "];",
        "",
    ].join("\n");
};

const readShapes = async (): Promise<Shapes> => {
    try {
        return JSON.parse(await readFile(SHAPES_FILE, "utf8")) as Shapes;
    } catch {
        // silent-catch: the first run starts from nothing
        return {};
    }
};

const { values } = parseArgs({ options: { seed: { type: "boolean", default: false } } });

const modules = await stateModules(SOURCE);
await writeFile(REGISTRY_FILE, registrySource(modules.documents, modules.steps));
const located = await locate(modules.documents);
const shapes = await readShapes();
if (values.seed) {
    await seed(shapes, located);
}
const utcDay = new Date().toISOString().slice(0, 10);
for (const { spec } of located) {
    append(shapes, documentKey(spec), { type: shapeOf(spec.schema), since: utcDay });
}
const sorted: Shapes = Object.fromEntries(Object.entries(shapes).toSorted(([a], [b]) => a.localeCompare(b)));
await mkdir(dirname(SHAPES_FILE), { recursive: true });
await writeFile(SHAPES_FILE, `${JSON.stringify(sorted, undefined, 2)}\n`);
await writeFile(CHECKS_FILE, checksSource(sorted, located));
process.stdout.write(
    `${Object.values(sorted).reduce((sum, list) => sum + list.length, 0)} shapes across ${Object.keys(sorted).length} documents; ` +
        `${modules.documents.length} documents and ${modules.steps.length} steps in the registry\n`,
);
