import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { pathToFileURL } from "node:url";
import { parseArgs } from "node:util";
import { packageRoot, repoRoot } from "@intentic/constants/node";
import { z } from "zod";
import { type DocumentSpec, documentKey } from "../evolution/documents.js";
import { ANYTHING, typeFromSchema } from "./json-schema-type.js";
import { beforeHorizon, freeze, type FrozenShape, isRelease, type Release, type Shapes } from "./shape-releases.js";
import { type Definition, stateModules } from "./state-modules.js";

// The shape generator, two modes. `--freeze` (the land check's fixer, after every land that touched daemon or contract
// source) writes the state registry (src/bootstrap/state-registry.ts, every document and boot step the source defines,
// which the boot step and the pre-flight read) and records each document's current shape in state-shapes.json, the
// only one of its outputs that is committed. `--checks` (the package's `pretypecheck`) writes the shape checks from that
// record: the type-level checks that each frozen shape still converts to what today's schema accepts and loses no key
// on the way (store/evolution/conversion-types.ts), so a change that would strand an old file fails `tsc` at the
// document until a conversion covers it. `--seed` backfills, once, the shapes every release since the contract lock
// existed recorded for contract-exported schemas. Never shipped: excluded from the build.
//
// Which release first shipped each shape, and which shapes never shipped at all, is shape-releases.ts.

const PACKAGE = packageRoot(import.meta.url);
const SOURCE = join(PACKAGE, "src");
const GENERATED = join(SOURCE, "store", "generated");
const SHAPES_FILE = join(GENERATED, "state-shapes.json");
const CHECKS_FILE = join(GENERATED, "state-shapes.ts");
// In the boot wiring, which sits above every subsystem (nothing under one imports bootstrap/): it imports each one's
// documents, so a registry inside `store/` would close an import cycle through every subsystem that stores anything.
const REGISTRY_FILE = join(SOURCE, "bootstrap", "state-registry.ts");
const REPO = repoRoot(import.meta.url);

const git = (...args: string[]): string | undefined => {
    try {
        return execFileSync("git", ["-C", REPO, ...args], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024, stdio: ["ignore", "pipe", "ignore"] });
    } catch {
        // allow(silent-catch): a path absent at a tag, or no git at all, is simply nothing to seed from
        return undefined;
    }
};

// Every path the contract lock has had, asked of git rather than spelled here: its package keeps its own directory name
// while the directory above it moved (the overhaul of 2026-09-06), so one glob finds it at any release.
const lockPaths = (): string[] => [
    ...new Set((git("log", "--all", "--format=", "--name-only", "--", ":(glob)**/sandbox-contract/contract.lock.json") ?? "").split("\n").filter((path) => path !== "")),
];

interface Located {
    readonly spec: DocumentSpec;
    // Package-relative module path and the name it exports the spec under, for the generated import.
    readonly module: string;
    readonly name: string;
}

// The registry module's source: an import of every definition by the name its module exports it under, and two lists
// read when called, so a module that reaches the registry back through an import cycle never meets an unfilled binding.
const registrySource = (documents: readonly Definition[], steps: readonly Definition[]): string => {
    const from = (module: string): string => {
        const path = `../${module.replace(/\.ts$/, ".js")}`;
        return path.startsWith("../bootstrap/") ? `./${path.slice("../bootstrap/".length)}` : path;
    };
    const names = new Map<string, string[]>();
    for (const { module, name } of [...documents, ...steps]) {
        names.set(module, [...(names.get(module) ?? []), name]);
    }
    const imports = [...names]
        .toSorted(([a], [b]) => a.localeCompare(b))
        .map(([module, exported]) => `import { ${exported.toSorted().join(", ")} } from "${from(module)}";`);
    return [
        "// Generated by src/store/shapes/write-state-shapes.ts from every `export const name = defineDocument(…)` and",
        "// `defineStep(…)` in src/. Do not edit; run the generator. The one list of every stored document and structural boot",
        "// step this build knows: main.ts hands it to the boot step and state-plan.ts plans with it, so the two agree whatever",
        "// else either process loads. state-registry.test.ts fails when a definition is missing from it. Above every",
        "// subsystem, in the boot wiring, on purpose: nothing under a subsystem imports bootstrap/.",
        'import type { DocumentSpec } from "../store/evolution/documents.js";',
        'import type { StructuralStep } from "../store/evolution/state-steps.js";',
        ...imports,
        "",
        "export const stateDocuments = (): readonly DocumentSpec[] => [",
        ...documents.map(({ name }) => `    ${name},`),
        "];",
        "",
        "// By id, not by the order modules happened to load in: the plan must not depend on an import graph.",
        "export const stateSteps = (): readonly StructuralStep[] =>",
        `    [${steps.map(({ name }) => name).join(", ")}].toSorted((a, b) => a.id.localeCompare(b.id));`,
        "",
    ].join("\n");
};

// Every document the registry just written lists, beside the module and name it imports it under (the registry lists
// them in the order of the definitions): the generated checks import each by that name. Two documents at one address
// would be one file read two ways.
const locate = async (documents: readonly Definition[]): Promise<Located[]> => {
    const registry = (await import(pathToFileURL(REGISTRY_FILE).href)) as { stateDocuments: () => readonly DocumentSpec[] };
    const listed = registry.stateDocuments();
    if (listed.length !== documents.length) {
        throw new Error(`the registry lists ${listed.length} documents where the source defines ${documents.length}`);
    }
    const located = listed.map((spec, index) => ({ spec, module: documents[index]?.module ?? "", name: documents[index]?.name ?? "" }));
    const keys = located.map(({ spec }) => documentKey(spec));
    const doubled = keys.filter((key, index) => keys.indexOf(key) !== index);
    if (doubled.length > 0) {
        throw new Error(`two documents are declared at one address: ${[...new Set(doubled)].join(", ")}`);
    }
    return located;
};

// A field whose schema accepts anything (`z.unknown()`, `z.any()`) says so, so it freezes as `unknown`, which a later
// narrowing fails, rather than as the `any` an unrepresentable type (a transform, a custom check) freezes as.
const markAnything = (context: { zodSchema: unknown; jsonSchema: Record<string, unknown> }): void => {
    const kind = (context.zodSchema as { _zod?: { def?: { type?: unknown } } })._zod?.def?.type;
    if (kind === "unknown" || kind === "any") {
        context.jsonSchema[ANYTHING] = true;
    }
};

const shapeOf = (schema: unknown): string => {
    try {
        return typeFromSchema(z.toJSONSchema(schema as z.ZodType, { io: "input", unrepresentable: "any", override: markAnything }));
    } catch {
        // allow(silent-catch): a schema JSON Schema cannot spell freezes as unknown, which every later shape fits
        return "unknown";
    }
};

const append = (shapes: Shapes, key: string, shape: FrozenShape): void => {
    const known = shapes[key] ?? [];
    if (!known.some((frozen) => frozen.type === shape.type)) {
        shapes[key] = [...known, shape];
    }
};

// Every release that carried the contract lock, oldest first, contributing the output shape it recorded for each
// document whose schema the contract exports: exactly what that release wrote to disk.
const seed = async (shapes: Shapes, located: readonly Located[]): Promise<void> => {
    const contract = (await import("@intentic/sandbox-contract")) as Record<string, unknown>;
    const names = new Map<unknown, string>(Object.entries(contract).map(([name, value]) => [value, name]));
    const tags = (git("tag", "--sort=creatordate") ?? "").split("\n").filter((tag) => tag !== "");
    const locks = lockPaths();
    for (const tag of tags) {
        const text = locks.map((path) => git("show", `${tag}:${path}`)).find((found) => found !== undefined);
        if (text === undefined) {
            continue;
        }
        const lock = JSON.parse(text) as Record<string, unknown>;
        for (const { spec } of located) {
            const name = names.get(spec.schema);
            if (name !== undefined && lock[name] !== undefined) {
                append(shapes, documentKey(spec), { type: typeFromSchema(lock[name]), since: tag });
            }
        }
    }
};

const aliasOf = (name: string, index: number): string => `${name.charAt(0).toUpperCase()}${name.slice(1)}${index}`;

const checksSource = (shapes: Shapes, located: readonly Located[]): string => {
    const byKey = new Map(located.map((entry) => [documentKey(entry.spec), entry]));
    const keys = Object.keys(shapes)
        .filter((key) => byKey.has(key))
        .toSorted();
    const imports = keys
        .map((key) => byKey.get(key))
        .filter((entry): entry is Located => entry !== undefined)
        .toSorted((a, b) => a.module.localeCompare(b.module) || a.name.localeCompare(b.name))
        .map(({ module, name }) => `import type { ${name} } from "../../${module.replace(/\.ts$/, ".js")}";`);
    const blocks: string[] = [];
    const checks: string[] = [];
    for (const key of keys) {
        const entry = byKey.get(key);
        if (entry === undefined) {
            continue;
        }
        blocks.push(`// ${key}`);
        (shapes[key] ?? []).forEach((shape, index, list) => {
            if (beforeHorizon(list[index + 1], entry.spec.horizon)) {
                blocks.push(`// since ${shape.since}: before the horizon (${entry.spec.horizon ?? ""}), not converted`);
                return;
            }
            const alias = aliasOf(entry.name, index);
            blocks.push(`// since ${shape.since}`, `type ${alias} = ${shape.type};`);
            checks.push(`Fits<Accepted<typeof ${entry.name}>, Converted<${alias}, typeof ${entry.name}>>`);
            checks.push(`Fits<never, VanishedKeys<${alias}, typeof ${entry.name}>>`);
        });
        checks.push(`Fits<never, ReusedKeys<typeof ${entry.name}>>`);
        blocks.push("");
    }
    return [
        "// Generated by src/store/shapes/write-state-shapes.ts --checks from state-shapes.json before every typecheck, and not",
        "// committed: every shape each stored document has had, and the checks that each still converts to what today's schema",
        "// accepts and loses no key it held. A failure below names the document and the property (or the vanished key's path)",
        "// that would strand an old file: add a conversion to its history (a `drop` or a `rename` for a key that left).",
        'import type { Accepted, Converted, Fits, ReusedKeys, VanishedKeys } from "../evolution/conversion-types.js";',
        ...imports,
        "",
        ...blocks,
        "export type StateShapeChecks = [",
        ...checks.map((check) => `    ${check},`),
        "];",
        "",
    ].join("\n");
};

const readShapes = async (): Promise<Shapes> => {
    try {
        return JSON.parse(await readFile(SHAPES_FILE, "utf8")) as Shapes;
    } catch {
        // allow(silent-catch): the first run starts from nothing
        return {};
    }
};

// The record as a release tag holds it, undefined for a tag from before the record existed.
const SHAPES_PATH = relative(REPO, SHAPES_FILE).split("\\").join("/");
const releasedRecords = new Map<string, Shapes | undefined>();
const recordAt = (tag: string): Shapes | undefined => {
    if (!releasedRecords.has(tag)) {
        const text = git("show", `${tag}:${SHAPES_PATH}`);
        releasedRecords.set(tag, text === undefined ? undefined : (JSON.parse(text) as Shapes));
    }
    return releasedRecords.get(tag);
};

// Release tags, oldest release first, with the UTC day each was cut.
const releases = (): Release[] =>
    (git("for-each-ref", "--sort=creatordate", "--format=%(refname:short) %(creatordate:iso-strict)", "refs/tags") ?? "")
        .split("\n")
        .map((line) => line.split(" "))
        .filter((parts): parts is [string, string] => parts.length === 2 && isRelease(parts[0] ?? ""))
        // A UTC day, the calendar a shape frozen before stamping by release is dated in (shape-releases.ts).
        .map(([tag, date]) => ({ tag, day: new Date(date).toISOString().slice(0, 10) }));

const { values } = parseArgs({
    options: { seed: { type: "boolean", default: false }, freeze: { type: "boolean", default: false }, checks: { type: "boolean", default: false } },
});
// The fixer's run, when no mode is named: it is the one that records.
const freezing = values.freeze || !values.checks;

const modules = await stateModules(SOURCE);
if (freezing) {
    await writeFile(REGISTRY_FILE, registrySource(modules.documents, modules.steps));
}
const located = await locate(modules.documents);
let shapes = await readShapes();
if (freezing) {
    if (values.seed) {
        await seed(shapes, located);
    }
    shapes = freeze(shapes, new Map(located.map(({ spec }) => [documentKey(spec), shapeOf(spec.schema)])), releases(), recordAt);
}
const sorted: Shapes = Object.fromEntries(Object.entries(shapes).toSorted(([a], [b]) => a.localeCompare(b)));
await mkdir(dirname(SHAPES_FILE), { recursive: true });
if (freezing) {
    await writeFile(SHAPES_FILE, `${JSON.stringify(sorted, undefined, 2)}\n`);
}
await writeFile(CHECKS_FILE, checksSource(sorted, located));
process.stdout.write(
    `${Object.values(sorted).reduce((sum, list) => sum + list.length, 0)} shapes across ${Object.keys(sorted).length} documents${ 
        freezing ? `; ${modules.documents.length} documents and ${modules.steps.length} steps in the registry\n` : "\n"}`,
);
