// Generated by src/store/shapes/write-state-shapes.ts from every `export const name = defineDocument(…)` and
// `defineStep(…)` in src/. Do not edit; run the generator. The one list of every stored document and structural boot
// step this build knows: main.ts hands it to the boot step and state-plan.ts plans with it, so the two agree whatever
// else either process loads. state-registry.test.ts fails when a definition is missing from it. Above every
// subsystem, in the boot wiring, on purpose: nothing under a subsystem imports bootstrap/.
import type { DocumentSpec } from "../store/evolution/documents.js";
import type { StructuralStep } from "../store/evolution/state-steps.js";
import { restartResumeDocument } from "../agent/run/turn/restart-resume.js";
import { approvalsDocument } from "../approvals/approvals-store.js";
import { areasDocument } from "../areas/areas-store.js";
import { membersDocument, ownerDocument } from "../auth/auth.js";
import { passkeysDocument } from "../auth/passkeys/passkey-store.js";
import { controlTokensDocument } from "../auth/tokens/control-tokens.js";
import { doorTokensDocument } from "../auth/tokens/door-tokens.js";
import { automationRunsDocument, automationsDocument, automationsRelocationStep } from "../automations/automations-store.js";
import { heldWakesDocument } from "../automations/held-wakes-store.js";
import { scheduleCoverageDocument } from "../automations/schedule-coverage.js";
import { sendersDocument } from "../automations/senders-store.js";
import { browserPasskeysDocument } from "../browser/tools/passkeys.js";
import { capabilitiesDocument } from "../capabilities/capabilities-store.js";
import { capabilitySecretsDocument, extensionSecretsDocument } from "../capabilities/credentials/secret-vault.js";
import { dismissalsDocument } from "../capabilities/offers/dismissals-store.js";
import { choreLedgerDocument, choreProbesDocument } from "../chores/chores-store.js";
import { ciDocument } from "../ci/ci-store.js";
import { conversationRecordDocument } from "../conversations/registry/agents-store.js";
import { pre1308ImportStep } from "../conversations/registry/pre-1308-import.js";
import { enginePolicyDocument } from "../engines/engine-policy.js";
import { engineStateDocument } from "../engines/engine-store.js";
import { runtimeInstallsDocument } from "../environment/runtime-installs.js";
import { extensionApprovalsDocument } from "../extensions/extension-approvals.js";
import { extensionEnablementDocument } from "../extensions/extension-enablement.js";
import { extensionSettingsDocument } from "../extensions/extension-settings.js";
import { extensionUpdatePolicyDocument, extensionUpdatesDocument } from "../extensions/extension-updates.js";
import { extensionUsageDocument } from "../extensions/extension-usage.js";
import { hookApprovalsDocument, hookRequestsDocument } from "../guard/hook-approvals.js";
import { syncEnrollmentsDocument } from "../hosts/desktop-sync.js";
import { hostSetupSeededDocument } from "../hosts/host-seed.js";
import { issuesDocument } from "../issues/issues-store.js";
import { loopDesignsDocument, loopsDocument } from "../loops/loops-store.js";
import { needsDocument } from "../needs/needs-store.js";
import { hostEnrollmentsDocument, hostPairConsumedDocument, runnerEnrollmentsDocument, runnerPairConsumedDocument, syncPairConsumedDocument, webextEnrollmentsDocument, webextPairConsumedDocument } from "../peers/enrollment.js";
import { peerToolsDocument } from "../peers/peer-tool-memory.js";
import { conversationGrantsDocument } from "../personas/conversation-grants.js";
import { personasDocument } from "../personas/personas-store.js";
import { bundleManifestDocument } from "../portability/bundle-arrival.js";
import { definitionDocument } from "../portability/definition.js";
import { privacyLedgerDocument } from "../privacy/privacy-ledger.js";
import { privacyShieldDocument } from "../privacy/privacy-policy.js";
import { privacyVaultDocument } from "../privacy/privacy-vault.js";
import { pushDocument } from "../push/push-store.js";
import { ruleFiringsDocument } from "../rules/rule-firings.js";
import { runnerIdentityDocument } from "../runners/runner-identity.js";
import { claudeSeatsDocument } from "../runtimes/claude/claude-seats.js";
import { safetyLogDocument } from "../safety/safety-log.js";
import { autostartDocument } from "../scaffold/autostart.js";
import { credentialReleasesDocument } from "../secrets/credential-grants.js";
import { secretHostGuardsDocument } from "../secrets/host-guards.js";
import { sandboxSecretsDocument } from "../secrets/sandbox-secrets.js";
import { secretUsesDocument } from "../secrets/secret-uses.js";
import { threadSessionsDocument } from "../sessions/thread-sessions.js";
import { memberAudienceDocument } from "../settings/member-audience.js";
import { settingsDocument } from "../settings/settings-store.js";
import { sharesDocument } from "../share/share-store.js";
import { conversationsSchemaStep } from "../store/conversations-db.js";
import { conversionsDocument } from "../store/evolution/state-convergence.js";
import { landCheckLeftoversStep } from "../store/evolution/steps/land-check-leftovers.js";
import { pushChecksLeftoversStep } from "../store/evolution/steps/push-checks-leftovers.js";
import { stateRegroupStep } from "../store/evolution/steps/state-regroup.js";
import { issueInstallsDocument, webchatInstallsDocument } from "../store/installs.js";
import { newestRunDocument } from "../store/newest-run.js";
import { bootFailureDocument } from "../system/boot/boot-failure.js";
import { stagedUpdateDocument, updateOutcomeDocument, updatePreparingDocument } from "../system/boot/staged-update.js";
import { skippedUpdateDocument } from "../system/boot/update-skip.js";
import { heavyCommandsDocument } from "../system/resources/heavy-commands.js";
import { workspaceIdentityDocument } from "../system/workspace-identity.js";
import { accountUsageDocument } from "../usage/account-usage.js";
import { modelCooldownsDocument } from "../usage/model-cooldowns.js";
import { modelRefusalsDocument } from "../usage/model-refusals.js";
import { observedLimitsDocument } from "../usage/observed-limits.js";
import { providerRefusalsDocument } from "../usage/provider-refusals.js";
import { usageParksDocument } from "../usage/usage-parks.js";
import { walletLedgerDocument } from "../wallet/wallet-ledger.js";
import { webchatOutboxDocument } from "../webchat/webchat-outbox.js";
import { workflowGateTokensStep, workflowRunsDocument, workflowsDocument } from "../workflows/workflows-store.js";
import { dependencyRequestsDocument } from "../workspace/deps/reconcile-deps.js";

export const stateDocuments = (): readonly DocumentSpec[] => [
    restartResumeDocument,
    approvalsDocument,
    areasDocument,
    membersDocument,
    ownerDocument,
    passkeysDocument,
    controlTokensDocument,
    doorTokensDocument,
    automationRunsDocument,
    automationsDocument,
    heldWakesDocument,
    scheduleCoverageDocument,
    sendersDocument,
    browserPasskeysDocument,
    capabilitiesDocument,
    capabilitySecretsDocument,
    extensionSecretsDocument,
    dismissalsDocument,
    choreLedgerDocument,
    choreProbesDocument,
    ciDocument,
    conversationRecordDocument,
    enginePolicyDocument,
    engineStateDocument,
    runtimeInstallsDocument,
    extensionApprovalsDocument,
    extensionEnablementDocument,
    extensionSettingsDocument,
    extensionUpdatePolicyDocument,
    extensionUpdatesDocument,
    extensionUsageDocument,
    hookApprovalsDocument,
    hookRequestsDocument,
    syncEnrollmentsDocument,
    hostSetupSeededDocument,
    issuesDocument,
    loopDesignsDocument,
    loopsDocument,
    needsDocument,
    hostEnrollmentsDocument,
    hostPairConsumedDocument,
    runnerEnrollmentsDocument,
    runnerPairConsumedDocument,
    syncPairConsumedDocument,
    webextEnrollmentsDocument,
    webextPairConsumedDocument,
    peerToolsDocument,
    conversationGrantsDocument,
    personasDocument,
    bundleManifestDocument,
    definitionDocument,
    privacyLedgerDocument,
    privacyShieldDocument,
    privacyVaultDocument,
    pushDocument,
    ruleFiringsDocument,
    runnerIdentityDocument,
    claudeSeatsDocument,
    safetyLogDocument,
    autostartDocument,
    credentialReleasesDocument,
    secretHostGuardsDocument,
    sandboxSecretsDocument,
    secretUsesDocument,
    threadSessionsDocument,
    memberAudienceDocument,
    settingsDocument,
    sharesDocument,
    conversionsDocument,
    issueInstallsDocument,
    webchatInstallsDocument,
    newestRunDocument,
    bootFailureDocument,
    stagedUpdateDocument,
    updateOutcomeDocument,
    updatePreparingDocument,
    skippedUpdateDocument,
    heavyCommandsDocument,
    workspaceIdentityDocument,
    accountUsageDocument,
    modelCooldownsDocument,
    modelRefusalsDocument,
    observedLimitsDocument,
    providerRefusalsDocument,
    usageParksDocument,
    walletLedgerDocument,
    webchatOutboxDocument,
    workflowRunsDocument,
    workflowsDocument,
    dependencyRequestsDocument,
];

// By id, not by the order modules happened to load in: the plan must not depend on an import graph.
export const stateSteps = (): readonly StructuralStep[] =>
    [automationsRelocationStep, pre1308ImportStep, conversationsSchemaStep, landCheckLeftoversStep, pushChecksLeftoversStep, stateRegroupStep, workflowGateTokensStep].toSorted((a, b) => a.id.localeCompare(b.id));
