/* WHETHER A PIECE OF DAEMON STATE TRAVELS — the second thing every state manifest declares.
 *
 * A sandbox's environment is not one directory. `/work` holds the workspace and the daemon's manifests,
 * `/history` holds the real git dirs, the fleet registry and the ledgers, and the container carries the built
 * image and its env. "Export the environment" therefore means walking state that lives in two volumes and
 * deciding, per entry, which of four things it is — and that decision has to be written down beside the entry
 * itself, or the exporter becomes the hand-kept list that workspace-state.ts exists to argue against.
 *
 * So each manifest entry carries a class, and both the bundler and the restorer derive from it. Adding a store
 * without saying whether it travels is a failing coverage test, not a file that silently goes missing from
 * every bundle.
 *
 * The classes are exhaustive on purpose — there is no "unset" — because the failure mode of a default is
 * exactly the one that matters: a credential store added later would inherit `carry` and ride out of the
 * sandbox in a file the owner thought was safe to email.
 */
export type Portability =
    /* Ordinary state. Travels in every bundle. */
    | "carry"
    /* Holds a credential — a provider token, a webhook secret, an ssh key. Travels ONLY when the owner opts
     * in at export, and the bundle records that it did. Never the default. */
    | "secret"
    /* Binds this sandbox to its owner, its browsers or its host: who may drive it, the session-signing secret,
     * push subscriptions, enrollments, certificates. Never travels — the target mints its own, and carrying
     * one would either hand the target's ownership to the source or leave two sandboxes claiming one identity. */
    | "identity"
    /* Regenerated by the target from state that does travel: composed files, caches, indexes, checkouts. Left
     * out for size, not for safety — carrying it would only ship a stale copy of something the daemon rebuilds
     * on its own. */
    | "derived";

// One entry of a state manifest: the path it owns and what happens to it at export. `note` is user-facing —
// the import report prints it beside a skipped entry, so it is written as an instruction to the owner ("log in
// again"), not as a rationale for the next reader. Rationale belongs in a comment on the entry.
export interface StateFile {
    readonly path: string;
    readonly portability: Portability;
    readonly note?: string;
}

/* The entry that owns a path, LONGEST PREFIX FIRST.
 *
 * Manifests may deliberately nest when one subtree has a different lifecycle. First-match resolution would
 * classify the child by whichever entry happened to be listed first, so the specific entry has to win over the
 * general one by construction rather than by list order — the same reason a .gitignore consults its deepest
 * matcher first.
 *
 * Undefined for a path no entry claims. Callers decide what that means: workspace content (including an
 * extension's undeclared output) defaults to `carry`, while unclaimed history machinery defaults to `derived`.
 * The daemon's state-path coverage guard is what prevents one of its own credential stores from relying on the
 * workspace default.
 */
export const stateFileFor = <T extends StateFile>(path: string, files: readonly T[]): T | undefined =>
    files
        .filter((file) => path === file.path || path.startsWith(file.path) || `${path}/` === file.path)
        .reduce<T | undefined>((best, file) => (best === undefined || file.path.length > best.path.length ? file : best), undefined);
