import type { Provider } from "@intentic/engine";
import { z } from "zod";
import { backingSchema, createBackingProvider } from "../core/backing-provider.js";
import { execProbe, stampLabels } from "../core/backing-ssh.js";
import type { SshExecutor } from "../core/ssh.js";
import { sshExecutor } from "../core/ssh.js";

const KIND = "postgres";

const postgresSchema = backingSchema.extend({
    // The superuser password, generated by intentic. Set on first init so TCP connections require a password;
    // per-app roles (minted by the binding provider) authenticate with their own passwords.
    adminPassword: z.string(),
});
type PostgresInputs = z.infer<typeof postgresSchema>;

// A single Postgres service published on the host's internal ip; the named volume survives a pin bump so the
// data persists. The superuser password is interpolated from the write-once .env. Stamped intentic.id=<id>
// so the binding provider can docker-exec into it.
const composeYaml = (parsed: PostgresInputs, id: string, hash: string): string =>
    [
        "services:",
        "  postgres:",
        `    image: ${parsed.image}`,
        "    restart: unless-stopped",
        "    environment: { POSTGRES_USER: postgres, POSTGRES_PASSWORD: $POSTGRES_PASSWORD, POSTGRES_DB: postgres }",
        "    volumes: [ data:/var/lib/postgresql ]",
        `    ports: [ "${parsed.publishPort}:5432" ]`,
        stampLabels(KIND, id, hash, parsed.protect),
        "    healthcheck:",
        "      test: [ CMD-SHELL, pg_isready -U postgres ]",
        "      interval: 10s",
        "      timeout: 5s",
        "      retries: 10",
        "volumes: { data: {} }",
        "",
    ].join("\n");

// A Postgres backing instance (i.want.database). read returns the resource only once the container is up and
// pg_isready passes (so a noop re-derives the deterministic internalHost/port); diff drives an image-pin bump;
// apply is idempotent (compose up -d reconciles, the volume persists). Per-app databases are the binding
// provider's job, not this one's.
export const createPostgresProvider = (executor: SshExecutor = sshExecutor): Provider =>
    createBackingProvider(
        {
            kind: KIND,
            schema: postgresSchema,
            readyTimeoutMs: 120_000,
            outputs: (parsed) => ({ internalHost: parsed.internalIp, port: String(parsed.publishPort) }),
            files: (parsed, id, hash) => ({ "compose.yaml": composeYaml(parsed, id, hash) }),
            // Write-once, deliberately: the superuser password is baked into the data dir on first init and
            // Postgres ignores it thereafter, so re-keying would lock us out of our own database.
            env: (parsed) => [{ key: "POSTGRES_PASSWORD", value: parsed.adminPassword }],
            probe: (_parsed, id) => execProbe(id, "pg_isready -U postgres -q"),
            // One `data` volume, so a renamed node moves its database rather than losing it.
            restamp: true,
        },
        executor,
    );
