import type { Provider } from "@intentic/engine";
import { shellQuote } from "@intentic/sandbox-run/quote";
import { z } from "zod";
import { backingSchema, createBackingProvider } from "../core/backing-provider.js";
import { execProbe, stampLabels } from "../core/backing-ssh.js";
import type { SshExecutor } from "../core/ssh.js";
import { sshExecutor } from "../core/ssh.js";

const KIND = "valkey";

const valkeySchema = backingSchema.extend({
    // The admin password (requirepass), generated by intentic. The binding provider reuses it to run
    // ACL SETUSER for per-app users.
    adminPassword: z.string(),
});
type ValkeyInputs = z.infer<typeof valkeySchema>;

// A single Valkey service published on the host's internal ip. requirepass lives in the mounted valkey.conf
// (write-once, chmod 600) so the secret is not interpolated through a shell command. Stamped intentic.id=<id>
// so the binding provider can docker-exec valkey-cli into it.
const composeYaml = (parsed: ValkeyInputs, id: string, hash: string): string =>
    [
        "services:",
        "  valkey:",
        `    image: ${parsed.image}`,
        "    restart: unless-stopped",
        "    command: [ valkey-server, /etc/valkey/valkey.conf ]",
        "    volumes:",
        "      - data:/data",
        "      - ./valkey.conf:/etc/valkey/valkey.conf:ro",
        `    ports: [ "${parsed.publishPort}:6379" ]`,
        stampLabels(KIND, id, hash, parsed.protect),
        "volumes: { data: {} }",
        "",
    ].join("\n");

// requirepass is a stable generated secret (the same value on every apply), so rewriting this file each time
// is idempotent: no re-key risk, and the binding's ACL users + the appendonly data survive a recreate.
const valkeyConf = (parsed: ValkeyInputs): string => [`requirepass ${parsed.adminPassword}`, "appendonly yes", ""].join("\n");

// A Valkey backing instance (i.want.cache). read returns the resource once the container answers PONG (so a
// noop re-derives internalHost/port); diff drives an image-pin bump; apply is idempotent. Per-app ACL users
// are the binding provider's job.
export const createValkeyProvider = (executor: SshExecutor = sshExecutor): Provider =>
    createBackingProvider(
        {
            kind: KIND,
            schema: valkeySchema,
            readyTimeoutMs: 60_000,
            outputs: (parsed) => ({ internalHost: parsed.internalIp, port: String(parsed.publishPort) }),
            files: (parsed, id, hash) => ({
                "compose.yaml": composeYaml(parsed, id, hash),
                "valkey.conf": { content: valkeyConf(parsed), secret: true },
            }),
            probe: (parsed, id) => execProbe(id, `valkey-cli -a ${shellQuote(parsed.adminPassword)} ping | grep -q PONG`),
            // One `data` volume, so a renamed node moves its appendonly file rather than losing it.
            restamp: true,
        },
        executor,
    );
