import { execFile, spawn } from "node:child_process";
import { setTimeout as sleep } from "node:timers/promises";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";
import { packageRoot, repoRoot } from "@intentic/constants/node";
import { cloudflareApi, forgejoApi, sshExecutor } from "@intentic/providers";
import { deploymentId, deploymentPort } from "@intentic/state-resolver";
import { loadConfig } from "./env.config.js";
import { renderTemplate } from "./lib/templates.js";
import { readGeneratedSecrets } from "./secrets/generated-secrets.js";
import { shellQuote } from "@intentic/sandbox-run/quote";

// ssh2 is CommonJS; `import { utils }` can't resolve under ESM, so load it via createRequire.
const { utils } = createRequire(import.meta.url)("ssh2") as {
    utils: { generateKeyPairSync: (type: string) => { private: string; public: string } };
};

// Persistent local demo of the full intentic flow: boots a long-lived DinD host and drives the real CLI to stand up
// Forgejo/Komodo behind a Cloudflare tunnel and wire the app's CI/CD, then leaves it running. `demo down`/`clear` tear
// it down. Dev harness only, not a shipped command.

const exec = promisify(execFile);
const root = repoRoot(import.meta.url);
const cliRoot = packageRoot(import.meta.url);
const hostContext = join(cliRoot, "node_modules/@intentic/dind-host");
const cliJs = join(cliRoot, "dist/cli.js");
const stateDir = join(root, ".demo");
const stateFile = join(stateDir, "state.json");

const CONTAINER = "intentic-demo-host";
const TUNNEL = "intentic-host"; // resolver's tunnelName(host.id): what cleanup finds it by
const ADMIN = "intentic"; // resolver's adminUsername: the Forgejo/Komodo admin login
const APP = "app";
const ENV = "production";
const APP_BODY = "intentic-demo-live";
const appPort = deploymentPort(deploymentId(APP, ENV));

const config = loadConfig();
const zone = config.cloudflareZone;
const sshPort = config.demo.sshPort;
// Forgejo/Komodo also publish to localhost so the stack is browsable before public URLs are up.
const forgejoPort = config.demo.forgejoPort;
const komodoPort = config.demo.komodoPort;

const GIT_URL = `https://git.${zone}`;
const KOMODO_URL = `https://deploy.${zone}`;
const APP_URL = `https://app.${zone}`;

const log = (message: string): void => {
    process.stdout.write(`${message}\n`);
};

// Routes CLI children's zone lookups through Cloudflare DoH so new records resolve despite local caching.
const dohHook = pathToFileURL(join(cliRoot, "doh-lookup.mjs")).href;
const cliEnv: NodeJS.ProcessEnv = {
    ...process.env,
    DEMO_DOH_ZONE: zone,
    NODE_OPTIONS: `${config.nodeOptions} --import=${dohHook}`.trim(),
};

// Streams a child's output live so the operator can watch progress; rejects the promise on a non-zero exit.
const run = (command: string, args: string[], env: NodeJS.ProcessEnv = process.env): Promise<void> =>
    new Promise((resolve, reject) => {
        const child = spawn(command, args, { cwd: root, env, stdio: ["ignore", "inherit", "inherit"] });
        child.on("error", reject);
        child.on("exit", (code) => {
            if (code === 0) {
                resolve();
            } else {
                reject(new Error(`${command} ${args.join(" ")} exited ${code}`));
            }
        });
    });
const runCli = (...args: string[]): Promise<void> => run(process.execPath, [cliJs, ...args], cliEnv);
const quiet = async (command: string, args: string[]): Promise<boolean> => {
    try {
        await exec(command, args, { maxBuffer: 16 * 1024 * 1024 });
        return true;
    } catch {
        return false;
    }
};

const readToken = async (): Promise<string> => {
    if (config.cloudflareApiToken !== "") {
        return config.cloudflareApiToken.replace(/\\/g, "").trim();
    }
    const envText = await readFile(join(root, "desired-state/.env"), "utf8");
    const match = /^CLOUDFLARE_API_TOKEN=(.*)$/m.exec(envText);
    if (match?.[1] === undefined) {
        throw new Error("CLOUDFLARE_API_TOKEN is not set and was not found in desired-state/.env");
    }
    return match[1].replace(/\\/g, "").trim();
};

const deployConfig = (): string =>
    renderTemplate("demo/deploy.config.ts", { sshPort, app: APP, env: ENV, domain: `app.${zone}`, appPort: String(appPort) });

// Passwords intentic can't invent: Forgejo/Komodo admin passwords are generated by resolve/apply into
// desired-state/.secrets.json, read back here to sign in.
const envFile = (privateKey: string, apiToken: string): string => renderTemplate("demo/env", { privateKey, apiToken });

// A trivial buildable app: busybox httpd serving a known body on $PORT (Komodo sets PORT to appPort).
const DOCKERFILE = renderTemplate("demo/Dockerfile", { appBody: APP_BODY });

const ssh = async (command: string): Promise<string> => {
    const session = await sshExecutor.connect({ address: "127.0.0.1", port: sshPort, user: "root", privateKey });
    try {
        const result = await session.exec(command);
        return `${result.stdout}${result.stderr}`;
    } finally {
        await session.dispose();
    }
};

let privateKey = "";

const up = async (): Promise<void> => {
    const apiToken = await readToken();
    const keys = utils.generateKeyPairSync("ed25519");
    privateKey = keys.private;
    // Filled after the platform apply, from desired-state/.secrets.json.
    let forgejoPassword = "";
    let komodoPassword = "";

    log(`▶ building the demo host image (${CONTAINER}) from @intentic/dind-host …`);
    await run("docker", ["build", "-t", CONTAINER, hostContext]);

    log("▶ starting the persistent Docker-in-Docker host …");
    await quiet("docker", ["rm", "-f", CONTAINER]);
    await run("docker", [
        "run",
        "-d",
        "--privileged",
        // Points dockerd's DNS at Cloudflare so registry-token lookups skip Docker Desktop's negative cache.
        "--dns",
        "1.1.1.1",
        "--dns",
        "1.0.0.1",
        "--name",
        CONTAINER,
        "-e",
        "DOCKER_TLS_CERTDIR=",
        "-p",
        `${sshPort}:22`,
        "-p",
        `${forgejoPort}:3000`,
        "-p",
        `${komodoPort}:9120`,
        CONTAINER,
    ]);

    log("▶ injecting the demo SSH key …");
    for (let i = 0; i < 60 && !(await quiet("docker", ["exec", CONTAINER, "true"])); i++) {
        await sleep(1000);
    }
    await exec("docker", [
        "exec",
        CONTAINER,
        "sh",
        "-c",
        `mkdir -p /root/.ssh && chmod 700 /root/.ssh && printf '%s\\n' ${shellQuote(keys.public)} > /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys`,
    ]);

    log(`▶ waiting for SSH on 127.0.0.1:${sshPort} …`);
    for (let i = 0; ; i++) {
        try {
            await (await sshExecutor.connect({ address: "127.0.0.1", port: sshPort, user: "root", privateKey })).dispose();
            break;
        } catch (error) {
            if (i >= 90) {
                throw new Error(`host SSH never came up: ${String(error)}`, { cause: error });
            }
            await sleep(1000);
        }
    }

    // Uses the repo's own scratch dirs (intent/, desired-state/) so .secrets.json lands where `deploy adopt` reads it.
    const workspace = root;
    const configPath = join(workspace, "intent", "deploy.config.ts");
    const artifactPath = join(workspace, "desired-state", "desired-state.json");

    // Persist enough state up front that `demo down` can always clean up, even if a later step fails.
    await mkdir(stateDir, { recursive: true });
    await writeFile(
        stateFile,
        JSON.stringify(
            {
                zone,
                apiToken,
                container: CONTAINER,
                sshPort,
                urls: { git: GIT_URL, komodo: KOMODO_URL, app: APP_URL },
                local: { git: `http://127.0.0.1:${forgejoPort}`, komodo: `http://127.0.0.1:${komodoPort}` },
            },
            null,
            2,
        ),
    );

    log("▶ scaffolding the intent (deploy init --link) …");
    await runCli("deploy", "init", "--dir", workspace, "--link");
    await writeFile(configPath, deployConfig());
    await writeFile(join(workspace, "desired-state", ".env"), envFile(privateKey, apiToken));

    log("▶ resolve + apply: Forgejo + Komodo + tunnel + the app's CI/CD wiring …");
    await runCli("deploy", "resolve", "--config", configPath, "--out", artifactPath);
    await runCli("deploy", "apply", "--yes", "--artifact", artifactPath, "--maxIterations", "8");

    // Reads back the admin passwords resolve/apply generated, to sign in with what actually bootstrapped the platform.
    const secrets = await readGeneratedSecrets(join(workspace, "desired-state"));
    forgejoPassword = secrets["FORGEJO_ADMIN_PASSWORD"] ?? "";
    komodoPassword = secrets["KOMODO_ADMIN_PASSWORD"] ?? "";

    const running = await ssh("docker ps --format '{{.Names}}'");
    for (const name of ["intentic-forgejo", "intentic-forgejo-runner", "komodo-core"]) {
        if (!running.includes(name)) {
            throw new Error(`platform container "${name}" is not running on the host:\n${running}`);
        }
    }
    log(`✅ platform up, host containers: ${running.split("\n").filter(Boolean).join(", ")}`);

    log("▶ seeding the app repo (intentic/app @ main) with a Dockerfile …");
    let appDeployed = false;
    try {
        await forgejoApi.commitFile({
            baseUrl: `http://127.0.0.1:${forgejoPort}`,
            user: ADMIN,
            password: forgejoPassword,
            owner: ADMIN,
            name: APP,
            branch: "main",
            path: "Dockerfile",
            content: DOCKERFILE,
            message: "seed demo app",
        });
        // intentic only wires CI/CD; the real Dockerfile pushed here triggers the build+deploy Action.
        log(`▶ CI builds + pushes the image and Komodo rolls it out: polling http://127.0.0.1:${appPort} …`);
        const deadline = Date.now() + 5 * 60_000;
        while (!appDeployed && Date.now() < deadline) {
            const hit = (await ssh(`wget -q -T 5 -O- http://127.0.0.1:${appPort} 2>/dev/null || true`)).trim();
            appDeployed = hit.includes(APP_BODY);
            if (!appDeployed) {
                await sleep(2000);
            }
        }
        log(
            appDeployed
                ? `✅ app deployed by CI/CD: serving "${APP_BODY}" on the host`
                : `⚠ app not live yet on :${appPort} (CI/CD may still be running)`,
        );
    } catch (error) {
        log(`⚠ app phase skipped (platform stays up): ${String(error)}`);
    }

    log("");
    log("════════════════════════════════════════════════════════════════════");
    log("  intentic demo is UP and will stay up until you run `pnpm demo:down`");
    log("════════════════════════════════════════════════════════════════════");
    log("  Public (through the Cloudflare tunnel: DNS/edge may take ~1 min):");
    log(`    Forgejo : ${GIT_URL}`);
    log(`    Komodo  : ${KOMODO_URL}`);
    if (appDeployed) {
        log(`    App     : ${APP_URL}`);
    }
    log("  Local (instant, no DNS needed):");
    log(`    Forgejo : http://127.0.0.1:${forgejoPort}`);
    log(`    Komodo  : http://127.0.0.1:${komodoPort}`);
    log("  Admin login (intentic-generated):");
    log(`    user     : ${ADMIN}`);
    log(`    Forgejo pw: ${forgejoPassword}`);
    log(`    Komodo pw : ${komodoPassword}`);
    log(`    (saved in ${join(workspace, "desired-state", ".secrets.json")})`);
    log(`  SSH into the host:  ssh -p ${sshPort} root@127.0.0.1   (key in ${join(workspace, "desired-state", ".env")})`);
    log("  Push the control-plane repos to Forgejo:  pnpm intentic deploy adopt   (once git DNS is live)");
    log("  Stop (reuses tunnel + DNS, fast re-up) :  pnpm demo:down");
    log("  Full teardown (also removes tunnel+DNS):  pnpm demo:clear");
    log("  Note: keep this machine + Docker running; the public URLs share the");
    log("        tunnel name 'intentic-host', so don't run the e2e at the same time.");
    log("════════════════════════════════════════════════════════════════════");
};

interface DemoState {
    readonly zone: string;
    readonly apiToken: string;
}

// Stops the demo without touching Cloudflare: removing the host container kills the connector, but the tunnel and DNS
// stay, so the next `up` reconnects in seconds with no NXDOMAIN caching. `clear` also purges them.
const down = async (): Promise<void> => {
    log(`▶ stopping the demo host container (${CONTAINER}): leaving the Cloudflare tunnel + DNS for a fast re-up …`);
    await quiet("docker", ["rm", "-f", CONTAINER]);
    log("✅ demo stopped. `pnpm demo:up` reconnects in seconds (tunnel + DNS reused); `pnpm demo:clear` tears down Cloudflare too.");
};

// Full teardown: removes the host container, purges the Cloudflare tunnel and DNS records this demo created, and drops
// the local state.
const clear = async (): Promise<void> => {
    const state: Partial<DemoState> = await readFile(stateFile, "utf8")
        .then((text) => JSON.parse(text) as DemoState)
        .catch(() => ({}));
    const zoneName = state.zone ?? zone;
    const apiToken = state.apiToken ?? (await readToken());

    log(`▶ removing the demo host container (${CONTAINER}) …`);
    await quiet("docker", ["rm", "-f", CONTAINER]);

    log("▶ deleting the Cloudflare tunnel + DNS records …");
    // Account and zone id come from resolving the zone name; teardown needs only the name and token.
    const cfZone = await cloudflareApi.getZone({ apiToken, zone: zoneName }).catch(() => undefined);
    if (cfZone !== undefined) {
        const tunnel = await cloudflareApi.findTunnel({ accountId: cfZone.accountId, apiToken, name: TUNNEL }).catch(() => undefined);
        if (tunnel !== undefined) {
            await fetch(`https://api.cloudflare.com/client/v4/accounts/${cfZone.accountId}/cfd_tunnel/${tunnel.id}/connections`, {
                method: "DELETE",
                headers: { Authorization: `Bearer ${apiToken}` },
            }).catch(() => {});
            await cloudflareApi
                .deleteTunnel({ accountId: cfZone.accountId, apiToken, tunnelId: tunnel.id })
                .catch((error) => log(`  tunnel: ${String(error)}`));
        }
        for (const name of [`git.${zoneName}`, `deploy.${zoneName}`, `app.${zoneName}`]) {
            const record = await cloudflareApi.findDnsRecord({ apiToken, zoneId: cfZone.id, name }).catch(() => undefined);
            if (record !== undefined) {
                await cloudflareApi
                    .deleteDnsRecord({ apiToken, zoneId: cfZone.id, recordId: record.id })
                    .catch((error) => log(`  dns ${name}: ${String(error)}`));
            }
        }
    }

    // intent/ and desired-state/ hold .secrets.json; left in place so `deploy adopt` still works.
    await rm(stateDir, { recursive: true, force: true }).catch(() => {});
    log("✅ demo cleared: host container, tunnel, and DNS records removed (intent/ + desired-state/ kept).");
};

const mode = process.argv[2];
if (mode === "up") {
    await up();
} else if (mode === "down") {
    await down();
} else if (mode === "clear" || mode === "clean") {
    await clear();
} else {
    log("usage: demo <up|down|clear>");
    process.exit(1);
}
