// Codegen: emits src/icons/iconData.generated.ts — a trimmed Iconify collection holding only the ~106 icons
// the app actually uses, so installUi() can addCollection() it and every <Icon> resolves offline. The full
// @iconify-json/ri set is thousands of icons; we ship only what ICONS references.
// Run with `bun run scripts/generateIconData.ts` (or `pnpm --filter @intentic/ui generate:icons`)
// whenever ICONS changes. Commit the generated file.

import { getIcons } from "@iconify/utils";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ICONS } from "../src/icons/iconSets.js";

// The one set the app draws from. An id naming any other prefix fails here rather than rendering as a hole in
// the running app — which is what an unbundled icon looks like: Iconify draws nothing and says nothing.
const PREFIX = "ri";

const names = new Set<string>();
for (const id of Object.values(ICONS)) {
    const [prefix, name] = id.split(":");
    if (prefix !== PREFIX || !name) {
        throw new Error(`Icon id must be "${PREFIX}:<name>" — got "${id}". Register another loader if a second set is ever wanted.`);
    }
    names.add(name);
}

const full = (await import("@iconify-json/ri/icons.json", { with: { type: "json" } })).default;
const trimmed = getIcons(full, [...names]);
if (!trimmed) {
    throw new Error(`getIcons returned nothing for prefix "${PREFIX}".`);
}
const missing = [...names].filter((n) => !(n in trimmed.icons) && !(n in (trimmed.aliases ?? {})));
if (missing.length > 0) {
    throw new Error(`Missing icons in "${PREFIX}": ${missing.join(", ")}`);
}

const out = `// GENERATED by scripts/generateIconData.ts — do not edit. Run \`pnpm --filter @intentic/ui generate:icons\`.
// The trimmed Iconify collection (only the icons ICONS references), registered via addCollection() in installUi().
import type { IconifyJSON } from "@iconify/types";

export const BUNDLED_ICONS: IconifyJSON[] = ${JSON.stringify([trimmed])};
`;

const outPath = fileURLToPath(new URL("../src/icons/iconData.generated.ts", import.meta.url));
writeFileSync(outPath, out);
console.log(`Wrote ${outPath} — ${Object.keys(trimmed.icons).length} icons.`);
