// Codegen: emits src/icons/iconData.generated.ts — trimmed Iconify collections holding only the ~90 icons
// the app actually uses (grouped by real prefix), so installUi() can addCollection() them and every <Icon>
// resolves offline. Full @iconify-json sets are thousands of icons; we ship only what ICON_SETS references.
// Run with `bun run scripts/generateIconData.ts` (or `pnpm --filter @intentic-app/ui generate:icons`)
// whenever ICON_SETS changes. Commit the generated file.

import { getIcons } from "@iconify/utils";
import type { IconifyJSON } from "@iconify/types";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ICON_SETS } from "../src/icons/iconSets.js";

// The full sets we can pull from, keyed by Iconify prefix (the part before the ':' in every mapped id).
const FULL_SETS: Record<string, () => Promise<{ default: IconifyJSON }>> = {
    ph: () => import("@iconify-json/ph/icons.json", { with: { type: "json" } }),
    solar: () => import("@iconify-json/solar/icons.json", { with: { type: "json" } }),
    ri: () => import("@iconify-json/ri/icons.json", { with: { type: "json" } }),
    hugeicons: () => import("@iconify-json/hugeicons/icons.json", { with: { type: "json" } }),
    prime: () => import("@iconify-json/prime/icons.json", { with: { type: "json" } }),
};

// Collect the bare icon names used per prefix across every set (the primeicons set's `gitlab: "ph:…"`
// fallback lands under `ph` automatically — we group by the id's own prefix, not by set name).
const namesByPrefix: Record<string, Set<string>> = {};
for (const set of Object.values(ICON_SETS)) {
    for (const id of Object.values(set)) {
        const [prefix, name] = id.split(":");
        if (!prefix || !name) {
            throw new Error(`Malformed Iconify id (expected "prefix:name"): ${id}`);
        }
        (namesByPrefix[prefix] ??= new Set()).add(name);
    }
}

const collections: IconifyJSON[] = [];
for (const [prefix, names] of Object.entries(namesByPrefix)) {
    const loader = FULL_SETS[prefix];
    if (!loader) {
        throw new Error(`No @iconify-json source registered for prefix "${prefix}" — add it to FULL_SETS.`);
    }
    const full = (await loader()).default;
    const trimmed = getIcons(full, [...names]);
    if (!trimmed) {
        throw new Error(`getIcons returned nothing for prefix "${prefix}".`);
    }
    const missing = [...names].filter((n) => !(n in trimmed.icons) && !(n in (trimmed.aliases ?? {})));
    if (missing.length > 0) {
        throw new Error(`Missing icons in "${prefix}": ${missing.join(", ")}`);
    }
    collections.push(trimmed);
}

const out = `// GENERATED by scripts/generateIconData.ts — do not edit. Run \`pnpm --filter @intentic-app/ui generate:icons\`.
// Trimmed Iconify collections (only the icons ICON_SETS references), registered via addCollection() in installUi().
import type { IconifyJSON } from "@iconify/types";

export const BUNDLED_ICONS: IconifyJSON[] = ${JSON.stringify(collections)};
`;

const outPath = fileURLToPath(new URL("../src/icons/iconData.generated.ts", import.meta.url));
writeFileSync(outPath, out);
const total = collections.reduce((n, c) => n + Object.keys(c.icons).length, 0);
console.log(`Wrote ${outPath} — ${collections.length} collections, ${total} icons.`);
