// Throwaway: same logic as generateIconData.ts, but imports the .ts source explicitly so plain `node`
// (which, unlike bun, won't rewrite a .js specifier to .ts) can run it. Delete after use.
import { getIcons } from "@iconify/utils";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ICON_SETS } from "../src/icons/iconSets.ts";

const FULL_SETS = {
    ph: () => import("@iconify-json/ph/icons.json", { with: { type: "json" } }),
    solar: () => import("@iconify-json/solar/icons.json", { with: { type: "json" } }),
    ri: () => import("@iconify-json/ri/icons.json", { with: { type: "json" } }),
    hugeicons: () => import("@iconify-json/hugeicons/icons.json", { with: { type: "json" } }),
    prime: () => import("@iconify-json/prime/icons.json", { with: { type: "json" } }),
};

const namesByPrefix = {};
for (const set of Object.values(ICON_SETS)) {
    for (const id of Object.values(set)) {
        const [prefix, name] = id.split(":");
        if (!prefix || !name) {
            throw new Error(`Malformed Iconify id: ${id}`);
        }
        (namesByPrefix[prefix] ??= new Set()).add(name);
    }
}

const collections = [];
for (const [prefix, names] of Object.entries(namesByPrefix)) {
    const loader = FULL_SETS[prefix];
    if (!loader) {
        throw new Error(`No source for prefix "${prefix}".`);
    }
    const full = (await loader()).default;
    const trimmed = getIcons(full, [...names]);
    if (!trimmed) {
        throw new Error(`getIcons returned nothing for "${prefix}".`);
    }
    const missing = [...names].filter((n) => !(n in trimmed.icons) && !(n in (trimmed.aliases ?? {})));
    if (missing.length > 0) {
        throw new Error(`Missing icons in "${prefix}": ${missing.join(", ")}`);
    }
    collections.push(trimmed);
}

const out = `// GENERATED by scripts/generateIconData.ts — do not edit. Run \`pnpm --filter @intentic-app/ui generate:icons\`.
// Trimmed Iconify collections (only the icons ICON_SETS references), registered via addCollection() in installUi().
import type { IconifyJSON } from "@iconify/types";

export const BUNDLED_ICONS: IconifyJSON[] = ${JSON.stringify(collections)};
`;

const outPath = fileURLToPath(new URL("../src/icons/iconData.generated.ts", import.meta.url));
writeFileSync(outPath, out);
const total = collections.reduce((n, c) => n + Object.keys(c.icons).length, 0);
console.log(`Wrote ${outPath} — ${collections.length} collections, ${total} icons.`);
