import type { IndexDb } from "../store/db.js";
import type { RankedGroup, RankedHit, SymbolRow } from "../types.js";

// `iq map` — the repo as a ranked skeleton: which files matter, and what each one exposes. This is the
// orientation artifact a reader (or a model with a fresh context) wants before touching anything, and the file
// tree is a poor substitute — it sorts alphabetically, which correlates with nothing.
//
// Importance is PageRank over the import graph: an edge A→B means A imports B, so rank flows from importers to
// the modules they depend on, and being imported by a central file counts for more than by a leaf.
//
// Edges are IMPORTS, not symbol-name matches. Name matching was tried first and has a ceiling that no weighting
// fixes: text cannot tell a reference from a coincidence, so a module exporting ordinary words (`App`, `Host`,
// `Repo`) collects mentions from the whole repo and tops the list. An import statement is unambiguous.

const DAMPING = 0.85;
const ITERATIONS = 20;

interface MapSymbol {
    readonly fileId: number;
    readonly path: string;
    readonly name: string;
    readonly kind: SymbolRow["kind"];
    readonly line: number;
    readonly signature: string;
}

// Generated files are not part of the authored surface a map describes, and they distort the ranking: a
// re-export shim duplicates a whole library's vocabulary, so everything appears to depend on it. Both halves of
// the test are conventions, not guesses about one repo — the `@generated` marker and Go's standardized
// `Code generated ... DO NOT EDIT.` banner, plus the `generated/` dir and `*.generated.*` suffix.
const GENERATED_PATH = /(^|\/)generated\/|\.generated\./i;
const GENERATED_BANNER = /@generated\b|\bdo not edit\b|\bauto-?generated\b|\bgenerated by\b/i;
const BANNER_LINES = 5;

// First chunk per file — where a generated banner sits, and where a package.json's "name" is.
const fileHeads = (db: IndexDb): Map<number, string> =>
    new Map(
        db
            .all("SELECT file_id, text FROM chunks WHERE id IN (SELECT MIN(id) FROM chunks GROUP BY file_id)")
            .map((row) => [Number(row["file_id"]), String(row["text"] ?? "")]),
    );

const exportedSymbols = (db: IndexDb, allowed: ReadonlySet<string>): MapSymbol[] =>
    db
        .all(
            `SELECT f.id AS file_id, f.path, s.name, s.kind, s.line, s.signature
             FROM symbols s JOIN files f ON f.id = s.file_id
             WHERE s.exported = 1 ORDER BY f.path, s.line`,
        )
        .map((row) => ({
            fileId: Number(row["file_id"]),
            path: row["path"] as string,
            name: row["name"] as string,
            kind: row["kind"] as SymbolRow["kind"],
            line: Number(row["line"]),
            signature: row["signature"] as string,
        }))
        .filter((symbol) => allowed.has(symbol.path));

const dirOf = (path: string): string => path.slice(0, Math.max(0, path.lastIndexOf("/")));

// Resolve `.`/`..` segments in an already-joined path.
const normalize = (path: string): string => {
    const parts: string[] = [];
    for (const segment of path.split("/")) {
        if (segment === "" || segment === ".") {
            continue;
        }
        if (segment === "..") {
            parts.pop();
            continue;
        }
        parts.push(segment);
    }
    return parts.join("/");
};

// TypeScript's ESM rule means source imports the EMITTED name: `./widget.js` is written in a file whose real
// neighbour is `widget.ts`. Missing that maps a TS monorepo to an empty graph, so the .js→.ts rewrites come
// first, ahead of the extensionless and directory-index forms.
const CANDIDATE_SUFFIXES = [".ts", ".tsx", ".mts", ".js", ".jsx", ".mjs", ".vue", ".py", ".go", ".rs", ".java"];
const INDEX_BASES = ["/index", "/main", "/mod"];

const candidatesFor = (base: string): string[] => {
    const candidates = [base];
    const jsLike = /\.(js|jsx|mjs|cjs)$/.exec(base);
    if (jsLike !== null) {
        const stem = base.slice(0, -jsLike[0].length);
        candidates.push(`${stem}.ts`, `${stem}.tsx`, `${stem}.mts`);
    }
    for (const suffix of CANDIDATE_SUFFIXES) {
        candidates.push(`${base}${suffix}`);
    }
    for (const indexBase of INDEX_BASES) {
        for (const suffix of CANDIDATE_SUFFIXES) {
            candidates.push(`${base}${indexBase}${suffix}`);
        }
    }
    return candidates;
};

// Workspace package name → its directory, read from each package.json's "name". Lets a cross-package import
// (`@intentic/sdk`) resolve to that package's entry file — without it the graph fragments into one island per
// package, which in a monorepo loses exactly the structure the map exists to show.
const packageDirs = (db: IndexDb, heads: ReadonlyMap<number, string>): Map<string, string> => {
    const dirs = new Map<string, string>();
    for (const row of db.all("SELECT id, path FROM files WHERE path LIKE '%package.json'")) {
        const name = /"name"\s*:\s*"([^"]+)"/.exec(heads.get(Number(row["id"])) ?? "")?.[1];
        if (name !== undefined) {
            dirs.set(name, dirOf(row["path"] as string));
        }
    }
    return dirs;
};

const resolveSpecifier = (
    specifier: string,
    fromPath: string,
    known: ReadonlySet<string>,
    packages: ReadonlyMap<string, string>,
): string | undefined => {
    const tryAll = (base: string): string | undefined => candidatesFor(base).find((candidate) => known.has(candidate));
    if (specifier.startsWith(".")) {
        return tryAll(normalize(`${dirOf(fromPath)}/${specifier}`));
    }
    // Longest package name wins, so `@scope/pkg/sub` prefers `@scope/pkg` over a shorter `@scope` entry.
    const owner = [...packages.keys()]
        .filter((name) => specifier === name || specifier.startsWith(`${name}/`))
        .toSorted((a, b) => b.length - a.length)[0];
    if (owner === undefined) {
        return undefined;
    }
    const dir = packages.get(owner)!;
    const subpath = specifier.slice(owner.length);
    return tryAll(normalize(`${dir}${subpath}`)) ?? tryAll(normalize(`${dir}/src${subpath}`));
};

const importGraph = (db: IndexDb, pathsById: ReadonlyMap<number, string>, packages: ReadonlyMap<string, string>): Map<number, Set<number>> => {
    const idByPath = new Map([...pathsById].map(([id, path]) => [path, id] as const));
    const known = new Set(idByPath.keys());
    const edges = new Map<number, Set<number>>();
    for (const row of db.all("SELECT file_id, specifier FROM imports")) {
        const from = Number(row["file_id"]);
        const fromPath = pathsById.get(from);
        if (fromPath === undefined) {
            continue;
        }
        const resolved = resolveSpecifier(row["specifier"] as string, fromPath, known, packages);
        // Unresolved specifiers are the common case (node_modules, stdlib) and are simply not edges.
        if (resolved === undefined || resolved === fromPath) {
            continue;
        }
        const out = edges.get(from) ?? new Set<number>();
        out.add(idByPath.get(resolved)!);
        edges.set(from, out);
    }
    return edges;
};

const pageRank = (nodes: ReadonlySet<number>, edges: ReadonlyMap<number, Set<number>>): Map<number, number> => {
    const count = nodes.size;
    let rank = new Map([...nodes].map((node) => [node, 1 / count]));
    for (let iteration = 0; iteration < ITERATIONS; iteration++) {
        const next = new Map([...nodes].map((node) => [node, 0]));
        // Files that import nothing would leak their rank out of the system; spreading it uniformly is the
        // standard fix and keeps the ranks a true distribution.
        let dangling = 0;
        for (const [node, value] of rank) {
            const out = edges.get(node);
            if (out === undefined || out.size === 0) {
                dangling += value;
                continue;
            }
            for (const to of out) {
                next.set(to, (next.get(to) ?? 0) + value / out.size);
            }
        }
        const base = (1 - DAMPING) / count + (DAMPING * dangling) / count;
        rank = new Map([...next].map(([node, value]) => [node, base + DAMPING * value]));
    }
    return rank;
};

export const repoMap = (db: IndexDb, allowed: ReadonlySet<string>): RankedGroup[] => {
    const heads = fileHeads(db);
    // Every indexed file in scope is a graph node, including ones that export nothing — an entry point that only
    // imports still pushes importance into what it uses. Only files with something to show get rendered.
    const pathsById = new Map(
        db
            .all("SELECT id, path FROM files")
            .map((row) => [Number(row["id"]), row["path"] as string] as const)
            .filter(([, path]) => allowed.has(path)),
    );
    if (pathsById.size === 0) {
        return [];
    }
    const rank = pageRank(new Set(pathsById.keys()), importGraph(db, pathsById, packageDirs(db, heads)));

    const isGenerated = (fileId: number, path: string): boolean =>
        GENERATED_PATH.test(path) || GENERATED_BANNER.test((heads.get(fileId) ?? "").split("\n", BANNER_LINES).join("\n"));

    const byFile = new Map<number, MapSymbol[]>();
    for (const symbol of exportedSymbols(db, allowed)) {
        if (isGenerated(symbol.fileId, symbol.path)) {
            continue;
        }
        const existing = byFile.get(symbol.fileId);
        if (existing === undefined) {
            byFile.set(symbol.fileId, [symbol]);
        } else {
            existing.push(symbol);
        }
    }
    return [...byFile.entries()]
        .map(([fileId, fileSymbols]) => ({ fileSymbols, rank: rank.get(fileId) ?? 0 }))
        .toSorted((a, b) => b.rank - a.rank || (a.fileSymbols[0]!.path < b.fileSymbols[0]!.path ? -1 : 1))
        .map((entry, position) => {
            const score = 1 / (position + 1);
            const hits: RankedHit[] = entry.fileSymbols.map((symbol) => ({
                path: symbol.path,
                line: symbol.line,
                text: symbol.signature,
                tags: [{ kind: "def" as const }],
                score,
            }));
            return { path: entry.fileSymbols[0]!.path, score, hits };
        });
};
