import { ACTION_GLYPHS } from "./actionGlyphs.js";
import { NAVIGATION_GLYPHS } from "./navigationGlyphs.js";
import { OBJECT_GLYPHS } from "./objectGlyphs.js";
import { STATUS_GLYPHS } from "./statusGlyphs.js";
import { BRAND_GLYPHS } from "./brandGlyphs.js";
import { CONTROL_GLYPHS } from "./controlGlyphs.js";
import { EDITOR_GLYPHS } from "./editorGlyphs.js";
import type { Glyph } from "./glyph.js";

// Native SVG drawings for the editor, extensions and shared views.
export const ICONS = {
    ...CONTROL_GLYPHS,
    ...EDITOR_GLYPHS,
    "align-left": ACTION_GLYPHS[`align-left`],
    "angle-right": ACTION_GLYPHS[`chevron-right`],
    approvals: NAVIGATION_GLYPHS[`approvals`],
    "arrow-circle-up": ACTION_GLYPHS[`arrow-circle-up`],
    "arrow-down-left": ACTION_GLYPHS[`arrow-down-left`],
    "arrow-left": ACTION_GLYPHS[`arrow-left`],
    "arrow-right": ACTION_GLYPHS[`arrow-right`],
    "arrow-up-right": ACTION_GLYPHS[`arrow-up-right`],
    "arrows-h": ACTION_GLYPHS[`arrows-h`],
    automations: NAVIGATION_GLYPHS[`automations`],
    backward: ACTION_GLYPHS[`backward`],
    bars: NAVIGATION_GLYPHS[`bars`],
    bolt: STATUS_GLYPHS[`bolt`],
    book: NAVIGATION_GLYPHS[`book`],
    box: OBJECT_GLYPHS[`box`],
    boxes: OBJECT_GLYPHS[`boxes`],
    browsers: NAVIGATION_GLYPHS[`browsers`],
    camera: OBJECT_GLYPHS[`camera`],
    check: STATUS_GLYPHS[`check`],
    "check-circle": STATUS_GLYPHS[`check-circle`],
    "check-square": STATUS_GLYPHS[`check-square`],
    "chevron-down": ACTION_GLYPHS[`chevron-down`],
    "chevron-right": ACTION_GLYPHS[`chevron-right`],
    "chevron-up": ACTION_GLYPHS[`chevron-up`],
    circle: STATUS_GLYPHS[`circle`],
    "circle-fill": STATUS_GLYPHS[`circle-fill`],
    clock: STATUS_GLYPHS[`clock`],
    clone: ACTION_GLYPHS[`copy`],
    cloud: OBJECT_GLYPHS[`cloud`],
    "cloud-upload": OBJECT_GLYPHS[`cloud-upload`],
    code: OBJECT_GLYPHS[`code`],
    cog: OBJECT_GLYPHS[`cog`],
    "collapse-all": ACTION_GLYPHS[`collapse-all`],
    comments: NAVIGATION_GLYPHS[`comments`],
    compress: ACTION_GLYPHS[`compress`],
    copy: ACTION_GLYPHS[`copy`],
    cpu: OBJECT_GLYPHS[`cpu`],
    "credit-card": OBJECT_GLYPHS[`credit-card`],
    database: OBJECT_GLYPHS[`database`],
    deployments: NAVIGATION_GLYPHS[`deployments`],
    desktop: OBJECT_GLYPHS[`desktop`],
    download: ACTION_GLYPHS[`download`],
    ellipsis: NAVIGATION_GLYPHS[`ellipsis`],
    envelope: OBJECT_GLYPHS[`envelope`],
    eraser: ACTION_GLYPHS[`eraser`],
    "exclamation-circle": STATUS_GLYPHS[`exclamation-circle`],
    "exclamation-triangle": NAVIGATION_GLYPHS[`exclamation-triangle`],
    expand: ACTION_GLYPHS[`expand`],
    extensions: OBJECT_GLYPHS[`extensions`],
    "external-link": ACTION_GLYPHS[`external-link`],
    eye: NAVIGATION_GLYPHS[`eye`],
    "eye-slash": ACTION_GLYPHS[`eye-slash`],
    file: OBJECT_GLYPHS[`file`],
    "file-edit": OBJECT_GLYPHS[`file-edit`],
    "file-pdf": OBJECT_GLYPHS[`file-pdf`],
    "file-tree": OBJECT_GLYPHS[`file-tree`],
    filter: ACTION_GLYPHS[`filter`],
    folder: NAVIGATION_GLYPHS[`folder`],
    "folder-open": OBJECT_GLYPHS[`folder-open`],
    fork: ACTION_GLYPHS[`fork`],
    forward: ACTION_GLYPHS[`forward`],
    gift: OBJECT_GLYPHS[`gift`],
    github: BRAND_GLYPHS[`github`],
    gitlab: BRAND_GLYPHS[`gitlab`],
    globe: OBJECT_GLYPHS[`globe`],
    google: BRAND_GLYPHS[`google`],
    hammer: OBJECT_GLYPHS[`hammer`],
    history: STATUS_GLYPHS[`history`],
    image: OBJECT_GLYPHS[`image`],
    "info-circle": STATUS_GLYPHS[`info-circle`],
    infrastructure: NAVIGATION_GLYPHS[`infrastructure`],
    key: OBJECT_GLYPHS[`key`],
    knowledge: OBJECT_GLYPHS[`knowledge`],
    "layout-left": ACTION_GLYPHS[`layout-left`],
    link: ACTION_GLYPHS[`link`],
    "link-broken": ACTION_GLYPHS[`link-broken`],
    "list-check": NAVIGATION_GLYPHS[`list-check`],
    lock: STATUS_GLYPHS[`lock`],
    maintenance: NAVIGATION_GLYPHS[`maintenance`],
    microphone: OBJECT_GLYPHS[`microphone`],
    moon: STATUS_GLYPHS[`moon`],
    palette: OBJECT_GLYPHS[`palette`],
    paperclip: OBJECT_GLYPHS[`paperclip`],
    pause: ACTION_GLYPHS[`pause`],
    pencil: ACTION_GLYPHS[`pencil`],
    "picture-in-picture": ACTION_GLYPHS[`picture-in-picture`],
    pin: ACTION_GLYPHS[`pin`],
    pipelines: NAVIGATION_GLYPHS[`pipelines`],
    play: ACTION_GLYPHS[`play`],
    plus: NAVIGATION_GLYPHS[`plus`],
    "plus-circle": STATUS_GLYPHS[`plus-circle`],
    ports: NAVIGATION_GLYPHS[`ports`],
    "question-circle": STATUS_GLYPHS[`question-circle`],
    refresh: ACTION_GLYPHS[`refresh`],
    repeat: ACTION_GLYPHS[`repeat`],
    robot: NAVIGATION_GLYPHS[`robot`],
    save: OBJECT_GLYPHS[`save`],
    search: ACTION_GLYPHS[`search`],
    send: ACTION_GLYPHS[`send`],
    server: OBJECT_GLYPHS[`server`],
    shield: STATUS_GLYPHS[`shield`],
    "sign-in": ACTION_GLYPHS[`sign-in`],
    "sign-out": ACTION_GLYPHS[`sign-out`],
    sitemap: NAVIGATION_GLYPHS[`sitemap`],
    slack: BRAND_GLYPHS[`slack`],
    "sliders-h": ACTION_GLYPHS[`sliders-h`],
    "sort-desc": ACTION_GLYPHS[`sort-desc`],
    sparkles: STATUS_GLYPHS[`sparkles`],
    spinner: STATUS_GLYPHS[`spinner`],
    "split-columns": ACTION_GLYPHS[`split-columns`],
    square: STATUS_GLYPHS[`square`],
    star: STATUS_GLYPHS[`star`],
    "star-fill": STATUS_GLYPHS[`star-fill`],
    stop: STATUS_GLYPHS[`stop`],
    subagents: NAVIGATION_GLYPHS[`subagents`],
    sun: STATUS_GLYPHS[`sun`],
    sync: ACTION_GLYPHS[`refresh`],
    terminal: NAVIGATION_GLYPHS[`terminal`],
    "th-large": OBJECT_GLYPHS[`th-large`],
    times: ACTION_GLYPHS[`times`],
    trash: ACTION_GLYPHS[`trash`],
    undo: ACTION_GLYPHS[`undo`],
    unlock: STATUS_GLYPHS[`unlock`],
    upload: ACTION_GLYPHS[`upload`],
    usage: OBJECT_GLYPHS[`usage`],
    user: OBJECT_GLYPHS[`user`],
    users: OBJECT_GLYPHS[`users`],
    "volume-off": STATUS_GLYPHS[`volume-off`],
    "volume-up": STATUS_GLYPHS[`volume-up`],
    vpn: NAVIGATION_GLYPHS[`vpn`],
    "wave-pulse": NAVIGATION_GLYPHS[`wave-pulse`],
    wifi: STATUS_GLYPHS[`wifi`],
    "window-maximize": ACTION_GLYPHS[`expand`],
    "window-minimize": ACTION_GLYPHS[`compress`],
    wrench: OBJECT_GLYPHS[`wrench`],
} satisfies Record<string, Glyph>;

export type IconName = keyof typeof ICONS;

/** Extension APIs accept open strings. An unknown name must fall back instead of drawing a blank. */
export const isIconName = (name: string): name is IconName => Object.hasOwn(ICONS, name);

/** Views choose by subject, so their navigation mark is the same in the rail, menus and hub indexes. */
const AREA_ICONS: Readonly<Record<string, IconName>> = {
    chat: `comments`,
    agents: `robot`,
    workspace: `folder`,
    preview: `eye`,
    approvals: `approvals`,
    acceptance: `list-check`,
    pipelines: `pipelines`,
    deployments: `deployments`,
    maintenance: `maintenance`,
    workflows: `sitemap`,
    automations: `automations`,
    documentation: `book`,
    infrastructure: `infrastructure`,
    "live-status": `wave-pulse`,
    browsers: `browsers`,
    subagents: `subagents`,
    terminal: `terminal`,
    vpn: `vpn`,
    ports: `ports`,
    capabilities: `plus`,
    more: `ellipsis`,
    menu: `bars`,
    issues: `exclamation-triangle`,
    activity: `wave-pulse`,
    public: `cloud-upload`,
    knowledge: `knowledge`,
    overview: `th-large`,
    usage: `usage`,
    environment: `box`,
    secrets: `key`,
    agent: `robot`,
    extensions: `extensions`,
    access: `shield`,
    personas: `user`,
    devices: `desktop`,
};

export const areaIcon = (area: string, fallback?: IconName): IconName | undefined =>
    Object.hasOwn(AREA_ICONS, area) ? AREA_ICONS[area] : fallback !== undefined && isIconName(fallback) ? fallback : undefined;
