// The app's icon vocabulary and how each name resolves in every switchable set. Keys are the stable
// semantic names (the old PrimeIcons suffixes, verbatim); values are Iconify ids. The active set is
// chosen in Settings (useIconSet) so all sets can be compared live in the running app.
//
// Every id referenced here is bundled offline: scripts/generateIconData.ts trims the used icons out of the
// full @iconify-json sets into src/icons/iconData.generated.ts, which installUi() registers via addCollection.
// So no runtime Iconify API fetch — all five sets stay available for the Settings switcher. Regenerate
// (pnpm --filter @intentic-app/ui generate:icons) whenever these mappings change.
//
// `primeicons` is the original set, kept as a baseline for comparison — rendered through the same
// Iconify pipeline via the `prime:` collection (no font/CSS dependency). Iconify's `prime` snapshot
// lacks `gitlab`, so that one name falls back to a monochrome Phosphor logo.

export type IconName =
    | "align-left"
    | "angle-right"
    | "arrow-circle-up"
    | "arrow-down-left"
    | "arrow-left"
    | "arrow-right"
    | "arrow-up-right"
    | "arrows-h"
    | "backward"
    | "bars"
    | "bolt"
    | "box"
    | "check"
    | "check-circle"
    | "check-square"
    | "chevron-down"
    | "chevron-right"
    | "chevron-up"
    | "circle"
    | "circle-fill"
    | "clock"
    | "clone"
    | "cloud"
    | "cloud-upload"
    | "code"
    | "cog"
    | "collapse-all"
    | "comments"
    | "compress"
    | "copy"
    | "credit-card"
    | "database"
    | "desktop"
    | "download"
    | "envelope"
    | "eraser"
    | "exclamation-circle"
    | "exclamation-triangle"
    | "expand"
    | "external-link"
    | "eye"
    | "eye-slash"
    | "file"
    | "file-edit"
    | "file-pdf"
    | "folder"
    | "folder-open"
    | "forward"
    | "github"
    | "gitlab"
    | "globe"
    | "google"
    | "history"
    | "image"
    | "info-circle"
    | "key"
    | "link"
    | "list-check"
    | "lock"
    | "microphone"
    | "moon"
    | "palette"
    | "paperclip"
    | "pause"
    | "pencil"
    | "picture-in-picture"
    | "play"
    | "plus"
    | "plus-circle"
    | "question-circle"
    | "refresh"
    | "repeat"
    | "save"
    | "search"
    | "send"
    | "server"
    | "shield"
    | "sign-in"
    | "sign-out"
    | "sitemap"
    | "sliders-h"
    | "sparkles"
    | "spinner"
    | "square"
    | "star"
    | "star-fill"
    | "stop"
    | "sun"
    | "sync"
    | "th-large"
    | "times"
    | "trash"
    | "undo"
    | "unlock"
    | "upload"
    | "user"
    | "users"
    | "volume-off"
    | "volume-up"
    | "wave-pulse"
    | "wifi"
    | "window-maximize"
    | "window-minimize";

export type IconSet = "phosphor" | "solar" | "remix" | "hugeicons" | "primeicons";

export const iconSets: IconSet[] = ["phosphor", "solar", "remix", "hugeicons", "primeicons"];

export const ICON_SETS: Record<IconSet, Record<IconName, string>> = {
    phosphor: {
        "align-left": "ph:text-align-left",
        "angle-right": "ph:caret-right",
        "arrow-circle-up": "ph:arrow-circle-up",
        "arrow-down-left": "ph:arrow-down-left",
        "arrow-left": "ph:arrow-left",
        "arrow-right": "ph:arrow-right",
        "arrow-up-right": "ph:arrow-up-right",
        "arrows-h": "ph:arrows-horizontal",
        bars: "ph:list",
        bolt: "ph:lightning",
        box: "ph:package",
        check: "ph:check",
        "check-circle": "ph:check-circle",
        "check-square": "ph:check-square",
        "chevron-down": "ph:caret-down",
        "chevron-right": "ph:caret-right",
        "chevron-up": "ph:caret-up",
        circle: "ph:circle",
        "circle-fill": "ph:circle-fill",
        clock: "ph:clock",
        clone: "ph:copy",
        cloud: "ph:cloud",
        "cloud-upload": "ph:cloud-arrow-up",
        code: "ph:code",
        cog: "ph:gear",
        "collapse-all": "ph:arrows-in-line-vertical",
        comments: "ph:chat",
        copy: "ph:copy",
        "credit-card": "ph:credit-card",
        database: "ph:database",
        desktop: "ph:monitor",
        download: "ph:download-simple",
        envelope: "ph:envelope",
        eraser: "ph:eraser",
        "exclamation-circle": "ph:warning-circle",
        "exclamation-triangle": "ph:warning",
        "external-link": "ph:arrow-square-out",
        eye: "ph:eye",
        "eye-slash": "ph:eye-closed",
        file: "ph:file",
        "file-edit": "ph:note-pencil",
        "file-pdf": "ph:file-pdf",
        folder: "ph:folder",
        "folder-open": "ph:folder-open",
        forward: "ph:fast-forward",
        github: "ph:github-logo",
        gitlab: "ph:gitlab-logo-simple",
        globe: "ph:globe",
        google: "ph:google-logo",
        history: "ph:clock-counter-clockwise",
        image: "ph:image",
        "info-circle": "ph:info",
        key: "ph:key",
        link: "ph:link",
        "list-check": "ph:list-checks",
        lock: "ph:lock",
        microphone: "ph:microphone",
        moon: "ph:moon",
        palette: "ph:palette",
        paperclip: "ph:paperclip",
        pencil: "ph:pencil-simple",
        play: "ph:play",
        backward: "ph:skip-back",
        compress: "ph:corners-in",
        expand: "ph:corners-out",
        pause: "ph:pause",
        "picture-in-picture": "ph:picture-in-picture",
        repeat: "ph:repeat",
        "volume-off": "ph:speaker-slash",
        "volume-up": "ph:speaker-high",
        plus: "ph:plus",
        "plus-circle": "ph:plus-circle",
        "question-circle": "ph:question",
        refresh: "ph:arrows-clockwise",
        save: "ph:floppy-disk",
        search: "ph:magnifying-glass",
        send: "ph:paper-plane-tilt",
        server: "ph:hard-drives",
        shield: "ph:shield-check",
        "sign-in": "ph:sign-in",
        "sign-out": "ph:sign-out",
        sitemap: "ph:tree-structure",
        "sliders-h": "ph:sliders-horizontal",
        sparkles: "ph:sparkle",
        spinner: "ph:spinner-gap",
        square: "ph:square",
        star: "ph:star",
        "star-fill": "ph:star-fill",
        stop: "ph:stop-circle",
        sun: "ph:sun",
        sync: "ph:arrows-clockwise",
        "th-large": "ph:squares-four",
        times: "ph:x",
        trash: "ph:trash",
        undo: "ph:arrow-counter-clockwise",
        unlock: "ph:lock-open",
        upload: "ph:upload-simple",
        user: "ph:user",
        users: "ph:users",
        "wave-pulse": "ph:pulse",
        wifi: "ph:wifi-high",
        "window-maximize": "ph:arrows-out",
        "window-minimize": "ph:arrows-in",
    },
    solar: {
        "align-left": "solar:align-left-linear",
        "angle-right": "solar:alt-arrow-right-linear",
        "arrow-circle-up": "solar:round-arrow-up-linear",
        "arrow-down-left": "solar:arrow-left-down-linear",
        "arrow-left": "solar:arrow-left-linear",
        "arrow-right": "solar:arrow-right-linear",
        "arrow-up-right": "solar:arrow-right-up-linear",
        "arrows-h": "solar:transfer-horizontal-linear",
        bars: "solar:hamburger-menu-linear",
        bolt: "solar:bolt-linear",
        box: "solar:box-linear",
        check: "solar:check-read-linear",
        "check-circle": "solar:check-circle-linear",
        "check-square": "solar:check-square-linear",
        "chevron-down": "solar:alt-arrow-down-linear",
        "chevron-right": "solar:alt-arrow-right-linear",
        "chevron-up": "solar:alt-arrow-up-linear",
        circle: "solar:record-circle-linear",
        "circle-fill": "ph:circle-fill",
        clock: "solar:clock-circle-linear",
        clone: "solar:copy-linear",
        cloud: "solar:cloud-linear",
        "cloud-upload": "solar:cloud-upload-linear",
        code: "solar:code-linear",
        cog: "solar:settings-linear",
        "collapse-all": "ph:arrows-in-line-vertical",
        comments: "solar:chat-round-linear",
        copy: "solar:copy-linear",
        "credit-card": "solar:card-2-linear",
        database: "solar:database-linear",
        desktop: "solar:monitor-linear",
        download: "solar:download-linear",
        envelope: "solar:letter-linear",
        eraser: "solar:eraser-linear",
        "exclamation-circle": "solar:danger-circle-linear",
        "exclamation-triangle": "solar:danger-triangle-linear",
        "external-link": "solar:arrow-right-up-linear",
        eye: "solar:eye-linear",
        "eye-slash": "solar:eye-closed-linear",
        file: "solar:file-linear",
        "file-edit": "solar:pen-new-square-linear",
        "file-pdf": "solar:file-text-linear",
        folder: "solar:folder-linear",
        "folder-open": "solar:folder-open-linear",
        forward: "solar:forward-linear",
        github: "ph:github-logo",
        gitlab: "ph:gitlab-logo-simple",
        globe: "solar:global-linear",
        google: "ph:google-logo",
        history: "solar:history-linear",
        image: "solar:gallery-linear",
        "info-circle": "solar:info-circle-linear",
        key: "solar:key-minimalistic-linear",
        link: "solar:link-linear",
        "list-check": "solar:checklist-linear",
        lock: "solar:lock-linear",
        microphone: "solar:microphone-linear",
        moon: "solar:moon-linear",
        palette: "solar:palette-linear",
        paperclip: "solar:paperclip-linear",
        pencil: "solar:pen-2-linear",
        play: "solar:play-linear",
        backward: "solar:rewind-back-linear",
        compress: "solar:minimize-square-linear",
        expand: "solar:maximize-square-linear",
        pause: "solar:pause-linear",
        // Solar ships no picture-in-picture glyph; falls back to Phosphor's, like primeicons' gitlab above.
        "picture-in-picture": "ph:picture-in-picture",
        repeat: "solar:repeat-linear",
        "volume-off": "solar:volume-cross-linear",
        "volume-up": "solar:volume-loud-linear",
        plus: "solar:add-square-linear",
        "plus-circle": "solar:add-circle-linear",
        "question-circle": "solar:question-circle-linear",
        refresh: "solar:refresh-linear",
        save: "solar:diskette-linear",
        search: "solar:magnifer-linear",
        send: "solar:plain-2-linear",
        server: "solar:server-linear",
        shield: "solar:shield-check-linear",
        "sign-in": "solar:login-2-linear",
        "sign-out": "solar:logout-3-linear",
        sitemap: "solar:branching-paths-down-linear",
        "sliders-h": "solar:slider-horizontal-linear",
        sparkles: "solar:magic-stick-3-linear",
        spinner: "solar:refresh-linear",
        square: "solar:stop-linear",
        star: "solar:star-linear",
        "star-fill": "solar:star-bold",
        stop: "solar:stop-circle-linear",
        sun: "solar:sun-linear",
        sync: "solar:restart-linear",
        "th-large": "solar:widget-linear",
        times: "solar:close-circle-linear",
        trash: "solar:trash-bin-trash-linear",
        undo: "solar:undo-left-linear",
        unlock: "solar:lock-unlocked-linear",
        upload: "solar:upload-linear",
        user: "solar:user-linear",
        users: "solar:users-group-rounded-linear",
        "wave-pulse": "solar:pulse-linear",
        wifi: "solar:wi-fi-router-linear",
        "window-maximize": "solar:maximize-linear",
        "window-minimize": "solar:minimize-square-linear",
    },
    remix: {
        "align-left": "ri:align-left",
        "angle-right": "ri:arrow-right-s-line",
        "arrow-circle-up": "ri:arrow-up-circle-line",
        "arrow-down-left": "ri:arrow-left-down-line",
        "arrow-left": "ri:arrow-left-line",
        "arrow-right": "ri:arrow-right-line",
        "arrow-up-right": "ri:arrow-right-up-line",
        "arrows-h": "ri:arrow-left-right-line",
        bars: "ri:menu-line",
        bolt: "ri:flashlight-line",
        box: "ri:box-3-line",
        check: "ri:check-line",
        "check-circle": "ri:checkbox-circle-line",
        "check-square": "ri:checkbox-line",
        "chevron-down": "ri:arrow-down-s-line",
        "chevron-right": "ri:arrow-right-s-line",
        "chevron-up": "ri:arrow-up-s-line",
        circle: "ri:circle-line",
        "circle-fill": "ri:circle-fill",
        clock: "ri:time-line",
        clone: "ri:file-copy-line",
        cloud: "ri:cloud-line",
        "cloud-upload": "ri:upload-cloud-line",
        code: "ri:code-line",
        cog: "ri:settings-3-line",
        "collapse-all": "ph:arrows-in-line-vertical",
        comments: "ri:chat-2-line",
        copy: "ri:file-copy-line",
        "credit-card": "ri:bank-card-line",
        database: "ri:database-2-line",
        desktop: "ri:computer-line",
        download: "ri:download-line",
        envelope: "ri:mail-line",
        eraser: "ri:eraser-line",
        "exclamation-circle": "ri:error-warning-line",
        "exclamation-triangle": "ri:alert-line",
        "external-link": "ri:external-link-line",
        eye: "ri:eye-line",
        "eye-slash": "ri:eye-off-line",
        file: "ri:file-line",
        "file-edit": "ri:file-edit-line",
        "file-pdf": "ri:file-pdf-line",
        folder: "ri:folder-line",
        "folder-open": "ri:folder-open-line",
        forward: "ri:forward-end-line",
        github: "ri:github-line",
        gitlab: "ri:gitlab-line",
        globe: "ri:global-line",
        google: "ri:google-line",
        history: "ri:history-line",
        image: "ri:image-line",
        "info-circle": "ri:information-line",
        key: "ri:key-2-line",
        link: "ri:link",
        "list-check": "ri:list-check",
        lock: "ri:lock-2-line",
        microphone: "ri:mic-line",
        moon: "ri:moon-line",
        palette: "ri:palette-line",
        paperclip: "ri:attachment-line",
        pencil: "ri:pencil-line",
        play: "ri:play-line",
        backward: "ri:rewind-mini-line",
        compress: "ri:fullscreen-exit-line",
        expand: "ri:fullscreen-line",
        pause: "ri:pause-line",
        "picture-in-picture": "ri:picture-in-picture-line",
        repeat: "ri:repeat-2-line",
        "volume-off": "ri:volume-mute-line",
        "volume-up": "ri:volume-up-line",
        plus: "ri:add-line",
        "plus-circle": "ri:add-circle-line",
        "question-circle": "ri:question-line",
        refresh: "ri:refresh-line",
        save: "ri:save-line",
        search: "ri:search-line",
        send: "ri:send-plane-line",
        server: "ri:server-line",
        shield: "ri:shield-check-line",
        "sign-in": "ri:login-box-line",
        "sign-out": "ri:logout-box-line",
        sitemap: "ri:organization-chart",
        "sliders-h": "ri:equalizer-line",
        sparkles: "ri:sparkling-line",
        spinner: "ri:loader-4-line",
        square: "ri:checkbox-blank-line",
        star: "ri:star-line",
        "star-fill": "ri:star-fill",
        stop: "ri:stop-circle-line",
        sun: "ri:sun-line",
        sync: "ri:restart-line",
        "th-large": "ri:layout-grid-line",
        times: "ri:close-line",
        trash: "ri:delete-bin-line",
        undo: "ri:arrow-go-back-line",
        unlock: "ri:lock-unlock-line",
        upload: "ri:upload-line",
        user: "ri:user-line",
        users: "ri:group-line",
        "wave-pulse": "ri:pulse-line",
        wifi: "ri:wifi-line",
        "window-maximize": "ri:fullscreen-line",
        "window-minimize": "ri:fullscreen-exit-line",
    },
    hugeicons: {
        "align-left": "hugeicons:text-align-left",
        "angle-right": "hugeicons:arrow-right-01",
        "arrow-circle-up": "hugeicons:circle-arrow-up-01",
        "arrow-down-left": "hugeicons:arrow-down-left-01",
        "arrow-left": "hugeicons:arrow-left-01",
        "arrow-right": "hugeicons:arrow-right-01",
        "arrow-up-right": "hugeicons:arrow-up-right-01",
        "arrows-h": "hugeicons:arrow-left-right",
        bars: "hugeicons:menu-01",
        bolt: "hugeicons:energy",
        box: "hugeicons:package",
        check: "hugeicons:tick-02",
        "check-circle": "hugeicons:checkmark-circle-02",
        "check-square": "hugeicons:checkmark-square-01",
        "chevron-down": "hugeicons:arrow-down-01",
        "chevron-right": "hugeicons:arrow-right-01",
        "chevron-up": "hugeicons:arrow-up-01",
        circle: "hugeicons:circle",
        "circle-fill": "ph:circle-fill",
        clock: "hugeicons:clock-01",
        clone: "hugeicons:copy-02",
        cloud: "hugeicons:cloud",
        "cloud-upload": "hugeicons:cloud-upload",
        code: "hugeicons:source-code",
        cog: "hugeicons:settings-01",
        "collapse-all": "ph:arrows-in-line-vertical",
        comments: "hugeicons:message-multiple-01",
        copy: "hugeicons:copy-01",
        "credit-card": "hugeicons:credit-card",
        database: "hugeicons:database-01",
        desktop: "hugeicons:computer",
        download: "hugeicons:download-01",
        envelope: "hugeicons:mail-01",
        eraser: "hugeicons:eraser-01",
        "exclamation-circle": "hugeicons:alert-circle",
        "exclamation-triangle": "hugeicons:alert-02",
        "external-link": "hugeicons:square-arrow-up-right",
        eye: "hugeicons:eye",
        "eye-slash": "hugeicons:view-off-slash",
        file: "hugeicons:file-01",
        "file-edit": "hugeicons:file-edit",
        "file-pdf": "hugeicons:pdf-01",
        folder: "hugeicons:folder-01",
        "folder-open": "hugeicons:folder-open",
        forward: "hugeicons:forward-02",
        github: "hugeicons:github",
        gitlab: "hugeicons:gitlab",
        globe: "hugeicons:global",
        google: "hugeicons:google",
        history: "hugeicons:time-04",
        image: "hugeicons:image-01",
        "info-circle": "hugeicons:information-circle",
        key: "hugeicons:key-01",
        link: "hugeicons:link-01",
        "list-check": "hugeicons:task-01",
        lock: "hugeicons:square-lock-02",
        microphone: "hugeicons:mic-01",
        moon: "hugeicons:moon-02",
        palette: "hugeicons:paint-board",
        paperclip: "hugeicons:attachment-01",
        pencil: "hugeicons:pencil-edit-01",
        play: "hugeicons:play",
        backward: "hugeicons:backward-01",
        compress: "hugeicons:square-arrow-shrink-02",
        expand: "hugeicons:full-screen",
        pause: "hugeicons:pause",
        "picture-in-picture": "hugeicons:picture-in-picture-on",
        repeat: "hugeicons:repeat",
        "volume-off": "hugeicons:volume-mute-02",
        "volume-up": "hugeicons:volume-high",
        plus: "hugeicons:add-01",
        "plus-circle": "hugeicons:add-circle",
        "question-circle": "hugeicons:help-circle",
        refresh: "hugeicons:refresh",
        save: "hugeicons:floppy-disk",
        search: "hugeicons:search-01",
        send: "hugeicons:navigation-01",
        server: "hugeicons:server-stack-01",
        shield: "hugeicons:shield-01",
        "sign-in": "hugeicons:login-03",
        "sign-out": "hugeicons:logout-03",
        sitemap: "hugeicons:hierarchy",
        "sliders-h": "hugeicons:sliders-horizontal",
        sparkles: "hugeicons:sparkles",
        spinner: "hugeicons:loading-03",
        square: "hugeicons:square",
        star: "hugeicons:star",
        "star-fill": "ph:star-fill",
        stop: "hugeicons:stop-circle",
        sun: "hugeicons:sun-03",
        sync: "hugeicons:arrow-reload-horizontal",
        "th-large": "hugeicons:grid-view",
        times: "hugeicons:cancel-01",
        trash: "hugeicons:delete-02",
        undo: "hugeicons:undo",
        unlock: "hugeicons:square-unlock-02",
        upload: "hugeicons:upload-01",
        user: "hugeicons:user",
        users: "hugeicons:user-multiple",
        "wave-pulse": "hugeicons:pulse-02",
        wifi: "hugeicons:wifi-01",
        "window-maximize": "hugeicons:maximize-01",
        "window-minimize": "hugeicons:minimize-02",
    },
    primeicons: {
        "align-left": "prime:align-left",
        "angle-right": "prime:angle-right",
        "arrow-circle-up": "prime:arrow-circle-up",
        "arrow-down-left": "prime:arrow-down-left",
        "arrow-left": "prime:arrow-left",
        "arrow-right": "prime:arrow-right",
        "arrow-up-right": "prime:arrow-up-right",
        "arrows-h": "prime:arrows-h",
        bars: "prime:bars",
        bolt: "prime:bolt",
        box: "prime:box",
        check: "prime:check",
        "check-circle": "prime:check-circle",
        "check-square": "prime:check-square",
        "chevron-down": "prime:chevron-down",
        "chevron-right": "prime:chevron-right",
        "chevron-up": "prime:chevron-up",
        circle: "prime:circle",
        "circle-fill": "prime:circle-fill",
        clock: "prime:clock",
        clone: "prime:clone",
        cloud: "prime:cloud",
        "cloud-upload": "prime:cloud-upload",
        code: "prime:code",
        cog: "prime:cog",
        "collapse-all": "ph:arrows-in-line-vertical",
        comments: "prime:comments",
        copy: "prime:copy",
        "credit-card": "prime:credit-card",
        database: "prime:database",
        desktop: "prime:desktop",
        download: "prime:download",
        envelope: "prime:envelope",
        eraser: "prime:eraser",
        "exclamation-circle": "prime:exclamation-circle",
        "exclamation-triangle": "prime:exclamation-triangle",
        "external-link": "prime:external-link",
        eye: "prime:eye",
        "eye-slash": "prime:eye-slash",
        file: "prime:file",
        "file-edit": "prime:file-edit",
        "file-pdf": "prime:file-pdf",
        folder: "prime:folder",
        "folder-open": "prime:folder-open",
        forward: "prime:forward",
        github: "prime:github",
        gitlab: "ph:gitlab-logo-simple",
        globe: "prime:globe",
        google: "prime:google",
        history: "prime:history",
        image: "prime:image",
        "info-circle": "prime:info-circle",
        key: "prime:key",
        link: "prime:link",
        "list-check": "prime:list-check",
        lock: "prime:lock",
        microphone: "prime:microphone",
        moon: "prime:moon",
        palette: "prime:palette",
        paperclip: "prime:paperclip",
        pencil: "prime:pencil",
        play: "prime:play",
        backward: "prime:backward",
        compress: "prime:window-minimize",
        expand: "prime:window-maximize",
        pause: "prime:pause",
        "picture-in-picture": "prime:clone",
        repeat: "prime:replay",
        "volume-off": "prime:volume-off",
        "volume-up": "prime:volume-up",
        plus: "prime:plus",
        "plus-circle": "prime:plus-circle",
        "question-circle": "prime:question-circle",
        refresh: "prime:refresh",
        save: "prime:save",
        search: "prime:search",
        send: "prime:send",
        server: "prime:server",
        shield: "prime:shield",
        "sign-in": "prime:sign-in",
        "sign-out": "prime:sign-out",
        sitemap: "prime:sitemap",
        "sliders-h": "prime:sliders-h",
        sparkles: "prime:sparkles",
        spinner: "prime:spinner",
        square: "prime:stop",
        star: "prime:star",
        "star-fill": "prime:star-fill",
        stop: "prime:stop",
        sun: "prime:sun",
        sync: "prime:sync",
        "th-large": "prime:th-large",
        times: "prime:times",
        trash: "prime:trash",
        undo: "prime:undo",
        unlock: "prime:unlock",
        upload: "prime:upload",
        user: "prime:user",
        users: "prime:users",
        "wave-pulse": "prime:wave-pulse",
        wifi: "prime:wifi",
        "window-maximize": "prime:window-maximize",
        "window-minimize": "prime:window-minimize",
    },
};
