// The files Cursor's hooks run: the script every hook calls (node, which, unlike curl, is guaranteed to be in the image)
// and the enterprise hooks file naming it, plus the shape of a shell command the privacy shield wraps. Kept apart from
// the service that answers them (cursor-hooks.ts) because this is text another process runs, not code this one does.

export const GATE_SCRIPT_NAME = "intentic-command-guard.mjs";

// The mode a wrapped shell command runs the script in, and the form the command takes. A command the shield wraps runs
// through the script, which runs the real command and hands what it prints to the daemon to mask before Cursor (and so
// its model) reads it. Cursor writes the wrapper into the call's own arguments and sends it back to its servers in the
// shell's result, so the wrapper carries no real value: only an opaque id, by which the script fetches the command with
// its values once from the daemon (cursor-hooks.ts), and, as base64 so no shell reads anything into it, the command as
// the model wrote it, tokens and all, for whatever shows the call.
const SHIELD_MODE = "shield";
const quoted = (text: string): string => `'${text.replaceAll("'", `'\\''`)}'`;
const WRAPPED = new RegExp(String.raw`^node '(?:[^']|'\\'')+' ${SHIELD_MODE} '(?:[^']|'\\'')+' ([A-Za-z0-9-]+) ([A-Za-z0-9+/=]*)$`, "u");

export const shieldedCommand = (script: string, turn: string, id: string, shown: string): string =>
    `node ${quoted(script)} ${SHIELD_MODE} ${quoted(turn)} ${id} ${Buffer.from(shown, "utf8").toString("base64")}`;

// A wrapped command's id and the command as the model wrote it; undefined for any other command.
export const wrappedCommand = (command: string): { readonly id: string; readonly shown: string } | undefined => {
    const wrapped = WRAPPED.exec(command);
    return wrapped?.[1] === undefined || wrapped[2] === undefined ? undefined : { id: wrapped[1], shown: Buffer.from(wrapped[2], "base64").toString("utf8") };
};

// The command a wrapped one stands for as the model wrote it, so the transcript reads what the model asked for rather
// than the wrapper; any other command as it is.
export const unshieldedCommand = (command: string): string => wrappedCommand(command)?.shown ?? command;

// Every failure path answers the harmless verdict silently, since an unregistered call is usually the owner's own manual
// run: no environment, no added context, an allowed command, an untouched tool call. A shielded command is the
// exception: the daemon not answering means its output cannot be masked, so it is withheld rather than sent.
// The script is plain JavaScript with no template literals, so nothing in it can be read as this file's interpolation.
export const gateScript = (socketPath: string): string =>
    [
        `// managed by intentic: overwritten on daemon boot (src/runtimes/cursor/cursor-hook-script.ts).`,
        `// Asks the daemon for the current turn's environment, its standing instructions, a command-guard verdict, and the`,
        `// privacy shield's word on a file read, a tool call and an edited file; and runs a shielded shell command, so what it`,
        `// prints reaches the model only as the shield lets it.`,
        `import { request } from "node:http";`,
        `import { spawn } from "node:child_process";`,
        `import { closeSync, existsSync, openSync, readFileSync, readSync, statSync, writeFileSync } from "node:fs";`,
        `import { constants } from "node:os";`,
        `import { extname, isAbsolute, resolve } from "node:path";`,
        `import { StringDecoder } from "node:string_decoder";`,
        ``,
        `const SOCKET = ${JSON.stringify(socketPath)};`,
        `const MODES = {`,
        `    "session-env": { path: "/session-env", fallback: {} },`,
        `    prompt: { path: "/prompt", fallback: { continue: true } },`,
        `    gate: { path: "/gate", fallback: { permission: "allow" } },`,
        `    "pre-tool": { path: "/pre-tool", fallback: {} },`,
        `    read: { path: "/read", fallback: { permission: "allow" } },`,
        `};`,
        `const TOKEN = /\\u27e6[A-Z][A-Z_]*?_\\d{1,7}\\u27e7|\\[\\[[A-Z][A-Z_]*?_\\d{1,7}\\]\\]/u;`,
        `const IMAGE = new Set([".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".tif", ".tiff"]);`,
        `const MAX_TEXT = 4 * 1024 * 1024;`,
        `const MAX_IMAGE = 16 * 1024 * 1024;`,
        `const MAX_DOCUMENT = 16 * 1024 * 1024;`,
        `// A line too long to wait for is cut where no value the shield finds can straddle the cut, and never closer to its end`,
        `// than this, so what is held back still holds the whole of a value that started before the read ended.`,
        `const LONG_LINE = 65536;`,
        `const TAIL = 1024;`,
        `const NOT_FETCHED = "[Not run: the privacy shield could not be reached to hand over this command.]\\n";`,
        `const WITHHELD = "\\n[The rest of this command's output was withheld: the privacy shield could not be reached to mask it.]\\n";`,
        ``,
        `const ask = (path, body) =>`,
        `    new Promise((settle, fail) => {`,
        `        const call = request({ socketPath: SOCKET, path, method: "POST", headers: { "content-type": "application/json" } }, (response) => {`,
        `            const parts = [];`,
        `            response.on("data", (part) => parts.push(part));`,
        `            response.on("error", fail);`,
        `            response.on("end", () => {`,
        `                // Anything but a well-formed answer is treated as no answer at all.`,
        `                try {`,
        `                    settle(JSON.parse(Buffer.concat(parts).toString("utf8")));`,
        `                } catch (error) {`,
        `                    fail(error);`,
        `                }`,
        `            });`,
        `        });`,
        `        call.on("error", fail);`,
        `        call.end(JSON.stringify(body));`,
        `    });`,
        ``,
        `const stdin = () =>`,
        `    new Promise((settle) => {`,
        `        const chunks = [];`,
        `        process.stdin.on("data", (chunk) => chunks.push(chunk));`,
        `        process.stdin.on("error", () => settle(""));`,
        `        process.stdin.on("end", () => settle(Buffer.concat(chunks).toString("utf8")));`,
        `    });`,
        ``,
        `const parsed = (text) => {`,
        `    try {`,
        `        const value = JSON.parse(text);`,
        `        return typeof value === "object" && value !== null && !Array.isArray(value) ? value : undefined;`,
        `    } catch {`,
        `        return undefined;`,
        `    }`,
        `};`,
        `const pathOf = (raw, cwd) => (typeof raw !== "string" || raw === "" ? undefined : isAbsolute(raw) ? raw : resolve(typeof cwd === "string" ? cwd : process.cwd(), raw));`,
        `const sizeOf = (path) => {`,
        `    try {`,
        `        const stat = statSync(path);`,
        `        return stat.isFile() ? stat.size : undefined;`,
        `    } catch {`,
        `        return undefined;`,
        `    }`,
        `};`,
        `// What Cursor's read tool sends its model as raw bytes, telling the read hook only content "": a PDF (by its extension,`,
        `// as Cursor decides, or its signature) and a picture (by its signature, as Cursor decides, or a listed extension).`,
        `const headOf = (path) => {`,
        `    const fd = openSync(path, "r");`,
        `    try {`,
        `        const head = Buffer.alloc(16);`,
        `        return head.subarray(0, readSync(fd, head, 0, 16, 0));`,
        `    } finally {`,
        `        closeSync(fd);`,
        `    }`,
        `};`,
        `const PICTURE_SIGNATURES = [[0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a], [0xff, 0xd8, 0xff], [0x47, 0x49, 0x46, 0x38]];`,
        `const kindOf = (path, head) => {`,
        `    const starts = (bytes, at = 0) => bytes.every((byte, index) => head[at + index] === byte);`,
        `    const webp = head.subarray(0, 4).toString("latin1") === "RIFF" && head.subarray(8, 12).toString("latin1") === "WEBP";`,
        `    if (extname(path).toLowerCase() === ".pdf" || head.subarray(0, 5).toString("latin1") === "%PDF-") {`,
        `        return "document";`,
        `    }`,
        `    return webp || PICTURE_SIGNATURES.some((signature) => starts(signature)) || IMAGE.has(extname(path).toLowerCase()) ? "image" : "opaque";`,
        `};`,
        `// A read whose content Cursor did not hand the hook: the file's bytes, for the daemon to check or refuse. Cursor says`,
        `// nothing of what it sent, so a file that is not empty and is neither a picture nor a PDF (a video, which Cursor also`,
        `// sends as bytes) is marked opaque, and one that could not be looked at here is too.`,
        `const attachUnread = (payload, path) => {`,
        `    const size = path === undefined ? undefined : sizeOf(path);`,
        `    if (size === 0) {`,
        `        return;`,
        `    }`,
        `    const kind = size === undefined ? "opaque" : kindOf(path, headOf(path));`,
        `    if (kind === "image") {`,
        `        payload.image_base64 = size > MAX_IMAGE ? "" : readFileSync(path).toString("base64");`,
        `    } else if (kind === "document") {`,
        `        payload.document_base64 = size > MAX_DOCUMENT ? "" : readFileSync(path).toString("base64");`,
        `    } else {`,
        `        payload.opaque = true;`,
        `    }`,
        `};`,
        `const textOf = (path) => {`,
        `    const size = sizeOf(path);`,
        `    return size === undefined || size > MAX_TEXT ? undefined : readFileSync(path, "utf8");`,
        `};`,
        ``,
        `// A hook that answers: the payload, with what only this side of a mount namespace can read added, to the daemon.`,
        `const answer = async (mode) => {`,
        `    const spec = MODES[mode] ?? MODES.gate;`,
        `    const payload = parsed(await stdin());`,
        `    if (payload === undefined) {`,
        `        process.stdout.write(JSON.stringify(spec.fallback));`,
        `        return;`,
        `    }`,
        `    try {`,
        `        // What Cursor read as bytes is read here, where its path means what Cursor meant by it; empty when too large to`,
        `        // check. A picture by its extension is read whatever content says, as before.`,
        `        if (mode === "read") {`,
        `            const path = pathOf(payload.file_path, payload.cwd);`,
        `            if (typeof payload.content !== "string" || payload.content === "") {`,
        `                attachUnread(payload, path);`,
        `            } else if (path !== undefined && IMAGE.has(extname(path).toLowerCase())) {`,
        `                const size = sizeOf(path);`,
        `                payload.image_base64 = size === undefined || size > MAX_IMAGE ? "" : readFileSync(path).toString("base64");`,
        `            }`,
        `        }`,
        `        // A whole-file write over a file that exists: what it replaces, which the write's result would echo back.`,
        `        if (mode === "pre-tool" && payload.tool_name === "Write" && typeof payload.tool_input === "object" && payload.tool_input !== null) {`,
        `            const path = pathOf(payload.tool_input.file_path, payload.cwd);`,
        `            const existing = path === undefined ? undefined : textOf(path);`,
        `            if (existing !== undefined) {`,
        `                payload.existing_content = existing;`,
        `            }`,
        `        }`,
        `    } catch {`,
        `        // allow(silent-catch): what could not be read here is left for the daemon to decide on without it; a read`,
        `        // whose content Cursor did not hand over is marked opaque, which a shielded turn refuses.`,
        `        if (mode === "read" && (typeof payload.content !== "string" || payload.content === "")) {`,
        `            payload.opaque = true;`,
        `        }`,
        `    }`,
        `    try {`,
        `        process.stdout.write(JSON.stringify(await ask(spec.path, payload)));`,
        `    } catch {`,
        `        process.stdout.write(JSON.stringify(spec.fallback));`,
        `    }`,
        `};`,
        ``,
        `// An edited file whose new lines carry tokens: the daemon reads them back to their values, and this writes the file.`,
        `// Prints nothing either way: an answer would have Cursor read the file back into its model, values and all.`,
        `const edited = async () => {`,
        `    const text = await stdin();`,
        `    if (!TOKEN.test(text)) {`,
        `        return;`,
        `    }`,
        `    const payload = parsed(text);`,
        `    const path = payload === undefined ? undefined : pathOf(payload.file_path, payload.cwd);`,
        `    const content = path === undefined ? undefined : textOf(path);`,
        `    if (content === undefined || !TOKEN.test(content)) {`,
        `        return;`,
        `    }`,
        `    try {`,
        `        const reply = await ask("/edited", { conversation_id: payload.conversation_id, file_path: path, content, edits: payload.edits ?? [] });`,
        `        if (typeof reply.content === "string" && reply.content !== content) {`,
        `            writeFileSync(path, reply.content);`,
        `        }`,
        `    } catch {`,
        `        // allow(silent-catch): the file keeps its tokens, which the vault can still read back; nothing else is at stake.`,
        `    }`,
        `};`,
        ``,
        `// Where a line too long to hold whole is cut, at least TAIL from its end (so the value the last read may have split`,
        `// is held back whole, with the context before it): the best gap in the stretch before that. Best is a space with no`,
        `// digit, capital or @ within QUIET of it either side, where no value nor the label that announces one can be; then a`,
        `// space between two lowercase words, which no name, number or address spans; then any space; then a cell separator;`,
        `// then any punctuation; and only in a run with no gap at all at TAIL from the end.`,
        `const QUIET = 64;`,
        `const LOUD = /[\\p{Lu}\\d@]/u;`,
        `const longCut = (text) => {`,
        `    const limit = text.length - TAIL;`,
        `    const found = [-1, -1, -1, -1, -1];`,
        `    for (let at = limit - 1; at > 0 && at >= limit - 16384; at -= 1) {`,
        `        const char = text[at];`,
        `        if (char === " " || char === "\\t") {`,
        `            if (found[0] < 0 && !LOUD.test(text.slice(Math.max(0, at - QUIET), at + QUIET))) {`,
        `                found[0] = at + 1;`,
        `                break;`,
        `            }`,
        `            if (found[1] < 0 && /\\p{Ll}/u.test(text[at + 1] ?? "") && /(?:^|\\s)\\p{Ll}\\S*$/u.test(text.slice(Math.max(0, at - 48), at))) {`,
        `                found[1] = at + 1;`,
        `            }`,
        `            if (found[2] < 0) {`,
        `                found[2] = at + 1;`,
        `            }`,
        `        } else if (found[3] < 0 && (char === "," || char === ";" || char === "|")) {`,
        `            found[3] = at + 1;`,
        `        } else if (found[4] < 0 && /[&="'<>(){}\\[\\]]/u.test(char)) {`,
        `            found[4] = at + 1;`,
        `        }`,
        `    }`,
        `    return found.find((at) => at > 0) ?? limit;`,
        `};`,
        ``,
        `// A shielded shell command: run here, its output handed to the daemon a stretch at a time and printed as masked.`,
        `const shielded = async () => {`,
        `    const turn = process.argv[3] ?? "";`,
        `    // The command with its values, fetched once by the id the wrapper carries: it never stands in Cursor's arguments.`,
        `    let fetched;`,
        `    try {`,
        `        fetched = await ask("/shell-command", { conversation_id: turn, id: process.argv[4] ?? "" });`,
        `    } catch {`,
        `        fetched = undefined;`,
        `    }`,
        `    if (typeof fetched?.command !== "string") {`,
        `        process.stdout.write(typeof fetched?.refused === "string" ? fetched.refused : NOT_FETCHED);`,
        `        process.exit(1);`,
        `    }`,
        `    const command = fetched.command;`,
        `    // bash first, as every agent writes its commands for it; the owner's own shell only where there is no bash.`,
        `    const shell = ["/bin/bash", "/usr/bin/bash", process.env.SHELL, "/bin/sh"].find((path) => typeof path === "string" && path !== "" && existsSync(path)) ?? "/bin/sh";`,
        `    const options = { stdio: ["inherit", "pipe", "inherit"], ...(typeof fetched.cwd === "string" ? { cwd: fetched.cwd } : {}) };`,
        // allow(process-tiers): the script runs outside the daemon, as Cursor's own child, where no runCheck or spawnAs exists.
        `    const child = spawn(shell, ["-c", "exec 2>&1\\n" + command], options);`,
        `    const decoder = new StringDecoder("utf8");`,
        `    let held = "";`,
        `    let withheld = false;`,
        `    let chain = Promise.resolve();`,
        `    let timer;`,
        `    const send = (text) => {`,
        `        chain = chain.then(async () => {`,
        `            if (withheld || text === "") {`,
        `                return;`,
        `            }`,
        `            try {`,
        `                const reply = await ask("/shell-output", { conversation_id: turn, output: text });`,
        `                if (typeof reply.output !== "string") {`,
        `                    throw new Error("no output");`,
        `                }`,
        `                process.stdout.write(reply.output);`,
        `            } catch {`,
        `                withheld = true;`,
        `                process.stdout.write(WITHHELD);`,
        `            }`,
        `        });`,
        `    };`,
        `    // Whole lines while the command runs, so a value is never split between two maskings; everything at the end. A`,
        `    // line too long to hold whole is cut at a gap between words (longCut).`,
        `    const flush = (all) => {`,
        `        clearTimeout(timer);`,
        `        timer = undefined;`,
        `        const line = held.lastIndexOf("\\n") + 1;`,
        `        const cut = all ? held.length : line > 0 || held.length < LONG_LINE ? line : longCut(held);`,
        `        if (cut > 0) {`,
        `            send(held.slice(0, cut));`,
        `            held = held.slice(cut);`,
        `        }`,
        `    };`,
        `    child.stdout.on("data", (chunk) => {`,
        `        held += decoder.write(chunk);`,
        `        if (held.length >= LONG_LINE) {`,
        `            flush(false);`,
        `        } else if (timer === undefined) {`,
        `            timer = setTimeout(() => flush(false), 200);`,
        `        }`,
        `    });`,
        `    let status;`,
        `    let closed = false;`,
        `    let finished = false;`,
        `    const finish = () => {`,
        `        if (finished || status === undefined) {`,
        `            return;`,
        `        }`,
        `        finished = true;`,
        `        held += decoder.end();`,
        `        flush(true);`,
        `        void chain.then(() => process.exit(status));`,
        `    };`,
        `    child.stdout.on("close", () => {`,
        `        closed = true;`,
        `        finish();`,
        `    });`,
        `    child.on("error", (error) => {`,
        `        held += "failed to start " + shell + ": " + error.message + "\\n";`,
        `        status = 127;`,
        `        finish();`,
        `    });`,
        `    // A job the command left running in the background can hold the pipe open for ever, so the command's own exit`,
        `    // ends this a moment later whether or not the pipe has closed.`,
        `    child.on("exit", (code, signal) => {`,
        `        status = code ?? (signal ? 128 + (constants.signals[signal] ?? 1) : 1);`,
        `        if (closed) {`,
        `            finish();`,
        `        } else {`,
        `            setTimeout(finish, 250);`,
        `        }`,
        `    });`,
        `    for (const signal of ["SIGINT", "SIGTERM", "SIGHUP"]) {`,
        `        process.on(signal, () => child.kill(signal));`,
        `    }`,
        `};`,
        ``,
        `const mode = process.argv[2];`,
        `if (mode === ${JSON.stringify(SHIELD_MODE)}) {`,
        `    void shielded();`,
        `} else if (mode === "edited") {`,
        `    void edited();`,
        `} else {`,
        `    void answer(mode);`,
        `}`,
        ``,
    ].join("\n");

// sessionStart projects the turn's env; beforeSubmitPrompt folds the daemon's instructions onto Cursor's base;
// beforeShellExecution enforces the rulebook; preToolUse, beforeReadFile and afterFileEdit are the privacy shield's
// (cursor-shield.ts), and pass everything through for a turn it is not reading. The rulebook and the shield's two
// gates fail closed: a command that outran its rules and a file read nobody checked are what they exist to stop, while a
// turn without its environment, its instructions or an edit's tokens read back is merely degraded.
// afterShellExecution is skipped, its return value is discarded upstream, which is why the secrets axis reads "none".
export const hooksJson = (scriptPath: string): string =>
    `${JSON.stringify(
        {
            version: 1,
            hooks: {
                sessionStart: [{ command: `node ${JSON.stringify(scriptPath)} session-env`, failClosed: false }],
                beforeSubmitPrompt: [{ command: `node ${JSON.stringify(scriptPath)} prompt`, failClosed: false }],
                beforeShellExecution: [{ command: `node ${JSON.stringify(scriptPath)} gate`, failClosed: true }],
                preToolUse: [{ command: `node ${JSON.stringify(scriptPath)} pre-tool`, failClosed: true }],
                beforeReadFile: [{ command: `node ${JSON.stringify(scriptPath)} read`, failClosed: true }],
                afterFileEdit: [{ command: `node ${JSON.stringify(scriptPath)} edited`, failClosed: false }],
            },
        },
        undefined,
        4,
    )}\n`;
